/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Supported load-carrier types. MODULAR carriers are semi-trailers (need a separate tractor unit); MONOLITHIC carriers are self-contained rigid vehicle bodies. These are generic loadable-space categories — concrete brand-models live in the vehicles catalog.

 */
export type CarrierType = typeof CarrierType[keyof typeof CarrierType];


export const CarrierType = {
  'standard-curtainside': 'standard-curtainside',
  mega: 'mega',
  reefer: 'reefer',
  van: 'van',
  'box-truck': 'box-truck',
} as const;
