/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { CarrierType } from './carrierType';
import type { VehicleClass } from './vehicleClass';

/**
 * Details of the load carrier assigned to the load plan.
 */
export interface CarrierReadModel {
  type: CarrierType;
  vehicleClass: VehicleClass;
  /** True when the carrier is MODULAR (a semi-trailer) and therefore needs a separate tractor unit to be moved. This module does not reserve the tractor; the flag signals the requirement to downstream fleet/dispatch.
 */
  requiresTractor: boolean;
  canCarryPallets: boolean;
  /** Maximum weight capacity in kilograms */
  maxWeightCapacityKg: number;
  /** Internal loading-space width in millimetres */
  widthMm: number;
  /** Internal loading-space height in millimetres */
  heightMm: number;
  /** Maximum loading metres (LDM). For sub-2.4 m bodies (vans) this is an approximation. */
  maxLdm: number;
}
