/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { CarrierType } from './carrierType';

/**
 * Payload for changing the carrier type on a load plan.
 */
export interface ChangeCarrierInput {
  carrierType: CarrierType;
}
