/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorResponse } from './errorResponse';

/**
 * The request conflicts with the current state (e.g. duplicate or referenced resource).
 */
export type ConflictResponse = ErrorResponse;
