/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorResponse } from './errorResponse';

/**
 * The requested resource was not found.
 */
export type NotFoundResponse = ErrorResponse;
