/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Supported trailer types
 */
export type SchemasTrailerType = typeof SchemasTrailerType[keyof typeof SchemasTrailerType];


export const SchemasTrailerType = {
  'standard-curtainside': 'standard-curtainside',
  mega: 'mega',
  reefer: 'reefer',
} as const;
