/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { VehicleHistoryEventCreateInputEventType } from './vehicleHistoryEventCreateInputEventType';

export interface VehicleHistoryEventCreateInput {
  event_type: VehicleHistoryEventCreateInputEventType;
  event_date: string;
  /**
   * @minimum 0
   * @nullable
   */
  mileage_km?: number | null;
  /** @nullable */
  description?: string | null;
}
