/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type VehicleModelUpdateInputTrailerType = typeof VehicleModelUpdateInputTrailerType[keyof typeof VehicleModelUpdateInputTrailerType] | null;


export const VehicleModelUpdateInputTrailerType = {
  reefer: 'reefer',
  curtain: 'curtain',
  isotherm: 'isotherm',
  tipper: 'tipper',
  platform: 'platform',
  tank: 'tank',
  container: 'container',
} as const;
