/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface VehicleBrandCreateInput {
  /**
   * @minLength 1
   * @maxLength 80
   */
  name: string;
  /**
   * @maxLength 80
   * @nullable
   */
  country?: string | null;
}
