/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Techniczne atrybuty zależne od typu (JSONB).
Ciągnik: {power_kw, euro_norm, axles, fuel_type};
naczepa: {euro_pallets, volume_m3, interior_height_m, has_tail_lift, has_refrigeration}.

 * @nullable
 */
export type VehicleSpecs = { [key: string]: unknown } | null;
