/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

export type VehicleDocumentCreateInputDocType = typeof VehicleDocumentCreateInputDocType[keyof typeof VehicleDocumentCreateInputDocType];


export const VehicleDocumentCreateInputDocType = {
  registration_certificate: 'registration_certificate',
  insurance_oc: 'insurance_oc',
  insurance_ac: 'insurance_ac',
  technical_inspection: 'technical_inspection',
  tachograph: 'tachograph',
  atp_certificate: 'atp_certificate',
  other: 'other',
} as const;
