/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

export type VehicleHistoryEventCreateInputEventType = typeof VehicleHistoryEventCreateInputEventType[keyof typeof VehicleHistoryEventCreateInputEventType];


export const VehicleHistoryEventCreateInputEventType = {
  purchase: 'purchase',
  inspection: 'inspection',
  repair: 'repair',
  accident: 'accident',
  mileage_reading: 'mileage_reading',
  status_change: 'status_change',
  sold: 'sold',
} as const;
