/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A single history event (zdarzenie historii) of a vehicle.
 */
export interface VehicleHistoryEvent {
  id: number;
  vehicle_id: number;
  /** purchase | inspection | repair | accident | mileage_reading | status_change | sold */
  event_type: string;
  event_date: string;
  /** @nullable */
  mileage_km?: number | null;
  /** @nullable */
  description?: string | null;
}
