/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { VehicleDocumentCreateInputDocType } from './vehicleDocumentCreateInputDocType';

export interface VehicleDocumentCreateInput {
  doc_type: VehicleDocumentCreateInputDocType;
  /**
   * @maxLength 60
   * @nullable
   */
  document_number?: string | null;
  /** @nullable */
  issue_date?: string | null;
  /** @nullable */
  expiry_date?: string | null;
  /** @nullable */
  file_url?: string | null;
  /** @nullable */
  notes?: string | null;
}
