/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Rodzaj pojazdu. Modularne: TRACTOR_UNIT (ciągnik siodłowy) + SEMI_TRAILER (naczepa). Monolityczne (samodzielne): VAN (furgon) + BOX_TRUCK (ciężarówka ze stałą zabudową).

 */
export type VehicleKind = typeof VehicleKind[keyof typeof VehicleKind];


export const VehicleKind = {
  TRACTOR_UNIT: 'TRACTOR_UNIT',
  SEMI_TRAILER: 'SEMI_TRAILER',
  VAN: 'VAN',
  BOX_TRUCK: 'BOX_TRUCK',
} as const;
