/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A vehicle brand (marka).
 */
export interface VehicleBrand {
  id: number;
  /** @maxLength 80 */
  name: string;
  /**
   * @maxLength 80
   * @nullable
   */
  country?: string | null;
}
