/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type VehicleCreateInputKind = typeof VehicleCreateInputKind[keyof typeof VehicleCreateInputKind] | null;


export const VehicleCreateInputKind = {
  TRACTOR_UNIT: 'TRACTOR_UNIT',
  SEMI_TRAILER: 'SEMI_TRAILER',
  VAN: 'VAN',
  BOX_TRUCK: 'BOX_TRUCK',
} as const;
