/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { VehicleKind } from './vehicleKind';
import type { VehicleModelUpdateInputTrailerType } from './vehicleModelUpdateInputTrailerType';

/**
 * Partial update — only provided fields are changed.
 */
export interface VehicleModelUpdateInput {
  brandId?: number;
  /**
   * @minLength 1
   * @maxLength 120
   */
  name?: string;
  kind?: VehicleKind;
  /** @nullable */
  trailerType?: VehicleModelUpdateInputTrailerType;
}
