/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type VehicleModelCreateInputTrailerType = typeof VehicleModelCreateInputTrailerType[keyof typeof VehicleModelCreateInputTrailerType] | null;


export const VehicleModelCreateInputTrailerType = {
  reefer: 'reefer',
  curtain: 'curtain',
  isotherm: 'isotherm',
  tipper: 'tipper',
  platform: 'platform',
  tank: 'tank',
  container: 'container',
} as const;
