/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Shape of the carrier: MONOLITHIC (single self-contained vehicle body) or MODULAR (a towed semi-trailer that requires a tractor unit).

 */
export type VehicleClass = typeof VehicleClass[keyof typeof VehicleClass];


export const VehicleClass = {
  MONOLITHIC: 'MONOLITHIC',
  MODULAR: 'MODULAR',
} as const;
