/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Wymagane dla SEMI_TRAILER, puste dla TRACTOR_UNIT.
 * @nullable
 */
export type VehicleModelTrailerType = typeof VehicleModelTrailerType[keyof typeof VehicleModelTrailerType] | null;


export const VehicleModelTrailerType = {
  reefer: 'reefer',
  curtain: 'curtain',
  isotherm: 'isotherm',
  tipper: 'tipper',
  platform: 'platform',
  tank: 'tank',
  container: 'container',
} as const;
