/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A document (dokument) attached to a vehicle.
 */
export interface VehicleDocument {
  id: number;
  vehicle_id: number;
  /** registration_certificate | insurance_oc | insurance_ac | technical_inspection | tachograph | atp_certificate | other */
  doc_type: string;
  /**
   * @maxLength 60
   * @nullable
   */
  document_number?: string | null;
  /** @nullable */
  issue_date?: string | null;
  /** @nullable */
  expiry_date?: string | null;
  /** @nullable */
  file_url?: string | null;
  /** @nullable */
  notes?: string | null;
}
