/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { VehicleCreateInput } from './vehicleCreateInput';

/**
 * Payload for updating an existing vehicle. All fields are optional (partial update). Provide only the fields you want to change.

 */
export type VehicleUpdateInput = VehicleCreateInput;
