/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetVehicleModelsParams,
  VehicleModel,
  VehicleModelCreateInput,
  VehicleModelListResponse,
  VehicleModelUpdateInput
} from '../model';




  export const getVehicleModels = (axiosInstance: AxiosInstance = axios) => {
/**
 * Returns a paginated list of vehicle models (modele). Each model belongs to a brand and is either a TRACTOR_UNIT (ciągnik siodłowy) or a SEMI_TRAILER (naczepa) — for trailers, `trailerType` describes the body kind.

 * @summary List vehicle models
 */
const getVehicleModels = (
    params?: GetVehicleModelsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleModelListResponse>> => {
    return axiosInstance.get(
      `/vehicle-models`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Create a vehicle model
 */
const createVehicleModel = (
    vehicleModelCreateInput: VehicleModelCreateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleModel>> => {
    return axiosInstance.post(
      `/vehicle-models`,
      vehicleModelCreateInput,options
    );
  }
/**
 * @summary Get vehicle model by ID
 */
const getVehicleModelById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleModel>> => {
    return axiosInstance.get(
      `/vehicle-models/${id}`,options
    );
  }
/**
 * @summary Update a vehicle model
 */
const updateVehicleModel = (
    id: number,
    vehicleModelUpdateInput: VehicleModelUpdateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleModel>> => {
    return axiosInstance.put(
      `/vehicle-models/${id}`,
      vehicleModelUpdateInput,options
    );
  }
/**
 * @summary Delete a vehicle model
 */
const deleteVehicleModel = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/vehicle-models/${id}`,options
    );
  }
return {getVehicleModels,createVehicleModel,getVehicleModelById,updateVehicleModel,deleteVehicleModel}};
export type GetVehicleModelsResult = AxiosResponse<VehicleModelListResponse>
export type CreateVehicleModelResult = AxiosResponse<VehicleModel>
export type GetVehicleModelByIdResult = AxiosResponse<VehicleModel>
export type UpdateVehicleModelResult = AxiosResponse<VehicleModel>
export type DeleteVehicleModelResult = AxiosResponse<void>
