/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetVehicleBrandsParams,
  VehicleBrand,
  VehicleBrandCreateInput,
  VehicleBrandListResponse,
  VehicleBrandUpdateInput
} from '../model';




  export const getVehicleBrands = (axiosInstance: AxiosInstance = axios) => {
/**
 * Returns a paginated list of vehicle brands (marki).
 * @summary List vehicle brands
 */
const getVehicleBrands = (
    params?: GetVehicleBrandsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleBrandListResponse>> => {
    return axiosInstance.get(
      `/vehicle-brands`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Create a vehicle brand
 */
const createVehicleBrand = (
    vehicleBrandCreateInput: VehicleBrandCreateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleBrand>> => {
    return axiosInstance.post(
      `/vehicle-brands`,
      vehicleBrandCreateInput,options
    );
  }
/**
 * @summary Get vehicle brand by ID
 */
const getVehicleBrandById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleBrand>> => {
    return axiosInstance.get(
      `/vehicle-brands/${id}`,options
    );
  }
/**
 * @summary Update a vehicle brand
 */
const updateVehicleBrand = (
    id: number,
    vehicleBrandUpdateInput: VehicleBrandUpdateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleBrand>> => {
    return axiosInstance.put(
      `/vehicle-brands/${id}`,
      vehicleBrandUpdateInput,options
    );
  }
/**
 * @summary Delete a vehicle brand
 */
const deleteVehicleBrand = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/vehicle-brands/${id}`,options
    );
  }
return {getVehicleBrands,createVehicleBrand,getVehicleBrandById,updateVehicleBrand,deleteVehicleBrand}};
export type GetVehicleBrandsResult = AxiosResponse<VehicleBrandListResponse>
export type CreateVehicleBrandResult = AxiosResponse<VehicleBrand>
export type GetVehicleBrandByIdResult = AxiosResponse<VehicleBrand>
export type UpdateVehicleBrandResult = AxiosResponse<VehicleBrand>
export type DeleteVehicleBrandResult = AxiosResponse<void>
