/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetVehiclesParams,
  Vehicle,
  VehicleCreateInput,
  VehicleDetail,
  VehicleDocument,
  VehicleDocumentCreateInput,
  VehicleDocumentListResponse,
  VehicleHistoryEvent,
  VehicleHistoryEventCreateInput,
  VehicleHistoryListResponse,
  VehicleListResponse,
  VehicleUpdateInput
} from '../model';




  export const getVehicles = (axiosInstance: AxiosInstance = axios) => {
/**
 * Returns a paginated list of all vehicles.
 * @summary List vehicles
 */
const getVehicles = (
    params?: GetVehiclesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleListResponse>> => {
    return axiosInstance.get(
      `/vehicles`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Creates a new vehicle record.
 * @summary Create a vehicle
 */
const createVehicle = (
    vehicleCreateInput: VehicleCreateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Vehicle>> => {
    return axiosInstance.post(
      `/vehicles`,
      vehicleCreateInput,options
    );
  }
/**
 * Returns a single vehicle by its numeric ID.
 * @summary Get vehicle by ID
 */
const getVehicleById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleDetail>> => {
    return axiosInstance.get(
      `/vehicles/${id}`,options
    );
  }
/**
 * Replaces vehicle data. All fields are optional – only provided fields are updated.
 * @summary Update a vehicle
 */
const updateVehicle = (
    id: number,
    vehicleUpdateInput: VehicleUpdateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Vehicle>> => {
    return axiosInstance.put(
      `/vehicles/${id}`,
      vehicleUpdateInput,options
    );
  }
/**
 * Permanently deletes a vehicle by its ID.
 * @summary Delete a vehicle
 */
const deleteVehicle = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/vehicles/${id}`,options
    );
  }
/**
 * Returns documents (dokumenty) attached to a vehicle.
 * @summary List vehicle documents
 */
const getVehicleDocuments = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleDocumentListResponse>> => {
    return axiosInstance.get(
      `/vehicles/${id}/documents`,options
    );
  }
/**
 * @summary Add a vehicle document
 */
const createVehicleDocument = (
    id: number,
    vehicleDocumentCreateInput: VehicleDocumentCreateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleDocument>> => {
    return axiosInstance.post(
      `/vehicles/${id}/documents`,
      vehicleDocumentCreateInput,options
    );
  }
/**
 * @summary Delete a vehicle document
 */
const deleteVehicleDocument = (
    id: number,
    docId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/vehicles/${id}/documents/${docId}`,options
    );
  }
/**
 * Returns the short history (krótka historia) of a vehicle.
 * @summary List vehicle history events
 */
const getVehicleHistory = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleHistoryListResponse>> => {
    return axiosInstance.get(
      `/vehicles/${id}/history`,options
    );
  }
/**
 * @summary Add a vehicle history event
 */
const createVehicleHistoryEvent = (
    id: number,
    vehicleHistoryEventCreateInput: VehicleHistoryEventCreateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleHistoryEvent>> => {
    return axiosInstance.post(
      `/vehicles/${id}/history`,
      vehicleHistoryEventCreateInput,options
    );
  }
return {getVehicles,createVehicle,getVehicleById,updateVehicle,deleteVehicle,getVehicleDocuments,createVehicleDocument,deleteVehicleDocument,getVehicleHistory,createVehicleHistoryEvent}};
export type GetVehiclesResult = AxiosResponse<VehicleListResponse>
export type CreateVehicleResult = AxiosResponse<Vehicle>
export type GetVehicleByIdResult = AxiosResponse<VehicleDetail>
export type UpdateVehicleResult = AxiosResponse<Vehicle>
export type DeleteVehicleResult = AxiosResponse<void>
export type GetVehicleDocumentsResult = AxiosResponse<VehicleDocumentListResponse>
export type CreateVehicleDocumentResult = AxiosResponse<VehicleDocument>
export type DeleteVehicleDocumentResult = AxiosResponse<void>
export type GetVehicleHistoryResult = AxiosResponse<VehicleHistoryListResponse>
export type CreateVehicleHistoryEventResult = AxiosResponse<VehicleHistoryEvent>
