import { buildFilename, formatDate, PdfDocument } from '@deliveroo/pdf-core';
import { Document } from '../../model/documents';

const LOGO_PATH = '/deliveroo-pdf-logo.png';
const FOOTER_LINES = [
  'Generated by Deliveroo TMS',
  `Generated on: ${formatDate(new Date())}`,
];

interface PDFOptions {
  includeWatermark?: boolean;
  includeFooter?: boolean;
}

function getDocumentTypeLabel(type: Document['type']): string {
  const labels: Record<Document['type'], string> = {
    contract: 'Contract',
    invoice: 'Invoice',
    registration: 'Vehicle Registration',
    insurance: 'Insurance Policy',
    inspection: 'Technical Inspection Certificate',
    'tir-carnet': 'TIR Carnet',
    adr: 'ADR Certificate',
    'hazmat-permit': 'Hazmat Transport Permit',
    license: 'License',
    certificate: 'Certificate',
    other: 'Document',
  };
  return labels[type];
}

function getEntityTypeLabel(type: Document['entityType']): string {
  const labels: Record<Document['entityType'], string> = {
    vehicle: 'Vehicle',
    customer: 'Customer',
    supplier: 'Supplier',
    driver: 'Driver',
    company: 'Company',
    other: 'Other',
  };
  return labels[type];
}

async function buildDocumentPdf(document: Document, options: PDFOptions): Promise<PdfDocument> {
  const pdf = new PdfDocument({ bottomMargin: 40 });

  await pdf.addHeader({
    title: getDocumentTypeLabel(document.type),
    logoPath: LOGO_PATH,
    rightAlignedCompanyInfo: true,
    companyLines: ['Transport Management System', 'Deliveroo TMS Sp. z o.o.'],
  });

  if (options.includeWatermark) {
    pdf.addWatermark('SAMPLE DOCUMENT');
  }

  if (options.includeFooter !== false) {
    pdf.setFooter({ lines: FOOTER_LINES });
  }

  pdf
    .addSection('Document Information')
    .addField('Document Name', document.name)
    .addField('Document Type', getDocumentTypeLabel(document.type))
    .addField('Document ID', document.id);

  if (document.number) pdf.addField('Document Number', document.number);

  pdf
    .addSection('Related Entity')
    .addField('Related To', getEntityTypeLabel(document.entityType))
    .addField('Entity Name', document.entityName)
    .addField('Entity ID', document.entityId)
    .addSection('Important Dates')
    .addField('Issue Date', formatDate(document.issueDate))
    .addField('Created', formatDate(document.createdAt))
    .addField('Last Updated', formatDate(document.updatedAt));

  if (document.expiryDate) pdf.addField('Expiry Date', formatDate(document.expiryDate));

  if (document.issuingAuthority) {
    pdf.addSection('Issuing Authority').addField('Authority', document.issuingAuthority);
  }

  if (document.notes) {
    pdf.addSection('Notes').addText(document.notes);
  }

  pdf
    .addSection('Document Content')
    .addText('This is a sample document generated by the Deliveroo TMS system.')
    .addText('This document contains all the relevant information as stored in the system.');

  return pdf;
}

export async function generateDocumentPDF(document: Document, options: PDFOptions = {}): Promise<void> {
  const pdf = await buildDocumentPdf(document, options);
  pdf.save(buildFilename(document.name, document.id));
}

export async function generateDocumentPDFBlob(document: Document, options: PDFOptions = {}): Promise<Blob> {
  const pdf = await buildDocumentPdf(document, options);
  return pdf.toBlob();
}
