
-- SQL generated by wms-data-generator
-- DO NOT EDIT THIS FILE MANUALLY
-- Edit the create-wms-schema.sql file instead
--
-- 🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚
-- 🚚 DELIVEROO (C) 2025 🚚
-- 🚚   SHIP THAT SHIT   🚚
-- 🚚   Spółka Akcyjna   🚚
-- 🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚
--
-- Zatrudniamy! https://shorturl.at/G98Ej


-- Clean up previous tables
DROP TABLE IF EXISTS cargo_event_history CASCADE;
DROP TABLE IF EXISTS cargo_event_type CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS storage_record CASCADE;
DROP TABLE IF EXISTS storage_reservation CASCADE;
DROP TABLE IF EXISTS storage_request CASCADE;
DROP TABLE IF EXISTS employee_warehouse CASCADE;
DROP TABLE IF EXISTS party_role CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS party_relationship CASCADE;
DROP TABLE IF EXISTS party_contact CASCADE;
DROP TABLE IF EXISTS party CASCADE;
DROP TABLE IF EXISTS capacity CASCADE;
DROP TABLE IF EXISTS shelf CASCADE;
DROP TABLE IF EXISTS rack CASCADE;
DROP TABLE IF EXISTS aisle CASCADE;
DROP TABLE IF EXISTS zone CASCADE;
DROP TABLE IF EXISTS warehouse CASCADE;
DROP TABLE IF EXISTS location CASCADE;

-- 1. LOCATIONS
CREATE TABLE location (
    location_id SERIAL PRIMARY KEY,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    country TEXT NOT NULL
);

-- 2. WAREHOUSES
CREATE TABLE warehouse (
    warehouse_id SERIAL PRIMARY KEY,
    location_id INTEGER NOT NULL REFERENCES location(location_id),
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED','MAINTENANCE','INACTIVE'))
);
-- Basic FK index only
CREATE INDEX idx_warehouse_location_id ON warehouse(location_id);

-- 3. ZONES
CREATE TABLE zone (
    zone_id SERIAL PRIMARY KEY,
    warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id),
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED','MAINTENANCE','INACTIVE'))
);
CREATE INDEX idx_zone_warehouse_id ON zone(warehouse_id);

-- 4. AISLES
CREATE TABLE aisle (
    aisle_id SERIAL PRIMARY KEY,
    zone_id INTEGER NOT NULL REFERENCES zone(zone_id),
    label TEXT NOT NULL,
    width INTEGER NOT NULL,
    width_unit TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED','MAINTENANCE','INACTIVE'))
);
CREATE INDEX idx_aisle_zone_id ON aisle(zone_id);

-- 5. RACKS
CREATE TABLE rack (
    rack_id SERIAL PRIMARY KEY,
    aisle_id INTEGER NOT NULL REFERENCES aisle(aisle_id),
    label TEXT NOT NULL,
    max_height INTEGER NOT NULL,
    height_unit TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED','MAINTENANCE','INACTIVE'))
);
CREATE INDEX idx_rack_aisle_id ON rack(aisle_id);

-- 6. SHELVES
CREATE TABLE shelf (
    shelf_id SERIAL PRIMARY KEY,
    rack_id INTEGER NOT NULL REFERENCES rack(rack_id),
    level TEXT NOT NULL,
    max_weight NUMERIC NOT NULL,
    max_volume NUMERIC NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED','MAINTENANCE','INACTIVE'))
);
CREATE INDEX idx_shelf_rack_id ON shelf(rack_id);

-- 7. CAPACITY
CREATE TABLE capacity (
    capacity_id SERIAL PRIMARY KEY,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('WAREHOUSE','ZONE','RACK','SHELF')),
    entity_id INTEGER NOT NULL,
    value NUMERIC NOT NULL,
    unit TEXT NOT NULL,
    description TEXT
);
-- Composite index exists, but likely insufficient for complex aggregations without covering columns
CREATE INDEX idx_capacity_entity ON capacity(entity_type, entity_id);

-- 8. PARTY
CREATE TABLE party (
    party_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    contact_email TEXT, -- Important: No index here implies full scan on search
    contact_phone TEXT,
    data JSONB, -- Important: No GIN index here
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 9. PARTY CONTACTS
CREATE TABLE party_contact (
    contact_id SERIAL PRIMARY KEY,
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    details TEXT NOT NULL
);
CREATE INDEX idx_party_contact_party_id ON party_contact(party_id);

-- 10. PARTY RELATIONSHIP
CREATE TABLE party_relationship (
    relationship_id SERIAL PRIMARY KEY,
    party_id_primary INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    party_id_secondary INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    relationship_type TEXT NOT NULL,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    notes TEXT
);
CREATE INDEX idx_party_relationship_primary ON party_relationship(party_id_primary);
CREATE INDEX idx_party_relationship_secondary ON party_relationship(party_id_secondary);

-- 11. ADDRESS
CREATE TABLE address (
    address_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    street_address TEXT NOT NULL,
    city TEXT NOT NULL,
    country TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    address_type TEXT NOT NULL CHECK (address_type IN ('BILLING','SHIPPING','CORPORATE','PERSONAL','OTHER'))
);
CREATE INDEX idx_address_party_id ON address(party_id);

-- 12. ROLES
CREATE TABLE role (
    role_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL CHECK (name IN ('DIRECTOR','WAREHOUSE_MANAGER','LOGISTICS_COORDINATOR','STORAGE_APPROVER','OPERATOR')),
    description TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_role_name ON role(name);

-- 13. PARTY ROLES
CREATE TABLE party_role (
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES role(role_id) ON DELETE CASCADE,
    assigned_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (party_id, role_id)
);
CREATE INDEX idx_party_role_party_id ON party_role(party_id);
CREATE INDEX idx_party_role_role_id ON party_role(role_id);

-- 14. EMPLOYEE-WAREHOUSE
CREATE TABLE employee_warehouse (
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id) ON DELETE CASCADE,
    assigned_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_until TIMESTAMP,
    PRIMARY KEY (party_id, warehouse_id, assigned_from)
);
CREATE INDEX idx_employee_warehouse_party_id ON employee_warehouse(party_id);
CREATE INDEX idx_employee_warehouse_warehouse ON employee_warehouse(warehouse_id);

-- 15. STORAGE REQUESTS
CREATE TABLE storage_request (
    request_id SERIAL PRIMARY KEY,
    issuing_party_id INTEGER NOT NULL REFERENCES party(party_id),
    warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id),
    requested_entry_date TIMESTAMP NOT NULL,
    requested_exit_date TIMESTAMP NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING','ACCEPTED','REJECTED')) DEFAULT 'PENDING',
    decisive_party_id INTEGER REFERENCES party(party_id),
    decision_date TIMESTAMP
);
CREATE INDEX idx_storage_request_issuing_party_id ON storage_request(issuing_party_id);
CREATE INDEX idx_storage_request_warehouse_id ON storage_request(warehouse_id);
CREATE INDEX idx_storage_request_decisive_party_id ON storage_request(decisive_party_id);

-- 16. STORAGE RESERVATIONS
CREATE TABLE storage_reservation (
    reservation_id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES storage_request(request_id) ON DELETE CASCADE,
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    shelf_id INTEGER NOT NULL REFERENCES shelf(shelf_id),
    reserved_weight NUMERIC NOT NULL,
    reserved_volume NUMERIC NOT NULL,
    reserved_from TIMESTAMP NOT NULL,
    reserved_until TIMESTAMP NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING','ACTIVE','EXPIRED','CANCELLED','FULFILLED')) DEFAULT 'PENDING'
);
CREATE INDEX idx_storage_reservation_request_id ON storage_reservation(request_id);
CREATE INDEX idx_storage_reservation_party_id ON storage_reservation(party_id);
CREATE INDEX idx_storage_reservation_shelf_id ON storage_reservation(shelf_id);

-- 17. STORAGE RECORDS
CREATE TABLE storage_record (
    storage_record_id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES storage_request(request_id),
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    shelf_id INTEGER NOT NULL REFERENCES shelf(shelf_id),
    actual_entry_date TIMESTAMP NOT NULL,
    actual_exit_date TIMESTAMP,
    cargo_description TEXT NOT NULL,
    cargo_weight NUMERIC NOT NULL,
    cargo_volume NUMERIC NOT NULL,
    condition TEXT NOT NULL DEFAULT 'GOOD' CHECK (condition IN ('GOOD','DAMAGED','LOST'))
);
CREATE INDEX idx_storage_record_request_id ON storage_record(request_id);
CREATE INDEX idx_storage_record_party_id ON storage_record(party_id);
CREATE INDEX idx_storage_record_shelf_id ON storage_record(shelf_id);

-- 18. PAYMENTS
CREATE TABLE payment (
    payment_id SERIAL PRIMARY KEY,
    storage_record_id INTEGER NOT NULL REFERENCES storage_record(storage_record_id) ON DELETE CASCADE,
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    amount NUMERIC NOT NULL,
    currency TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING','PAID','FAILED','CANCELLED')) DEFAULT 'PENDING',
    payment_date TIMESTAMP,
    external_reference TEXT
);
CREATE INDEX idx_payment_party_id ON payment(party_id);
CREATE INDEX idx_payment_storage_record_id ON payment(storage_record_id);

-- 19. CARGO EVENT TYPES
CREATE TABLE cargo_event_type (
    event_type_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT
);
CREATE UNIQUE INDEX idx_cargo_event_type_name ON cargo_event_type(name);

-- 20. CARGO EVENT HISTORY
CREATE TABLE cargo_event_history (
    event_id SERIAL PRIMARY KEY,
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    storage_record_id INTEGER NOT NULL REFERENCES storage_record(storage_record_id) ON DELETE CASCADE,
    event_type_id INTEGER NOT NULL REFERENCES cargo_event_type(event_type_id),
    event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details JSONB
);
CREATE INDEX idx_cargo_event_history_party_id ON cargo_event_history(party_id);
CREATE INDEX idx_cargo_event_history_storage_record_id ON cargo_event_history(storage_record_id);
CREATE INDEX idx_cargo_event_history_event_type_id ON cargo_event_history(event_type_id);

-- Locations
INSERT INTO location (location_id, address, city, postal_code, country) VALUES
(1, 'ul. Wichrowa 89', 'Janki', '05-090', 'Poland');

-- Warehouses
INSERT INTO warehouse (warehouse_id, location_id, name, description) VALUES
(1, 1, 'Main Deliveroo Warehouse', 'Main warehouse for Deliveroo in Poland');

-- Roles
INSERT INTO role (role_id, name, description) VALUES
(1, 'DIRECTOR', 'Executive director overseeing all warehouse operations and strategic planning.'),
(2, 'WAREHOUSE_MANAGER', 'Oversees all warehouse operations, staff management, and safety protocols.'),
(3, 'LOGISTICS_COORDINATOR', 'Manages logistics, distribution processes, and supply chain coordination.'),
(4, 'STORAGE_APPROVER', 'Reviews and approves storage requests and reservation decisions.'),
(5, 'OPERATOR', 'Handles day-to-day warehouse operations including receiving, shipping, and inventory management.');

-- Contractor and Employee Parties
INSERT INTO party (party_id, name, data, created_at, updated_at) VALUES
(1, 'Klein, Cole and Cherry', '{"type": "contractor_company", "tax_id_number": "8545266571", "status": "ACTIVE"}'::jsonb, '2025-05-16 12:17:05.251334', '2025-07-26 05:23:31.827338'),
(2, 'Morris, Brown and Tate', '{"type": "contractor_company", "tax_id_number": "2171344477", "status": "ACTIVE"}'::jsonb, '2026-05-23 04:36:36.418810', '2026-04-20 17:21:26.820581'),
(3, 'Gibbs, Walton and Hoover', '{"type": "contractor_company", "tax_id_number": "5552459113", "status": "ACTIVE"}'::jsonb, '2024-12-05 14:41:10.666073', '2025-11-18 05:39:59.991130'),
(4, 'Davis-Williams', '{"type": "contractor_company", "tax_id_number": "2200237316", "status": "ACTIVE"}'::jsonb, '2024-09-29 12:04:37.634147', '2026-04-16 10:24:20.189383'),
(5, 'Bradley-Hogan', '{"type": "contractor_company", "tax_id_number": "8023196877", "status": "ACTIVE"}'::jsonb, '2024-12-20 10:27:47.230444', '2025-10-29 01:34:18.721942'),
(6, 'Parsons PLC', '{"type": "contractor_company", "tax_id_number": "7959926030", "status": "ACTIVE"}'::jsonb, '2026-05-31 21:13:31.418878', '2025-09-30 13:13:31.604559'),
(7, 'Bowen, Robinson and Park', '{"type": "contractor_company", "tax_id_number": "7759851842", "status": "ACTIVE"}'::jsonb, '2026-03-14 17:49:08.037510', '2025-10-19 05:02:53.772108'),
(8, 'Fritz Group', '{"type": "contractor_company", "tax_id_number": "9084649496", "status": "ACTIVE"}'::jsonb, '2025-09-12 20:55:07.338882', '2026-02-03 10:24:37.119617'),
(9, 'Mccall-Preston', '{"type": "contractor_company", "tax_id_number": "7762704027", "status": "ACTIVE"}'::jsonb, '2025-05-10 11:36:35.856981', '2026-04-15 06:56:40.304226'),
(10, 'Woodward PLC', '{"type": "contractor_company", "tax_id_number": "2397839548", "status": "ACTIVE"}'::jsonb, '2024-08-10 03:50:37.883946', '2025-09-16 05:15:22.862708'),
(11, 'Stone-Brown', '{"type": "contractor_company", "tax_id_number": "6325110652", "status": "ACTIVE"}'::jsonb, '2025-01-25 18:53:04.513260', '2025-08-21 01:22:48.853942'),
(12, 'Gibson Ltd', '{"type": "contractor_company", "tax_id_number": "2980458171", "status": "ACTIVE"}'::jsonb, '2025-02-24 11:25:07.199424', '2025-11-08 09:58:07.275253'),
(13, 'Cardenas-Smith', '{"type": "contractor_company", "tax_id_number": "8364131182", "status": "ACTIVE"}'::jsonb, '2024-10-29 02:35:56.067930', '2025-10-06 14:16:27.996434'),
(14, 'Barajas PLC', '{"type": "contractor_company", "tax_id_number": "2110257126", "status": "ACTIVE"}'::jsonb, '2025-09-14 04:17:28.099332', '2026-02-25 03:52:13.521560'),
(15, 'Oliver-Garza', '{"type": "contractor_company", "tax_id_number": "1044210182", "status": "ACTIVE"}'::jsonb, '2024-08-16 00:24:35.311589', '2025-10-22 00:03:24.029190'),
(16, 'Lawson Inc', '{"type": "contractor_company", "tax_id_number": "2011126211", "status": "ACTIVE"}'::jsonb, '2025-10-24 15:33:29.867630', '2026-06-18 21:30:14.715425'),
(17, 'Taylor, Simmons and Coffey', '{"type": "contractor_company", "tax_id_number": "3591167818", "status": "ACTIVE"}'::jsonb, '2024-08-17 22:34:48.416477', '2026-06-03 09:43:55.082152'),
(18, 'Wright, Deleon and Dorsey', '{"type": "contractor_company", "tax_id_number": "8007843726", "status": "INACTIVE"}'::jsonb, '2025-11-26 05:06:35.980744', '2026-03-23 21:19:43.536623'),
(19, 'Brown-Cabrera', '{"type": "contractor_company", "tax_id_number": "4685032115", "status": "ACTIVE"}'::jsonb, '2026-01-04 08:46:11.959106', '2025-09-27 22:48:33.043229'),
(20, 'Kennedy LLC', '{"type": "contractor_company", "tax_id_number": "0723148891", "status": "ACTIVE"}'::jsonb, '2024-09-03 18:50:14.011902', '2025-07-14 21:11:44.822601'),
(21, 'Lewis-Archer', '{"type": "contractor_company", "tax_id_number": "1672255778", "status": "ACTIVE"}'::jsonb, '2026-01-19 16:07:46.759386', '2026-03-30 09:29:35.899447'),
(22, 'Burke and Sons', '{"type": "contractor_company", "tax_id_number": "7029797962", "status": "ACTIVE"}'::jsonb, '2024-09-12 15:19:16.231344', '2026-06-06 06:12:32.273729'),
(23, 'Walters, Christian and Fleming', '{"type": "contractor_company", "tax_id_number": "1847903415", "status": "ACTIVE"}'::jsonb, '2025-04-10 00:56:15.562262', '2025-11-11 16:52:45.141156'),
(24, 'Harrison and Sons', '{"type": "contractor_company", "tax_id_number": "3294700521", "status": "ACTIVE"}'::jsonb, '2026-02-03 05:01:26.086423', '2026-04-18 06:12:31.254074'),
(25, 'Hernandez, Willis and Munoz', '{"type": "contractor_company", "tax_id_number": "4740799038", "status": "ACTIVE"}'::jsonb, '2025-03-13 05:01:17.638489', '2026-01-14 09:15:28.076400'),
(26, 'Gonzalez Ltd', '{"type": "contractor_company", "tax_id_number": "3371355907", "status": "ACTIVE"}'::jsonb, '2025-12-10 15:13:34.151058', '2026-04-24 16:20:44.158775'),
(27, 'Rogers-Davis', '{"type": "contractor_company", "tax_id_number": "5914108098", "status": "ACTIVE"}'::jsonb, '2026-01-14 23:21:27.380284', '2025-08-30 16:22:06.856434'),
(28, 'Jones-Thomas', '{"type": "contractor_company", "tax_id_number": "0510233726", "status": "INACTIVE"}'::jsonb, '2025-01-06 01:03:12.528693', '2025-12-08 16:29:34.450893'),
(29, 'Harrell, Moreno and Salas', '{"type": "contractor_company", "tax_id_number": "7276277503", "status": "ACTIVE"}'::jsonb, '2025-03-02 21:03:32.988452', '2026-01-17 15:43:24.606089'),
(30, 'Pittman-Houston', '{"type": "contractor_company", "tax_id_number": "5852037062", "status": "ACTIVE"}'::jsonb, '2024-11-22 04:00:02.552436', '2026-05-15 23:37:25.383221'),
(31, 'Welch, Gay and Farmer', '{"type": "contractor_company", "tax_id_number": "0592661079", "status": "ACTIVE"}'::jsonb, '2025-05-20 22:45:09.468798', '2026-06-28 22:26:52.764011'),
(32, 'Brown Group', '{"type": "contractor_company", "tax_id_number": "5175731278", "status": "ACTIVE"}'::jsonb, '2025-04-08 15:12:01.796159', '2025-10-03 15:34:43.087942'),
(33, 'Jones Ltd', '{"type": "contractor_company", "tax_id_number": "8184362097", "status": "ACTIVE"}'::jsonb, '2025-05-30 11:44:35.399979', '2025-12-20 13:30:35.622953'),
(34, 'Taylor, Dorsey and Williamson', '{"type": "contractor_company", "tax_id_number": "2908796276", "status": "INACTIVE"}'::jsonb, '2025-07-05 08:59:13.893818', '2026-05-31 11:31:20.785619'),
(35, 'Johnson LLC', '{"type": "contractor_company", "tax_id_number": "4027558567", "status": "ACTIVE"}'::jsonb, '2024-08-30 00:23:31.053598', '2025-12-18 04:26:52.283854'),
(36, 'Smith, Taylor and Lindsey', '{"type": "contractor_company", "tax_id_number": "1393041517", "status": "ACTIVE"}'::jsonb, '2025-07-26 18:37:06.744715', '2026-03-27 08:31:44.254215'),
(37, 'Baker, Schultz and Garcia', '{"type": "contractor_company", "tax_id_number": "7183401418", "status": "ACTIVE"}'::jsonb, '2026-04-24 11:00:43.340780', '2025-11-04 02:34:08.500016'),
(38, 'Collins-Hunter', '{"type": "contractor_company", "tax_id_number": null, "status": "ACTIVE"}'::jsonb, '2026-01-31 03:10:37.549719', '2026-01-04 07:36:53.853622'),
(39, 'Irwin Group', '{"type": "contractor_company", "tax_id_number": "7186628736", "status": "ACTIVE"}'::jsonb, '2025-10-24 09:54:46.539520', '2026-03-10 20:13:00.277223'),
(40, 'Lewis LLC', '{"type": "contractor_company", "tax_id_number": "0189653632", "status": "ACTIVE"}'::jsonb, '2025-02-15 16:04:34.789256', '2025-09-26 09:40:58.427554'),
(41, 'Torres, Norman and Miller', '{"type": "contractor_company", "tax_id_number": "3486265605", "status": "ACTIVE"}'::jsonb, '2024-09-18 19:26:36.501622', '2026-04-04 08:02:36.028997'),
(42, 'Moore-Callahan', '{"type": "contractor_company", "tax_id_number": "3436844668", "status": "ACTIVE"}'::jsonb, '2025-06-04 22:30:05.454216', '2025-11-27 04:42:40.150885'),
(43, 'Petersen-Collins', '{"type": "contractor_company", "tax_id_number": "2916729153", "status": "ACTIVE"}'::jsonb, '2025-03-17 07:32:54.306856', '2026-05-27 16:49:07.091649'),
(44, 'Vasquez, Mcclure and Campbell', '{"type": "contractor_company", "tax_id_number": "5063654888", "status": "ACTIVE"}'::jsonb, '2025-03-19 03:26:09.485123', '2025-07-19 10:57:54.945612'),
(45, 'Trevino, Thomas and Chavez', '{"type": "contractor_company", "tax_id_number": "7467700319", "status": "ACTIVE"}'::jsonb, '2026-06-19 17:26:21.723615', '2026-06-28 19:37:08.853319'),
(46, 'Silva PLC', '{"type": "contractor_company", "tax_id_number": null, "status": "INACTIVE"}'::jsonb, '2026-04-07 09:26:25.552901', '2026-06-14 05:48:45.210135'),
(47, 'Fritz LLC', '{"type": "contractor_company", "tax_id_number": "0545545940", "status": "ACTIVE"}'::jsonb, '2024-10-14 15:06:25.676563', '2026-06-06 22:07:52.075053'),
(48, 'Morgan-Russo', '{"type": "contractor_company", "tax_id_number": "7742286457", "status": "ACTIVE"}'::jsonb, '2026-04-02 15:10:59.362308', '2025-07-20 12:49:18.720209'),
(49, 'Lambert-Pitts', '{"type": "contractor_company", "tax_id_number": "0659973490", "status": "ACTIVE"}'::jsonb, '2025-01-07 10:24:13.078695', '2025-09-14 08:21:27.484370'),
(50, 'Fuentes Ltd', '{"type": "contractor_company", "tax_id_number": "0988998671", "status": "ACTIVE"}'::jsonb, '2025-11-20 23:56:49.337012', '2026-06-11 20:02:19.547567'),
(71, 'Jasmin Wagner', '{"type": "contractor_employee", "job_title": "Social researcher"}'::jsonb, '2026-04-15 23:42:02.699074', '2026-07-02 20:13:21.498401'),
(72, 'Erik Austin', '{"type": "contractor_employee", "job_title": "Cartographer"}'::jsonb, '2026-01-21 01:34:51.341180', '2026-07-02 20:18:28.480545'),
(73, 'Christopher Moore', '{"type": "contractor_employee", "job_title": "Research officer, trade union"}'::jsonb, '2026-06-16 01:40:12.995075', '2026-07-02 20:13:30.225725'),
(74, 'Casey Jones', '{"type": "contractor_employee", "job_title": "Operational researcher"}'::jsonb, '2026-06-23 16:08:33.780237', '2026-07-02 20:19:19.666379'),
(75, 'Mary Reid', '{"type": "contractor_employee", "job_title": "Administrator, local government"}'::jsonb, '2025-10-13 20:41:00.496192', '2026-07-02 20:17:19.823991'),
(76, 'Andrea Grant', '{"type": "contractor_employee", "job_title": "Teacher, English as a foreign language"}'::jsonb, '2025-07-11 02:53:05.057056', '2026-07-02 20:16:59.541995'),
(77, 'Scott Brown', '{"type": "contractor_employee", "job_title": "Surveyor, mining"}'::jsonb, '2025-07-12 09:26:12.719955', '2026-07-02 20:14:11.367633'),
(78, 'Tina Levine', '{"type": "contractor_employee", "job_title": "Counselling psychologist"}'::jsonb, '2026-05-27 14:25:01.067418', '2026-07-02 20:16:32.919598'),
(79, 'Jessica Torres', '{"type": "contractor_employee", "job_title": "Designer, multimedia"}'::jsonb, '2025-09-29 18:06:27.539378', '2026-07-02 20:14:10.851028'),
(80, 'Bruce Yu', '{"type": "contractor_employee", "job_title": "Chartered certified accountant"}'::jsonb, '2025-07-24 14:19:19.855429', '2026-07-02 20:17:51.534209'),
(81, 'Mrs. Kara Butler MD', '{"type": "contractor_employee", "job_title": "Programmer, multimedia"}'::jsonb, '2026-04-07 04:44:35.162176', '2026-07-02 20:13:35.099560'),
(82, 'Cindy Moore', '{"type": "contractor_employee", "job_title": "Banker"}'::jsonb, '2025-11-30 05:07:00.105132', '2026-07-02 20:14:32.431871'),
(83, 'Briana Morse', '{"type": "contractor_employee", "job_title": "Sub"}'::jsonb, '2026-01-29 21:56:19.625910', '2026-07-02 20:16:25.900422'),
(84, 'Andrew Snyder', '{"type": "contractor_employee", "job_title": "Leisure centre manager"}'::jsonb, '2026-06-16 00:15:17.552210', '2026-07-02 20:14:19.695038'),
(85, 'Michael Johnson', '{"type": "contractor_employee", "job_title": "Scientist, research (medical)"}'::jsonb, '2025-12-15 12:11:38.175936', '2026-07-02 20:19:18.356020'),
(86, 'David Goodman', '{"type": "contractor_employee", "job_title": "Translator"}'::jsonb, '2025-12-16 12:58:37.778947', '2026-07-02 20:17:32.790289'),
(87, 'Christopher Brown', '{"type": "contractor_employee", "job_title": "Travel agency manager"}'::jsonb, '2026-05-26 16:31:07.811177', '2026-07-02 20:16:07.466018'),
(88, 'Brandon Goodwin', '{"type": "contractor_employee", "job_title": "Retail merchandiser"}'::jsonb, '2026-04-16 13:24:45.279939', '2026-07-02 20:13:50.082643'),
(89, 'Valerie Johnson', '{"type": "contractor_employee", "job_title": "Acupuncturist"}'::jsonb, '2025-12-14 05:33:17.794221', '2026-07-02 20:16:10.462346'),
(90, 'Shelley Taylor', '{"type": "contractor_employee", "job_title": "Accountant, chartered"}'::jsonb, '2025-08-10 01:02:58.749444', '2026-07-02 20:16:33.752188'),
(91, 'Aaron Alexander', '{"type": "contractor_employee", "job_title": "Professor Emeritus"}'::jsonb, '2026-04-28 17:01:58.474663', '2026-07-02 20:14:15.385458'),
(92, 'Patrick Barry', '{"type": "contractor_employee", "job_title": "Learning disability nurse"}'::jsonb, '2026-04-19 09:26:21.098348', '2026-07-02 20:13:45.526017'),
(93, 'Cassandra Hansen', '{"type": "contractor_employee", "job_title": "Biomedical scientist"}'::jsonb, '2026-01-20 13:13:22.139396', '2026-07-02 20:16:32.394383'),
(94, 'Caitlin Powers', '{"type": "contractor_employee", "job_title": "Geographical information systems officer"}'::jsonb, '2026-02-28 14:46:59.319491', '2026-07-02 20:15:18.356385'),
(95, 'Scott Henry', '{"type": "contractor_employee", "job_title": "Event organiser"}'::jsonb, '2025-10-29 00:09:12.731737', '2026-07-02 20:19:19.325941'),
(96, 'Lindsay Gould', '{"type": "contractor_employee", "job_title": "Patent attorney"}'::jsonb, '2025-12-10 16:58:20.813623', '2026-07-02 20:13:36.792000'),
(97, 'Eduardo Moreno', '{"type": "contractor_employee", "job_title": "Insurance underwriter"}'::jsonb, '2025-08-22 05:52:43.926625', '2026-07-02 20:16:21.238354'),
(98, 'David Giles', '{"type": "contractor_employee", "job_title": "Secondary school teacher"}'::jsonb, '2025-11-19 00:02:17.934538', '2026-07-02 20:18:35.563135'),
(99, 'Steven Greer', '{"type": "contractor_employee", "job_title": "Actuary"}'::jsonb, '2025-09-14 04:31:29.081904', '2026-07-02 20:16:47.613410'),
(100, 'Matthew Novak PhD', '{"type": "contractor_employee", "job_title": "Archaeologist"}'::jsonb, '2026-03-31 04:38:10.371316', '2026-07-02 20:18:46.030701'),
(101, 'Charles Reese', '{"type": "contractor_employee", "job_title": "Museum/gallery conservator"}'::jsonb, '2025-07-31 13:14:51.844393', '2026-07-02 20:14:17.543374'),
(102, 'Amanda Jones', '{"type": "contractor_employee", "job_title": "Insurance underwriter"}'::jsonb, '2025-08-11 19:27:53.791085', '2026-07-02 20:14:15.849377'),
(103, 'Dr. Ashley Spencer PhD', '{"type": "contractor_employee", "job_title": "Community pharmacist"}'::jsonb, '2026-05-03 20:07:35.344405', '2026-07-02 20:14:00.108438'),
(104, 'Lindsey Gonzalez', '{"type": "contractor_employee", "job_title": "Financial adviser"}'::jsonb, '2025-07-28 11:23:05.016926', '2026-07-02 20:16:59.589500'),
(105, 'Vanessa Mann', '{"type": "contractor_employee", "job_title": "Landscape architect"}'::jsonb, '2026-02-16 17:12:19.695790', '2026-07-02 20:17:09.704619'),
(106, 'Kari Castro', '{"type": "contractor_employee", "job_title": "Chief Financial Officer"}'::jsonb, '2025-10-30 01:52:54.538515', '2026-07-02 20:17:07.946229'),
(107, 'Christopher Velasquez', '{"type": "contractor_employee", "job_title": "Production engineer"}'::jsonb, '2026-05-28 02:52:30.333148', '2026-07-02 20:18:33.512537'),
(108, 'Jennifer Dickerson', '{"type": "contractor_employee", "job_title": "Automotive engineer"}'::jsonb, '2026-06-06 01:36:35.447369', '2026-07-02 20:19:13.372144'),
(109, 'Sharon Randolph', '{"type": "contractor_employee", "job_title": "Armed forces technical officer"}'::jsonb, '2026-06-28 17:21:34.529644', '2026-07-02 20:16:32.111755'),
(110, 'Barbara Taylor', '{"type": "contractor_employee", "job_title": "Claims inspector/assessor"}'::jsonb, '2025-07-04 07:12:57.225001', '2026-07-02 20:16:35.581052'),
(111, 'Stacey Smith', '{"type": "contractor_employee", "job_title": "Teacher, secondary school"}'::jsonb, '2025-08-19 13:48:19.672477', '2026-07-02 20:19:10.908118'),
(112, 'Jeremy Patterson', '{"type": "contractor_employee", "job_title": "Transport planner"}'::jsonb, '2026-05-17 06:39:06.244199', '2026-07-02 20:18:58.940506'),
(113, 'Jamie Richardson', '{"type": "contractor_employee", "job_title": "Actuary"}'::jsonb, '2026-04-10 03:09:06.696568', '2026-07-02 20:17:13.382747'),
(114, 'Kimberly Stone', '{"type": "contractor_employee", "job_title": "Illustrator"}'::jsonb, '2026-02-12 13:04:47.730274', '2026-07-02 20:17:48.312692'),
(115, 'Tina Montgomery', '{"type": "contractor_employee", "job_title": "Multimedia programmer"}'::jsonb, '2025-12-09 00:43:29.631918', '2026-07-02 20:17:44.054650'),
(116, 'Robert Green', '{"type": "contractor_employee", "job_title": "Industrial buyer"}'::jsonb, '2025-09-14 01:44:39.579408', '2026-07-02 20:14:32.024607'),
(117, 'Keith Huff', '{"type": "contractor_employee", "job_title": "Charity fundraiser"}'::jsonb, '2026-05-03 20:15:12.010887', '2026-07-02 20:13:48.360666'),
(118, 'George Anderson', '{"type": "contractor_employee", "job_title": "Emergency planning/management officer"}'::jsonb, '2025-11-21 11:01:49.219098', '2026-07-02 20:15:43.102006'),
(119, 'Brianna Becker', '{"type": "contractor_employee", "job_title": "Museum/gallery curator"}'::jsonb, '2026-06-14 03:53:30.375153', '2026-07-02 20:18:09.388875'),
(120, 'Bobby Luna', '{"type": "contractor_employee", "job_title": "Veterinary surgeon"}'::jsonb, '2026-05-06 02:22:17.717969', '2026-07-02 20:18:23.231425'),
(121, 'Paul Rivera', '{"type": "contractor_employee", "job_title": "Engineering geologist"}'::jsonb, '2026-05-13 09:58:43.730833', '2026-07-02 20:14:26.906901'),
(122, 'Tiffany Bradley', '{"type": "contractor_employee", "job_title": "Higher education careers adviser"}'::jsonb, '2025-07-24 00:00:20.256574', '2026-07-02 20:17:27.092237'),
(123, 'Ryan Macdonald', '{"type": "contractor_employee", "job_title": "Systems developer"}'::jsonb, '2026-05-31 06:49:55.692306', '2026-07-02 20:16:31.730386'),
(124, 'Brian Jones', '{"type": "contractor_employee", "job_title": "Chief Strategy Officer"}'::jsonb, '2025-07-12 02:07:32.316322', '2026-07-02 20:19:18.455641'),
(125, 'Lisa Morris', '{"type": "contractor_employee", "job_title": "Chemist, analytical"}'::jsonb, '2026-06-16 10:47:41.895429', '2026-07-02 20:16:26.264238'),
(126, 'Richard Baker', '{"type": "contractor_employee", "job_title": "Operational researcher"}'::jsonb, '2026-04-01 14:54:19.715561', '2026-07-02 20:17:26.200040'),
(127, 'Douglas Page', '{"type": "contractor_employee", "job_title": "Therapist, sports"}'::jsonb, '2026-04-28 09:35:30.624967', '2026-07-02 20:16:08.871670'),
(128, 'Jacqueline Ramirez DVM', '{"type": "contractor_employee", "job_title": "Cytogeneticist"}'::jsonb, '2025-07-08 20:28:39.190589', '2026-07-02 20:13:49.586300'),
(129, 'Eric Sutton', '{"type": "contractor_employee", "job_title": "Theatre stage manager"}'::jsonb, '2026-04-03 12:09:41.476095', '2026-07-02 20:14:17.620337'),
(130, 'Debra Smith', '{"type": "contractor_employee", "job_title": "Geophysical data processor"}'::jsonb, '2026-04-28 10:28:29.538431', '2026-07-02 20:16:49.033707'),
(131, 'Theodore Parker', '{"type": "contractor_employee", "job_title": "Scientist, water quality"}'::jsonb, '2026-01-11 20:47:35.247264', '2026-07-02 20:16:33.371226'),
(132, 'Ashley Torres', '{"type": "contractor_employee", "job_title": "Fast food restaurant manager"}'::jsonb, '2026-03-15 20:35:06.913014', '2026-07-02 20:14:14.922077'),
(133, 'Jennifer Ramos', '{"type": "contractor_employee", "job_title": "Economist"}'::jsonb, '2025-08-16 02:13:51.593107', '2026-07-02 20:17:32.875182'),
(134, 'Abigail Reed', '{"type": "contractor_employee", "job_title": "Scientist, research (life sciences)"}'::jsonb, '2025-08-12 08:30:43.657337', '2026-07-02 20:14:15.448278'),
(135, 'Tamara Horn', '{"type": "contractor_employee", "job_title": "Chief of Staff"}'::jsonb, '2025-12-16 10:54:30.244229', '2026-07-02 20:16:52.788371'),
(136, 'Terry Chen', '{"type": "contractor_employee", "job_title": "Financial trader"}'::jsonb, '2026-07-02 18:28:28.958050', '2026-07-02 20:17:06.980406'),
(137, 'Preston Wolf', '{"type": "contractor_employee", "job_title": "Materials engineer"}'::jsonb, '2026-01-02 20:45:52.392082', '2026-07-02 20:17:48.541777'),
(138, 'Dawn Miller', '{"type": "contractor_employee", "job_title": "Retail banker"}'::jsonb, '2026-06-15 19:08:47.391190', '2026-07-02 20:17:21.405910'),
(139, 'Samuel Krueger', '{"type": "contractor_employee", "job_title": "Copywriter, advertising"}'::jsonb, '2026-06-19 09:02:14.496720', '2026-07-02 20:13:52.790280'),
(140, 'Jennifer Wilson', '{"type": "contractor_employee", "job_title": "Retail merchandiser"}'::jsonb, '2025-08-06 10:33:14.534177', '2026-07-02 20:18:18.942963'),
(141, 'Stacey Williams', '{"type": "contractor_employee", "job_title": "Museum/gallery exhibitions officer"}'::jsonb, '2025-12-22 05:40:29.305676', '2026-07-02 20:15:40.974994'),
(142, 'Gabriel Schmidt', '{"type": "contractor_employee", "job_title": "Soil scientist"}'::jsonb, '2026-01-22 13:26:16.929453', '2026-07-02 20:15:51.195937'),
(143, 'Cynthia Day', '{"type": "contractor_employee", "job_title": "Sales promotion account executive"}'::jsonb, '2026-05-27 10:47:01.340571', '2026-07-02 20:19:16.811892'),
(144, 'Douglas Watson', '{"type": "contractor_employee", "job_title": "Archaeologist"}'::jsonb, '2025-11-27 10:04:05.503650', '2026-07-02 20:16:41.099652'),
(145, 'Joseph Berger', '{"type": "contractor_employee", "job_title": "Clinical cytogeneticist"}'::jsonb, '2026-06-18 04:44:05.078866', '2026-07-02 20:16:00.192005'),
(146, 'Ashley Morales', '{"type": "contractor_employee", "job_title": "Tax inspector"}'::jsonb, '2026-04-08 10:51:40.841180', '2026-07-02 20:14:29.979995'),
(147, 'Sean Velasquez', '{"type": "contractor_employee", "job_title": "Health physicist"}'::jsonb, '2025-07-14 18:21:58.305908', '2026-07-02 20:13:36.603809'),
(148, 'Mark Hardin', '{"type": "contractor_employee", "job_title": "Engineer, biomedical"}'::jsonb, '2025-09-01 21:42:37.787398', '2026-07-02 20:17:41.940068');

-- Party Relationships
INSERT INTO party_relationship (party_id_primary, party_id_secondary, relationship_type, valid_from) VALUES
(1, 71, 'REPRESENTATIVE', '2025-07-05 09:33:50.770557'),
(1, 72, 'REPRESENTATIVE', '2025-12-19 09:05:20.025660'),
(1, 73, 'REPRESENTATIVE', '2025-07-12 03:37:03.159189'),
(2, 74, 'REPRESENTATIVE', '2025-10-16 16:32:49.462519'),
(2, 75, 'REPRESENTATIVE', '2025-10-26 10:42:43.662290'),
(3, 76, 'REPRESENTATIVE', '2025-11-25 04:25:56.362482'),
(4, 77, 'REPRESENTATIVE', '2026-03-09 14:53:03.445063'),
(4, 78, 'REPRESENTATIVE', '2026-04-02 04:37:46.425830'),
(6, 79, 'REPRESENTATIVE', '2025-09-09 02:42:45.369948'),
(6, 80, 'REPRESENTATIVE', '2025-12-28 16:24:39.886591'),
(6, 81, 'REPRESENTATIVE', '2026-02-12 21:43:34.042098'),
(9, 82, 'REPRESENTATIVE', '2026-01-23 15:30:26.814725'),
(10, 83, 'REPRESENTATIVE', '2026-05-22 04:50:38.939265'),
(10, 84, 'REPRESENTATIVE', '2025-10-25 11:35:14.145495'),
(10, 85, 'REPRESENTATIVE', '2025-08-21 20:50:06.593799'),
(12, 86, 'REPRESENTATIVE', '2025-11-08 21:04:54.377856'),
(12, 87, 'REPRESENTATIVE', '2025-11-20 06:51:48.245209'),
(13, 88, 'REPRESENTATIVE', '2026-01-02 18:52:05.619159'),
(13, 89, 'REPRESENTATIVE', '2026-02-04 00:58:09.367656'),
(13, 90, 'REPRESENTATIVE', '2026-01-27 07:24:54.672698'),
(14, 91, 'REPRESENTATIVE', '2026-05-14 21:21:04.522221'),
(15, 92, 'REPRESENTATIVE', '2025-08-30 21:17:14.900987'),
(16, 93, 'REPRESENTATIVE', '2026-03-12 10:46:01.894822'),
(16, 94, 'REPRESENTATIVE', '2026-03-26 02:20:18.931937'),
(17, 95, 'REPRESENTATIVE', '2026-02-10 10:06:57.427197'),
(17, 96, 'REPRESENTATIVE', '2025-12-20 14:13:43.318011'),
(19, 97, 'REPRESENTATIVE', '2025-12-31 00:12:14.217233'),
(21, 98, 'REPRESENTATIVE', '2026-05-03 10:43:19.489883'),
(21, 99, 'REPRESENTATIVE', '2025-10-02 09:34:01.311641'),
(22, 100, 'REPRESENTATIVE', '2026-06-03 02:30:12.761426'),
(22, 101, 'REPRESENTATIVE', '2026-05-17 05:20:29.655226'),
(23, 102, 'REPRESENTATIVE', '2025-07-14 11:56:05.993528'),
(23, 103, 'REPRESENTATIVE', '2026-01-26 11:51:28.585407'),
(23, 104, 'REPRESENTATIVE', '2026-03-10 01:54:40.745611'),
(25, 105, 'REPRESENTATIVE', '2025-09-19 14:05:25.364861'),
(25, 106, 'REPRESENTATIVE', '2025-08-17 14:32:45.979501'),
(25, 107, 'REPRESENTATIVE', '2026-06-14 05:07:31.464166'),
(28, 108, 'REPRESENTATIVE', '2026-03-27 04:12:36.867981'),
(28, 109, 'REPRESENTATIVE', '2026-05-11 22:12:41.428426'),
(28, 110, 'REPRESENTATIVE', '2026-05-02 17:09:24.002836'),
(30, 111, 'REPRESENTATIVE', '2026-01-09 00:12:29.687512'),
(30, 112, 'REPRESENTATIVE', '2025-11-24 08:47:01.154588'),
(30, 113, 'REPRESENTATIVE', '2025-11-17 12:36:36.370832'),
(31, 114, 'REPRESENTATIVE', '2026-02-24 01:06:51.632237'),
(31, 115, 'REPRESENTATIVE', '2025-09-15 00:40:13.168559'),
(31, 116, 'REPRESENTATIVE', '2025-09-27 02:37:31.977529'),
(32, 117, 'REPRESENTATIVE', '2026-03-17 23:49:57.045132'),
(33, 118, 'REPRESENTATIVE', '2026-05-19 00:04:41.403453'),
(33, 119, 'REPRESENTATIVE', '2025-11-07 15:30:33.643253'),
(34, 120, 'REPRESENTATIVE', '2025-12-29 21:33:39.945563'),
(34, 121, 'REPRESENTATIVE', '2025-09-25 16:56:20.141398'),
(35, 122, 'REPRESENTATIVE', '2026-05-15 19:05:59.419043'),
(35, 123, 'REPRESENTATIVE', '2025-07-20 11:54:50.474209'),
(35, 124, 'REPRESENTATIVE', '2025-08-14 08:45:42.810851'),
(36, 125, 'REPRESENTATIVE', '2026-06-25 02:16:42.616700'),
(36, 126, 'REPRESENTATIVE', '2025-11-29 08:25:25.102689'),
(37, 127, 'REPRESENTATIVE', '2026-06-28 03:52:04.121268'),
(37, 128, 'REPRESENTATIVE', '2025-07-23 17:08:52.618363'),
(37, 129, 'REPRESENTATIVE', '2025-11-20 10:50:03.992979'),
(39, 130, 'REPRESENTATIVE', '2026-01-15 23:34:12.525861'),
(39, 131, 'REPRESENTATIVE', '2025-07-28 17:16:40.809293'),
(39, 132, 'REPRESENTATIVE', '2025-10-08 18:20:49.877208'),
(42, 133, 'REPRESENTATIVE', '2025-08-28 00:42:27.998555'),
(42, 134, 'REPRESENTATIVE', '2025-09-13 17:47:19.822740'),
(42, 135, 'REPRESENTATIVE', '2026-04-29 03:44:26.940682'),
(43, 136, 'REPRESENTATIVE', '2025-12-17 09:50:21.898942'),
(43, 137, 'REPRESENTATIVE', '2026-04-27 10:00:07.776017'),
(44, 138, 'REPRESENTATIVE', '2026-04-06 10:57:58.232993'),
(44, 139, 'REPRESENTATIVE', '2026-03-16 16:33:12.814176'),
(45, 140, 'REPRESENTATIVE', '2026-05-26 10:26:54.221456'),
(45, 141, 'REPRESENTATIVE', '2026-06-23 06:55:12.156871'),
(45, 142, 'REPRESENTATIVE', '2025-12-09 23:54:35.820009'),
(46, 143, 'REPRESENTATIVE', '2026-01-05 05:56:59.441467'),
(48, 144, 'REPRESENTATIVE', '2025-10-12 00:12:32.822761'),
(48, 145, 'REPRESENTATIVE', '2025-09-22 22:43:15.632175'),
(48, 146, 'REPRESENTATIVE', '2026-03-05 20:11:20.703389'),
(49, 147, 'REPRESENTATIVE', '2025-12-30 04:45:02.705749'),
(49, 148, 'REPRESENTATIVE', '2026-05-17 19:59:49.601697');

-- Party Contacts
INSERT INTO party_contact (party_id, type, details) VALUES
(1, 'EMAIL', 'info@kleincoleandcherry.com'),
(1, 'PHONE', '356.819.5344'),
(2, 'EMAIL', 'info@morrisbrownandtate.com'),
(2, 'PHONE', '5494124445'),
(3, 'EMAIL', 'info@gibbswaltonandhoover.com'),
(3, 'PHONE', '+1-650-579-1987x27024'),
(4, 'EMAIL', 'info@davis-williams.com'),
(4, 'PHONE', '(413)617-9794x619'),
(5, 'EMAIL', 'info@bradley-hogan.com'),
(5, 'PHONE', '769-444-0547'),
(6, 'EMAIL', 'info@parsonsplc.com'),
(6, 'PHONE', '289.430.3801x4339'),
(7, 'EMAIL', 'info@bowenrobinsonandpark.com'),
(7, 'PHONE', '576.382.9599'),
(8, 'EMAIL', 'info@fritzgroup.com'),
(8, 'PHONE', '847-219-5493'),
(9, 'EMAIL', 'info@mccall-preston.com'),
(9, 'PHONE', '704-256-8801x92127'),
(10, 'EMAIL', 'info@woodwardplc.com'),
(10, 'PHONE', '+1-758-462-1753x900'),
(11, 'EMAIL', 'info@stone-brown.com'),
(11, 'PHONE', '+1-657-381-6124x3415'),
(12, 'EMAIL', 'info@gibsonltd.com'),
(12, 'PHONE', '308-532-2011'),
(13, 'EMAIL', 'info@cardenas-smith.com'),
(13, 'PHONE', '973-222-0841x6617'),
(14, 'EMAIL', 'info@barajasplc.com'),
(14, 'PHONE', '399.202.8347x2594'),
(15, 'EMAIL', 'info@oliver-garza.com'),
(16, 'EMAIL', 'info@lawsoninc.com'),
(16, 'PHONE', '700-810-6185x725'),
(17, 'EMAIL', 'info@taylorsimmonsandcoffey.com'),
(17, 'PHONE', '855.559.5549x047'),
(18, 'EMAIL', 'info@wrightdeleonanddorsey.com'),
(19, 'EMAIL', 'info@brown-cabrera.com'),
(19, 'PHONE', '+1-698-428-2094'),
(20, 'EMAIL', 'info@kennedyllc.com'),
(20, 'PHONE', '(888)278-6610'),
(21, 'EMAIL', 'info@lewis-archer.com'),
(21, 'PHONE', '404-421-2409'),
(22, 'EMAIL', 'info@burkeandsons.com'),
(22, 'PHONE', '279.978.2720'),
(23, 'EMAIL', 'info@walterschristianandfleming.com'),
(23, 'PHONE', '001-243-324-9577x48277'),
(24, 'EMAIL', 'info@harrisonandsons.com'),
(24, 'PHONE', '001-853-801-6281'),
(25, 'EMAIL', 'info@hernandezwillisandmunoz.com'),
(26, 'EMAIL', 'info@gonzalezltd.com'),
(26, 'PHONE', '+1-304-404-3413x9921'),
(27, 'EMAIL', 'info@rogers-davis.com'),
(27, 'PHONE', '001-514-443-7450x2363'),
(28, 'EMAIL', 'info@jones-thomas.com'),
(28, 'PHONE', '(347)898-6504x4644'),
(29, 'EMAIL', 'info@harrellmorenoandsalas.com'),
(29, 'PHONE', '001-609-979-4762'),
(30, 'EMAIL', 'info@pittman-houston.com'),
(30, 'PHONE', '+1-362-385-8778'),
(31, 'EMAIL', 'info@welchgayandfarmer.com'),
(31, 'PHONE', '001-911-358-9602x80485'),
(32, 'EMAIL', 'info@browngroup.com'),
(32, 'PHONE', '441.337.8064x506'),
(33, 'EMAIL', 'info@jonesltd.com'),
(33, 'PHONE', '399-955-4087'),
(34, 'EMAIL', 'info@taylordorseyandwilliamson.com'),
(34, 'PHONE', '(567)999-2526'),
(35, 'EMAIL', 'info@johnsonllc.com'),
(35, 'PHONE', '586-530-1104x412'),
(36, 'EMAIL', 'info@smithtaylorandlindsey.com'),
(36, 'PHONE', '232.473.3993x427'),
(37, 'EMAIL', 'info@bakerschultzandgarcia.com'),
(37, 'PHONE', '886-894-4339x98072'),
(38, 'EMAIL', 'info@collins-hunter.com'),
(39, 'EMAIL', 'info@irwingroup.com'),
(40, 'EMAIL', 'info@lewisllc.com'),
(40, 'PHONE', '718-691-9567'),
(41, 'EMAIL', 'info@torresnormanandmiller.com'),
(42, 'EMAIL', 'info@moore-callahan.com'),
(42, 'PHONE', '764-849-0906x28452'),
(43, 'EMAIL', 'info@petersen-collins.com'),
(43, 'PHONE', '+1-367-200-9063'),
(44, 'EMAIL', 'info@vasquezmcclureandcampbell.com'),
(44, 'PHONE', '742-992-5735x917'),
(45, 'EMAIL', 'info@trevinothomasandchavez.com'),
(46, 'EMAIL', 'info@silvaplc.com'),
(46, 'PHONE', '001-729-468-0254x2109'),
(47, 'EMAIL', 'info@fritzllc.com'),
(48, 'EMAIL', 'info@morgan-russo.com'),
(48, 'PHONE', '486-466-4687x7873'),
(49, 'EMAIL', 'info@lambert-pitts.com'),
(49, 'PHONE', '396-804-1519'),
(50, 'EMAIL', 'info@fuentesltd.com'),
(50, 'PHONE', '001-946-687-6435x051'),
(71, 'EMAIL', 'jasmin.wagner@kleincoleandcherry.com'),
(71, 'PHONE', '+1-288-567-6582x4235'),
(72, 'EMAIL', 'erik.austin@kleincoleandcherry.com'),
(72, 'PHONE', '001-819-748-1358'),
(73, 'EMAIL', 'christopher.moore@kleincoleandcherry.com'),
(74, 'EMAIL', 'casey.jones@morrisbrownandtate.com'),
(74, 'PHONE', '+1-498-249-5852'),
(75, 'EMAIL', 'mary.reid@morrisbrownandtate.com'),
(75, 'PHONE', '481-491-5177x82671'),
(76, 'EMAIL', 'andrea.grant@gibbswaltonandhoover.com'),
(76, 'PHONE', '651.321.1370x228'),
(77, 'EMAIL', 'scott.brown@davis-williams.com'),
(77, 'PHONE', '635.875.5007x9483'),
(78, 'EMAIL', 'tina.levine@davis-williams.com'),
(78, 'PHONE', '+1-792-504-1678x4292'),
(79, 'EMAIL', 'jessica.torres@parsonsplc.com'),
(79, 'PHONE', '+1-518-329-6801x244'),
(80, 'EMAIL', 'bruce.yu@parsonsplc.com'),
(80, 'PHONE', '(446)940-2729x42361'),
(81, 'EMAIL', 'mrs..md@parsonsplc.com'),
(81, 'PHONE', '390.476.6773x3807'),
(82, 'EMAIL', 'cindy.moore@mccall-preston.com'),
(82, 'PHONE', '6696753783'),
(83, 'EMAIL', 'briana.morse@woodwardplc.com'),
(83, 'PHONE', '839.656.6373x46057'),
(84, 'EMAIL', 'andrew.snyder@woodwardplc.com'),
(84, 'PHONE', '(272)539-4852'),
(85, 'EMAIL', 'michael.johnson@woodwardplc.com'),
(85, 'PHONE', '001-226-444-1178x476'),
(86, 'EMAIL', 'david.goodman@gibsonltd.com'),
(86, 'PHONE', '+1-619-404-8595x36153'),
(87, 'EMAIL', 'christopher.brown@gibsonltd.com'),
(87, 'PHONE', '+1-745-396-8362x4330'),
(88, 'EMAIL', 'brandon.goodwin@cardenas-smith.com'),
(88, 'PHONE', '(490)789-4196'),
(89, 'EMAIL', 'valerie.johnson@cardenas-smith.com'),
(89, 'PHONE', '691-810-3155'),
(90, 'EMAIL', 'shelley.taylor@cardenas-smith.com'),
(90, 'PHONE', '515.787.2547'),
(91, 'EMAIL', 'aaron.alexander@barajasplc.com'),
(91, 'PHONE', '7817583735'),
(92, 'EMAIL', 'patrick.barry@oliver-garza.com'),
(93, 'EMAIL', 'cassandra.hansen@lawsoninc.com'),
(93, 'PHONE', '(846)425-4361'),
(94, 'EMAIL', 'caitlin.powers@lawsoninc.com'),
(95, 'EMAIL', 'scott.henry@taylorsimmonsandcoffey.com'),
(95, 'PHONE', '729.561.7585x018'),
(96, 'EMAIL', 'lindsay.gould@taylorsimmonsandcoffey.com'),
(96, 'PHONE', '846.753.7509'),
(97, 'EMAIL', 'eduardo.moreno@brown-cabrera.com'),
(97, 'PHONE', '001-211-584-0230x7449'),
(98, 'EMAIL', 'david.giles@lewis-archer.com'),
(98, 'PHONE', '+1-493-763-8433x699'),
(99, 'EMAIL', 'steven.greer@lewis-archer.com'),
(99, 'PHONE', '744-892-5619'),
(100, 'EMAIL', 'matthew.phd@burkeandsons.com'),
(100, 'PHONE', '+1-307-277-0658x780'),
(101, 'EMAIL', 'charles.reese@burkeandsons.com'),
(101, 'PHONE', '450-730-1809x7468'),
(102, 'EMAIL', 'amanda.jones@walterschristianandfleming.com'),
(102, 'PHONE', '(385)497-1611x57726'),
(103, 'EMAIL', 'dr..phd@walterschristianandfleming.com'),
(103, 'PHONE', '+1-820-248-4448x9522'),
(104, 'EMAIL', 'lindsey.gonzalez@walterschristianandfleming.com'),
(104, 'PHONE', '753.735.5481x7077'),
(105, 'EMAIL', 'vanessa.mann@hernandezwillisandmunoz.com'),
(105, 'PHONE', '001-464-339-6009x0513'),
(106, 'EMAIL', 'kari.castro@hernandezwillisandmunoz.com'),
(106, 'PHONE', '001-257-380-3952'),
(107, 'EMAIL', 'christopher.velasquez@hernandezwillisandmunoz.com'),
(108, 'EMAIL', 'jennifer.dickerson@jones-thomas.com'),
(108, 'PHONE', '4132087282'),
(109, 'EMAIL', 'sharon.randolph@jones-thomas.com'),
(109, 'PHONE', '957-567-1497'),
(110, 'EMAIL', 'barbara.taylor@jones-thomas.com'),
(110, 'PHONE', '834-706-5692x442'),
(111, 'EMAIL', 'stacey.smith@pittman-houston.com'),
(111, 'PHONE', '001-393-349-0954'),
(112, 'EMAIL', 'jeremy.patterson@pittman-houston.com'),
(112, 'PHONE', '4614366496'),
(113, 'EMAIL', 'jamie.richardson@pittman-houston.com'),
(113, 'PHONE', '(555)976-2098x63473'),
(114, 'EMAIL', 'kimberly.stone@welchgayandfarmer.com'),
(114, 'PHONE', '001-725-490-8240x19072'),
(115, 'EMAIL', 'tina.montgomery@welchgayandfarmer.com'),
(115, 'PHONE', '+1-256-845-8210x506'),
(116, 'EMAIL', 'robert.green@welchgayandfarmer.com'),
(116, 'PHONE', '(954)797-4306x98491'),
(117, 'EMAIL', 'keith.huff@browngroup.com'),
(118, 'EMAIL', 'george.anderson@jonesltd.com'),
(118, 'PHONE', '001-545-826-1751x41070'),
(119, 'EMAIL', 'brianna.becker@jonesltd.com'),
(119, 'PHONE', '(242)556-0112x139'),
(120, 'EMAIL', 'bobby.luna@taylordorseyandwilliamson.com'),
(120, 'PHONE', '943-439-9701'),
(121, 'EMAIL', 'paul.rivera@taylordorseyandwilliamson.com'),
(121, 'PHONE', '(266)220-9497x778'),
(122, 'EMAIL', 'tiffany.bradley@johnsonllc.com'),
(123, 'EMAIL', 'ryan.macdonald@johnsonllc.com'),
(123, 'PHONE', '+1-522-655-4665'),
(124, 'EMAIL', 'brian.jones@johnsonllc.com'),
(124, 'PHONE', '817.217.0126'),
(125, 'EMAIL', 'lisa.morris@smithtaylorandlindsey.com'),
(125, 'PHONE', '(475)885-0382x580'),
(126, 'EMAIL', 'richard.baker@smithtaylorandlindsey.com'),
(126, 'PHONE', '(704)674-7626'),
(127, 'EMAIL', 'douglas.page@bakerschultzandgarcia.com'),
(127, 'PHONE', '208-767-9468x10465'),
(128, 'EMAIL', 'jacqueline.dvm@bakerschultzandgarcia.com'),
(128, 'PHONE', '384.343.3202'),
(129, 'EMAIL', 'eric.sutton@bakerschultzandgarcia.com'),
(129, 'PHONE', '+1-264-586-5136'),
(130, 'EMAIL', 'debra.smith@irwingroup.com'),
(130, 'PHONE', '692-416-9971x5094'),
(131, 'EMAIL', 'theodore.parker@irwingroup.com'),
(131, 'PHONE', '870.348.0903x9603'),
(132, 'EMAIL', 'ashley.torres@irwingroup.com'),
(132, 'PHONE', '485-362-9707x88841'),
(133, 'EMAIL', 'jennifer.ramos@moore-callahan.com'),
(133, 'PHONE', '551.504.6131x9972'),
(134, 'EMAIL', 'abigail.reed@moore-callahan.com'),
(135, 'EMAIL', 'tamara.horn@moore-callahan.com'),
(136, 'EMAIL', 'terry.chen@petersen-collins.com'),
(136, 'PHONE', '985.754.7381'),
(137, 'EMAIL', 'preston.wolf@petersen-collins.com'),
(137, 'PHONE', '(673)894-3494x86763'),
(138, 'EMAIL', 'dawn.miller@vasquezmcclureandcampbell.com'),
(138, 'PHONE', '+1-916-717-4512'),
(139, 'EMAIL', 'samuel.krueger@vasquezmcclureandcampbell.com'),
(139, 'PHONE', '001-448-849-5293x389'),
(140, 'EMAIL', 'jennifer.wilson@trevinothomasandchavez.com'),
(140, 'PHONE', '(778)572-6477x826'),
(141, 'EMAIL', 'stacey.williams@trevinothomasandchavez.com'),
(141, 'PHONE', '001-761-901-5975x924'),
(142, 'EMAIL', 'gabriel.schmidt@trevinothomasandchavez.com'),
(142, 'PHONE', '+1-607-763-4949x80935'),
(143, 'EMAIL', 'cynthia.day@silvaplc.com'),
(143, 'PHONE', '877-445-5871'),
(144, 'EMAIL', 'douglas.watson@morgan-russo.com'),
(144, 'PHONE', '960.625.8357'),
(145, 'EMAIL', 'joseph.berger@morgan-russo.com'),
(146, 'EMAIL', 'ashley.morales@morgan-russo.com'),
(146, 'PHONE', '243-776-2653'),
(147, 'EMAIL', 'sean.velasquez@lambert-pitts.com'),
(147, 'PHONE', '996.217.3543x70845'),
(148, 'EMAIL', 'mark.hardin@lambert-pitts.com'),
(148, 'PHONE', '+1-684-397-7905x2813');

-- Contractor Addresses
INSERT INTO address (address_id, party_id, street_address, city, country, postal_code, address_type) VALUES
('2b132516-4251-4613-87fd-d4b814f972fe', 1, '6796 Debra Grove Apt. 907', 'Starkview', 'Honduras', '95460', 'BILLING'),
('a53ab0d9-ff36-4c6d-8821-51e0d55a434b', 2, '5699 Stephanie Points', 'Lake Dustinfurt', 'Grenada', '07680', 'CORPORATE'),
('6f95eae3-7cef-4b04-af30-2e2656eefa25', 2, '70207 Connie Prairie Apt. 041', 'Toddton', 'Andorra', '26508', 'OTHER'),
('1ce76a66-974e-4efd-8f99-1129d99a5161', 3, '71756 Martinez Divide', 'Herreraton', 'Morocco', '01276', 'SHIPPING'),
('1e0cd39e-6c8d-459b-8053-22c93c6cb1e5', 3, '57042 Long Rapid', 'West Christopher', 'Brunei Darussalam', '71889', 'BILLING'),
('b4966189-0bd5-4729-850d-020177adbca5', 4, '721 Donald Springs', 'Zimmermanborough', 'Costa Rica', '54001', 'SHIPPING'),
('d739b781-5d05-4d06-811a-35bbbc0c361d', 5, '3818 Atkins Burgs', 'Gallegoschester', 'Sudan', '52797', 'BILLING'),
('09a5c342-cc8d-4316-84fb-e5161987c178', 6, '964 Parker Unions Apt. 717', 'Carolinemouth', 'Montenegro', '40351', 'BILLING'),
('81d54bd2-adcc-4049-89c9-2cbf59da1a00', 6, '3018 Martinez Inlet', 'Kathleenberg', 'Albania', '86611', 'CORPORATE'),
('c36ad24c-3aaa-4479-b731-1c7ffa76b674', 7, '3379 Kyle Junctions Suite 839', 'East Patriciamouth', 'Lesotho', '12103', 'OTHER'),
('f329279e-f9ae-4f95-831e-53a3fec6ee17', 8, '883 Patricia Turnpike Apt. 718', 'West Aaron', 'Swaziland', '73246', 'BILLING'),
('2144f295-42f1-4c78-9338-e20ba5cdfa2b', 8, '6218 Hernandez Tunnel Suite 495', 'Lake Jennifer', 'Bermuda', '26762', 'OTHER'),
('b5de2d27-6850-4ff5-86b9-705d9d01973e', 9, '46467 Eric Shoals', 'North Dannyfort', 'Antarctica (the territory South of 60 deg S)', '34381', 'CORPORATE'),
('10b10b79-71b7-466d-a3c1-6225ce4726a8', 9, '17632 Jackson Field Apt. 568', 'East Moniqueburgh', 'Latvia', '69846', 'OTHER'),
('5adbf836-af1d-4ba7-a1d9-71132214747d', 10, '976 Daniel Creek Suite 483', 'Brentstad', 'Angola', '17333', 'BILLING'),
('f8f1aa4c-6265-4121-b3f4-83569febe903', 11, '713 Jones Forks', 'New Stephanieport', 'Morocco', '48062', 'BILLING'),
('26b51e37-28f7-4d2a-8fae-fc2c19b383cb', 11, '550 Kristina Freeway', 'Paulchester', 'Liberia', '04778', 'OTHER'),
('06dd6c78-24a1-469f-8bff-c4cbd5177d82', 11, '7126 Clements Square', 'Paulhaven', 'Saint Helena', '62680', 'SHIPPING'),
('4d349756-51d1-4231-861a-d374e21ad078', 12, '212 Matthew Crest Suite 730', 'Lake John', 'United Arab Emirates', '61168', 'BILLING'),
('48329303-48ac-4137-a1cb-a431feda133a', 12, '6092 Farrell Crescent Apt. 850', 'South Jessica', 'Kazakhstan', '96405', 'OTHER'),
('e6a9d942-81b7-46e8-beb2-00152f789e12', 12, '018 Nixon Flats Suite 866', 'New Ericburgh', 'Moldova', '23684', 'CORPORATE'),
('8a2bc525-2615-4e57-bd9a-9b2d18dcba98', 13, '6702 Ann Fork', 'Lake Erinmouth', 'Aruba', '96456', 'CORPORATE'),
('f9c8ba19-848f-4e10-9050-a14aa154a074', 14, '9087 Goodwin Brook Suite 121', 'West Wesley', 'Tokelau', '36526', 'SHIPPING'),
('ade7b93d-1dee-4e63-8eac-d0684ca8a87e', 15, '663 Schwartz Squares', 'Sheastad', 'Bangladesh', '77556', 'CORPORATE'),
('f452c9e0-f960-4cfd-bae5-7f0f85903a0b', 16, '482 Marks Mews', 'North Ernest', 'Mauritius', '43454', 'SHIPPING'),
('d3e85a2b-b334-4724-be04-d286a7924dd2', 17, '48914 Nichols Underpass', 'Butlerland', 'Nauru', '85282', 'SHIPPING'),
('250412c3-3bb1-4753-8110-ff0155e273a7', 17, '8647 Black Neck', 'North Jeffreystad', 'Pakistan', '29801', 'BILLING'),
('99352075-66a3-48d1-bc90-5cd7c3948ac2', 17, '5400 Jose Summit', 'South Marcusborough', 'Armenia', '13264', 'CORPORATE'),
('215acd2e-7cee-47fc-890d-fde45b273b98', 18, '43601 Frost Point', 'Williamville', 'Haiti', '53443', 'BILLING'),
('037ef041-6625-41df-a595-013c7fdac1a5', 19, '8144 Estes Extensions Suite 195', 'Alyssamouth', 'Oman', '58789', 'OTHER'),
('166262aa-0e92-44b5-8530-8b8aabaaa845', 19, '727 Noble Forges', 'Hendersonfurt', 'Cayman Islands', '20070', 'CORPORATE'),
('b91371b8-6d50-4f68-99f6-24e47a535cd3', 20, '403 Ricardo Inlet Apt. 271', 'Travisside', 'Portugal', '09878', 'OTHER'),
('51ece14f-d444-4dbd-852f-4b5bcf640b43', 21, '01134 Keith Key Suite 150', 'East Heathermouth', 'New Zealand', '97529', 'OTHER'),
('2f878889-f5d9-4f52-a4a9-fb8ee83cf019', 22, '731 Villanueva Dale', 'North Deanna', 'Ghana', '55575', 'SHIPPING'),
('89189931-ba0d-4ab1-a355-59acf790453d', 23, '34627 Zachary Wall Suite 033', 'South Nicole', 'Nepal', '07641', 'OTHER'),
('d5c00d5a-7c5c-4545-90a7-dad461806227', 24, '92922 Jimmy Trace', 'Dunlapmouth', 'Turks and Caicos Islands', '27101', 'BILLING'),
('f4f325d4-2640-4e00-92d2-d6efc610d457', 25, '096 Laura Manor Apt. 165', 'Derekborough', 'Cape Verde', '89351', 'BILLING'),
('ad1aa2be-02b2-42b1-b4be-748bf1954dc7', 25, '34545 Watts Manor Apt. 235', 'Hansenshire', 'Wallis and Futuna', '18800', 'CORPORATE'),
('6961cbb7-6ac1-4032-9d2b-de34a7ad8bae', 25, '59311 Kristie Expressway', 'North Loriville', 'Ukraine', '20549', 'SHIPPING'),
('b5e7e191-5b5c-4e01-85a7-7e244c87af19', 26, '3618 Olsen View', 'East Lisa', 'Libyan Arab Jamahiriya', '28164', 'BILLING'),
('e7096167-ca4b-41b6-abfd-c02e17c97ea3', 26, '2244 Nicholas Islands Suite 671', 'Joycebury', 'Brazil', '47962', 'SHIPPING'),
('7fd892e4-c316-463d-b919-de3b6c0bab1a', 27, '407 Pittman Vista', 'Lake Erin', 'Equatorial Guinea', '85581', 'OTHER'),
('ee20dae4-d1bd-4619-9f54-0a4fc5cc041c', 28, '67713 Turner Well Suite 099', 'Port Nicolemouth', 'Kenya', '23091', 'OTHER'),
('8c4d45fa-3fa6-4e8b-af02-5e37430b24ae', 29, '5421 Joshua Mountain', 'Simonhaven', 'Croatia', '59059', 'BILLING'),
('037e3f8b-525d-4353-9537-09cf024ada9f', 30, '88548 Miller Union Suite 462', 'North Natashatown', 'Equatorial Guinea', '06666', 'CORPORATE'),
('799c46ae-c28a-4f41-9eeb-29cce1e6d92a', 30, '50007 Edward Road Apt. 081', 'Kylieshire', 'Belize', '78988', 'SHIPPING'),
('c61f3c18-3919-41b8-8b68-6972f913963d', 31, '96052 Nathaniel Land Suite 432', 'New Jasonmouth', 'Bouvet Island (Bouvetoya)', '80319', 'BILLING'),
('8512e975-3d7e-4258-801d-370c77bdb475', 31, '849 Sierra Terrace Apt. 678', 'East Lauren', 'Suriname', '79435', 'OTHER'),
('d595046b-e50e-4133-b097-344bd30b398f', 32, '15091 Anne Plains Apt. 292', 'Tiffanyfort', 'Tunisia', '87711', 'BILLING'),
('3a008596-c405-4174-8060-156218e6d554', 33, '79514 Pamela Well Apt. 490', 'West Karen', 'Angola', '31855', 'BILLING'),
('4504ccc4-7f02-4150-8a60-ba8b3e510438', 33, '4486 Johnson Manor Apt. 992', 'Port Tyler', 'Belarus', '07011', 'CORPORATE'),
('05383561-595e-468b-8d75-e944cdf4f7cf', 33, '147 Rogers Mountain', 'Lake Jacquelinehaven', 'Australia', '21479', 'OTHER'),
('558af908-b842-4f60-a33f-be84b60204ab', 34, '23870 Jessica Viaduct Suite 042', 'Hallmouth', 'Algeria', '47702', 'OTHER'),
('a203d7ae-02fc-41c0-ae86-4ba93455fc3e', 34, '5615 Julia Lane', 'Henrymouth', 'Uruguay', '82191', 'CORPORATE'),
('a79ec051-497a-4f5a-a9ad-d78c32f8ca22', 35, '14371 Martin Highway Apt. 004', 'Port Jenniferfurt', 'Ghana', '76896', 'CORPORATE'),
('ad99f042-3996-496d-ac4b-53579002bdb4', 35, '5823 Smith Loop', 'Port Douglas', 'Uganda', '80773', 'OTHER'),
('6c2a5229-dcca-44e3-b519-16b114d6b1a0', 35, '3565 Hernandez Vista', 'Priceberg', 'United States Virgin Islands', '53035', 'BILLING'),
('bf4770c1-b2b3-4f2e-be2f-838dc90e1d6b', 36, '96733 Newton Alley Apt. 857', 'West Katelyn', 'Iceland', '75633', 'SHIPPING'),
('dd2f6301-7db5-4b7c-a5b1-2f3e78ecf786', 36, '6997 Richard Station Apt. 039', 'Irwinton', 'Kuwait', '14261', 'BILLING'),
('b8c20a3f-9abc-4719-a48c-d0bfa10ebdd2', 36, '1399 Knight Mission Apt. 932', 'Sloanshire', 'Congo', '73017', 'CORPORATE'),
('d50d1050-a3f6-43d7-a1f3-50b71880d1d3', 37, '795 Joseph Fork Apt. 685', 'Christophermouth', 'Jamaica', '97676', 'SHIPPING'),
('76cf64b8-3b94-4955-88c3-acfb22e33b0f', 37, '5724 Elizabeth Pike', 'Saunderstown', 'Swaziland', '52875', 'BILLING'),
('8d9cc0f7-22cb-4f9c-bc30-ebbd84fb4353', 37, '5570 Parker Dam Apt. 385', 'Parkerfort', 'Bulgaria', '24121', 'CORPORATE'),
('0ee889c8-6aa4-4f4a-be53-f24cb21624d1', 38, '261 Kevin Loaf', 'Jennifershire', 'Saint Kitts and Nevis', '64550', 'SHIPPING'),
('93eb26ce-491c-48b0-b0c8-d60828e1a812', 39, '347 Cox Corner Apt. 499', 'Jenniferland', 'China', '40198', 'OTHER'),
('a4fc8568-7e25-4116-9455-b644d019ca9f', 40, '005 April Villages Suite 150', 'East Michelle', 'United States Virgin Islands', '57447', 'CORPORATE'),
('cd6a4f50-116e-4483-b621-6b62306baa37', 40, '44429 Timothy Divide', 'Prestonport', 'Gabon', '40187', 'SHIPPING'),
('5df5b4d7-e632-448c-8dbf-82f827dd037b', 41, '7038 Wilkerson Tunnel', 'New Robertstad', 'Georgia', '39611', 'BILLING'),
('caf9de6f-2e35-46b1-86a7-eeaf2cd246a7', 42, '17601 Diaz Lodge', 'Ronaldhaven', 'Sierra Leone', '21845', 'OTHER'),
('4510796f-8612-4f0a-b145-d026f966d73d', 42, '6504 Coleman Center Apt. 947', 'Kathytown', 'Micronesia', '25433', 'CORPORATE'),
('dbc2dc14-ca33-4f82-a19a-834a16039053', 43, '270 Lauren Ports Apt. 964', 'Burnsbury', 'Antarctica (the territory South of 60 deg S)', '22430', 'BILLING'),
('f933bb54-aa2c-4cfd-9a79-0bf8370c2887', 43, '33441 James Lake', 'New John', 'Turks and Caicos Islands', '50646', 'OTHER'),
('a625ac73-f052-41b9-9788-9d470d3adc73', 44, '791 Beard Squares Suite 023', 'East Harold', 'Cayman Islands', '54994', 'CORPORATE'),
('df945dc7-6941-493f-aa07-5865fb6f55ac', 45, '6940 Robert Station Suite 421', 'North Joseph', 'Pitcairn Islands', '17948', 'BILLING'),
('bcb5e182-7fe5-4631-875e-604b68b6848b', 46, '85339 Sierra Club', 'Fergusonstad', 'Western Sahara', '68211', 'OTHER'),
('d3c2edc2-81fe-4769-b8b6-b2639bef7e35', 47, '03517 Noble Mountains Suite 317', 'South Adam', 'Latvia', '81142', 'OTHER'),
('47577a4c-42c0-4bf5-93ff-70908e2e4ed2', 48, '7227 Michael Mews Suite 871', 'Sanchezland', 'Morocco', '32161', 'CORPORATE'),
('c0686fc1-d8c7-4c2b-b3ce-ff3b197f46a8', 48, '9780 Patty Ridge', 'Mendozahaven', 'Korea', '87032', 'OTHER'),
('111cb13a-7589-4501-b525-d80c1bed3660', 48, '2419 Richardson Branch', 'Allenmouth', 'Gambia', '31544', 'BILLING'),
('a05d30c5-a7ad-485a-8839-0d3c1ef4dc18', 49, '515 Dustin Forks Apt. 729', 'Howeburgh', 'Ukraine', '86434', 'CORPORATE'),
('aadb68c7-2b0e-4ca9-83eb-461d19f12324', 50, '310 Hodge Ports', 'Williamsshire', 'Christmas Island', '75270', 'SHIPPING'),
('ed054c69-6093-47bf-8da2-53aff769b885', 50, '1638 Joseph Field Apt. 403', 'Michaelville', 'Saint Helena', '71792', 'OTHER');

-- Employee Parties
INSERT INTO party (party_id, name, data, created_at, updated_at) VALUES
(51, 'Erik Rhodes', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-05-09 06:11:54', '2026-06-29 06:13:49'),
(52, 'Stuart Hicks', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-10-16 22:14:58', '2026-02-11 20:49:43'),
(53, 'William Turner', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2021-10-10 23:41:01', '2026-02-28 04:31:32'),
(54, 'Jennifer Owen', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2025-02-03 05:55:32', '2026-04-22 21:52:01'),
(55, 'Joseph Kemp', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-03-17 14:05:34', '2026-04-29 17:24:35'),
(56, 'Monique Kelley', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-10-29 20:15:21', '2026-06-28 22:33:51'),
(57, 'Ryan Henderson', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2023-06-02 02:22:23', '2025-07-08 19:47:46'),
(58, 'Laura Brooks', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-02-24 06:31:56', '2026-05-10 12:40:23'),
(59, 'Elaine Cruz', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-08-22 06:17:40', '2026-02-17 13:15:04'),
(60, 'James Rodriguez', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2025-02-11 08:09:26', '2025-12-28 21:17:11'),
(61, 'Jill Graves', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2021-09-16 23:30:25', '2025-11-02 12:34:22'),
(62, 'Crystal Osborne', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-11-12 01:43:06', '2026-06-09 01:18:41'),
(63, 'Jennifer Blanchard', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-09-20 06:03:20', '2026-06-30 03:47:57'),
(64, 'David Davis', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2023-09-01 11:36:31', '2025-10-27 23:58:23'),
(65, 'William Snyder', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2025-02-05 17:52:38', '2026-06-20 05:06:11'),
(66, 'Lisa Wilson', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-05-14 08:18:58', '2026-02-21 09:14:44'),
(67, 'Angelica Thomas', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-09-29 12:18:58', '2025-09-07 10:24:26'),
(68, 'Kyle Henderson', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2023-01-25 05:55:47', '2026-01-09 04:28:34'),
(69, 'Rebecca Hubbard', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-08-19 16:09:29', '2025-12-02 21:14:57'),
(70, 'Jennifer Phillips', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-07-16 13:39:35', '2025-11-03 11:24:52');

-- Employee Addresses
INSERT INTO address (address_id, party_id, street_address, city, country, postal_code, address_type) VALUES
('4ac93eec-3742-4d79-82ba-22cebbc76010', 51, '967 Green Mount', 'Lake Cynthiachester', 'Austria', '34589', 'OTHER'),
('9bbbf921-6020-4183-80c1-aa0348a16221', 52, '395 Rebecca Mews', 'Port Johnshire', 'Eritrea', '08241', 'PERSONAL'),
('35e59a4c-e057-4ffd-804d-558c5e8d8a0b', 52, '737 Hernandez Port Suite 458', 'North Adamchester', 'British Indian Ocean Territory (Chagos Archipelago)', '71778', 'OTHER'),
('a3a72a7a-4ef5-46f3-b9f3-0c024cc9ec1f', 53, '963 Powell Island Suite 085', 'West Johnside', 'Ghana', '41141', 'PERSONAL'),
('68f73287-0884-45a7-86ec-a715aa970e27', 53, '575 Williams Oval', 'Lake Kristine', 'Anguilla', '46434', 'OTHER'),
('0f8662f0-c12c-4699-9544-7d449309cb76', 54, '27473 Turner Valley', 'West Travis', 'Mozambique', '87477', 'PERSONAL'),
('c53e5dce-d52b-48a7-ac85-5d0dfafb11d3', 54, '80329 Mark Locks Apt. 657', 'West Denniston', 'Jordan', '58778', 'OTHER'),
('5821d3e1-1672-428f-8e5c-93848f2197c5', 55, '0185 Thomas Bypass', 'North Alexandramouth', 'Saint Kitts and Nevis', '19987', 'OTHER'),
('4f235a45-c303-41c9-b9d7-7a9944439463', 56, '342 Kristen Points Apt. 565', 'North Carlaberg', 'Gambia', '09393', 'PERSONAL'),
('9d5e99fc-9959-450c-986d-75bdd473b5d9', 57, '6582 Bates Extensions', 'East James', 'Saint Lucia', '59203', 'PERSONAL'),
('6c634b19-299d-4978-9a68-1ffe030a77fe', 57, '185 Carolyn Islands Suite 651', 'Hessland', 'Hong Kong', '09685', 'OTHER'),
('06676856-e776-4bae-86eb-55298e6f00a5', 58, '650 Simmons Summit Apt. 623', 'North Douglas', 'San Marino', '96862', 'PERSONAL'),
('8df0e691-1128-44ac-8e5f-06ceafa854c4', 58, '3312 Andrea Garden Apt. 246', 'Martinchester', 'Ireland', '08761', 'OTHER'),
('7da683c2-4ee7-459b-b66f-95649d9391d2', 59, '7477 Nicholas Burg', 'East Bruce', 'Fiji', '93710', 'PERSONAL'),
('9194e807-7bcf-4bee-9131-bfc88115a2fc', 60, '0686 Charles Rest Suite 458', 'East Devin', 'Angola', '30675', 'OTHER'),
('08c44b06-9a8d-4117-b71c-acf8ccee6ea5', 60, '56374 Kristen Point Apt. 285', 'Port Heatherview', 'Cook Islands', '60543', 'PERSONAL'),
('37c04d72-0b90-4a38-819b-d0ad314ff751', 61, '3241 Christopher Pike', 'Justinbury', 'Azerbaijan', '77424', 'PERSONAL'),
('796edc41-6f4f-49ae-a60f-43089391f36b', 62, '4349 Hoffman Streets', 'New Brian', 'Senegal', '81113', 'OTHER'),
('d2cef41c-b7d0-4db3-a12d-d724a30f6a28', 63, '281 Kyle Ville', 'New Aliciastad', 'Andorra', '19317', 'PERSONAL'),
('3489d1c4-1dc7-4898-b435-b4b2ff7dcf2f', 63, '33248 Steven Fords', 'Taylorborough', 'Belize', '36415', 'OTHER'),
('3344d927-2923-4695-9daa-eb0a82bd0365', 64, '43115 Smith Isle', 'Hopkinsmouth', 'Albania', '13415', 'PERSONAL'),
('74daa02f-c3ff-4b7c-af2a-ddadaca61c73', 65, '48052 Miller Passage Apt. 376', 'Lake Brittney', 'Thailand', '99217', 'PERSONAL'),
('575f8fa9-944a-4927-aa4c-634b23052951', 65, '538 Jonathan Knoll', 'Port Gerald', 'Lithuania', '24510', 'OTHER'),
('65e8c5b6-87e0-4307-aaea-b0ac24b03c61', 66, '133 Joshua Points', 'West Karenchester', 'Zambia', '14262', 'OTHER'),
('cc2601ff-d8f3-4483-954b-920538c4052d', 66, '80295 Kelly Street Apt. 497', 'Danielville', 'Armenia', '38412', 'PERSONAL'),
('babbb2a9-3485-4268-b770-d94ee6be181e', 67, '735 Mendez Underpass Suite 533', 'Ginastad', 'Nigeria', '92479', 'OTHER'),
('b3d75143-900f-4c49-934b-699efa0ebc7f', 68, '6543 Hughes Mills Apt. 627', 'New Jenna', 'Brunei Darussalam', '92044', 'OTHER'),
('a27f8b74-c081-49e6-a04d-8b593212984c', 69, '120 Dean Bypass', 'Cherylstad', 'Heard Island and McDonald Islands', '72129', 'PERSONAL'),
('2ee7ca15-da00-4e46-b997-0c976352aa75', 69, '07478 Perry Curve Apt. 432', 'West Megan', 'Indonesia', '75850', 'OTHER'),
('a75bc862-44fe-4b98-977b-6261163d10e3', 70, '01380 Melanie Wells Suite 024', 'West Darrylfort', 'Belize', '23387', 'OTHER');

-- Employee Contacts
INSERT INTO party_contact (party_id, type, details) VALUES
(51, 'EMAIL', 'novakryan@example.org'),
(51, 'PHONE', '832.408.6791'),
(52, 'EMAIL', 'uyang@example.com'),
(52, 'PHONE', '(476)686-1078x00376'),
(53, 'EMAIL', 'alicia05@example.org'),
(53, 'PHONE', '+1-863-403-5266x0202'),
(54, 'EMAIL', 'yyoder@example.net'),
(54, 'PHONE', '+1-344-770-5134x807'),
(55, 'EMAIL', 'howardveronica@example.net'),
(55, 'PHONE', '5522773493'),
(56, 'EMAIL', 'alicia60@example.net'),
(56, 'PHONE', '001-613-210-3413x5399'),
(57, 'EMAIL', 'donald15@example.net'),
(57, 'PHONE', '9978282561'),
(58, 'EMAIL', 'stevensonnicholas@example.com'),
(58, 'PHONE', '757.605.8159x81111'),
(59, 'EMAIL', 'gabrielfuller@example.com'),
(59, 'PHONE', '718.211.6092'),
(60, 'EMAIL', 'bburke@example.com'),
(60, 'PHONE', '(478)459-3225x17900'),
(61, 'EMAIL', 'carla81@example.org'),
(61, 'PHONE', '001-556-988-3094x4137'),
(62, 'EMAIL', 'kvaughn@example.net'),
(62, 'PHONE', '515-282-7764x4548'),
(63, 'EMAIL', 'debra45@example.org'),
(63, 'PHONE', '409.274.7310'),
(64, 'EMAIL', 'pamelaaustin@example.com'),
(64, 'PHONE', '(498)875-7509x5932'),
(65, 'EMAIL', 'peter59@example.com'),
(65, 'PHONE', '+1-607-325-6778x48262'),
(66, 'EMAIL', 'wfrench@example.net'),
(66, 'PHONE', '+1-443-500-9439x92944'),
(67, 'EMAIL', 'ralph37@example.org'),
(67, 'PHONE', '376-658-7466x650'),
(68, 'EMAIL', 'marquezkeith@example.org'),
(68, 'PHONE', '2067869177'),
(69, 'EMAIL', 'nnguyen@example.org'),
(69, 'PHONE', '646-466-5391x7605'),
(70, 'EMAIL', 'emorris@example.org'),
(70, 'PHONE', '480-617-3670x8117');

-- Party Roles
INSERT INTO party_role (party_id, role_id, assigned_date) VALUES
(51, 3, '2025-05-06 16:55:30'),
(52, 4, '2026-02-13 17:08:24'),
(53, 3, '2021-11-19 03:43:08'),
(54, 5, '2025-08-05 14:22:53'),
(54, 4, '2026-04-03 07:29:30'),
(55, 5, '2022-10-28 08:54:43'),
(56, 5, '2023-08-15 16:09:42'),
(57, 5, '2023-12-13 03:29:21'),
(57, 3, '2025-11-18 19:22:51'),
(58, 5, '2025-07-14 02:09:11'),
(59, 5, '2026-02-16 16:48:57'),
(59, 4, '2024-09-05 23:15:57'),
(60, 5, '2025-09-06 03:24:36'),
(61, 5, '2024-01-03 16:31:52'),
(62, 5, '2025-12-29 19:33:40'),
(63, 1, '2026-03-20 03:35:13'),
(64, 5, '2026-06-11 06:49:35'),
(65, 5, '2025-05-04 10:40:12'),
(66, 5, '2023-08-20 18:59:55'),
(66, 3, '2023-01-29 11:38:05'),
(67, 4, '2026-05-29 17:57:38'),
(68, 5, '2024-07-27 18:51:30'),
(69, 1, '2023-02-03 00:14:39'),
(70, 1, '2024-10-22 20:16:45');

-- Employee Warehouses
INSERT INTO employee_warehouse (party_id, warehouse_id, assigned_from, assigned_until) VALUES
(51, 1, '2024-05-09 06:11:54', NULL),
(52, 1, '2022-10-16 22:14:58', NULL),
(53, 1, '2021-10-10 23:41:01', NULL),
(54, 1, '2025-02-03 05:55:32', NULL),
(55, 1, '2022-03-17 14:05:34', NULL),
(56, 1, '2022-10-29 20:15:21', NULL),
(57, 1, '2023-06-02 02:22:23', NULL),
(58, 1, '2024-02-24 06:31:56', NULL),
(59, 1, '2024-08-22 06:17:40', NULL),
(60, 1, '2025-02-11 08:09:26', NULL),
(61, 1, '2021-09-16 23:30:25', NULL),
(62, 1, '2024-11-12 01:43:06', NULL),
(63, 1, '2022-09-20 06:03:20', NULL),
(64, 1, '2023-09-01 11:36:31', NULL),
(65, 1, '2025-02-05 17:52:38', NULL),
(66, 1, '2022-05-14 08:18:58', NULL),
(67, 1, '2022-09-29 12:18:58', NULL),
(68, 1, '2023-01-25 05:55:47', NULL),
(69, 1, '2022-08-19 16:09:29', NULL),
(70, 1, '2024-07-16 13:39:35', NULL);

-- Cargo Event Types
INSERT INTO cargo_event_type (event_type_id, name, description) VALUES
(1, 'RECEIVED', 'Cargo received at warehouse'),
(2, 'MOVED', 'Cargo moved to another shelf'),
(3, 'DISPATCHED', 'Cargo dispatched from warehouse'),
(4, 'DAMAGED', 'Cargo found damaged'),
(5, 'LOST', 'Cargo missing or lost'),
(6, 'CONTRACTOR_CONTACT', 'Contact with contractor regarding storage'),
(7, 'QUALITY_ISSUE', 'Quality-related issue reported'),
(8, 'SAFETY_INCIDENT', 'Safety or accident incident reported');

-- Zones
INSERT INTO zone (zone_id, warehouse_id, name, description) VALUES
(1, 1, 'Bulk Storage Area', 'Area for storing large quantities of goods, usually on pallets.'),
(2, 1, 'Receiving Area', 'Zone designated for unloading and inspecting incoming goods.'),
(3, 1, 'Picking Area', 'Zone where items are picked to fulfill orders.'),
(4, 1, 'Packing Area', 'Area for packing picked items and preparing them for shipment.'),
(5, 1, 'Shipping Area', 'Zone for staging and loading outbound shipments.'),
(6, 1, 'Returns Area', 'Designated space for processing returned goods.'),
(7, 1, 'Quarantine/Inspection Area', 'Area for holding goods pending inspection or quality checks.');

-- Aisles
INSERT INTO aisle (aisle_id, zone_id, label, width, width_unit) VALUES
(1, 1, 'Aisle-1', 250, 'cm'),
(2, 1, 'Aisle-2', 350, 'cm'),
(3, 1, 'Aisle-3', 250, 'cm'),
(4, 1, 'Aisle-4', 250, 'cm'),
(5, 1, 'Aisle-5', 200, 'cm'),
(6, 1, 'Aisle-6', 300, 'cm'),
(7, 1, 'Aisle-7', 250, 'cm');

-- Racks
INSERT INTO rack (rack_id, aisle_id, label, max_height, height_unit) VALUES
(1, 1, 'R-001', 450, 'cm'),
(2, 2, 'R-002', 400, 'cm'),
(3, 3, 'R-003', 450, 'cm'),
(4, 4, 'R-004', 400, 'cm'),
(5, 5, 'R-005', 450, 'cm'),
(6, 6, 'R-006', 500, 'cm'),
(7, 7, 'R-007', 400, 'cm'),
(8, 1, 'R-008', 400, 'cm'),
(9, 2, 'R-009', 350, 'cm'),
(10, 3, 'R-010', 500, 'cm');

-- Shelves
INSERT INTO shelf (shelf_id, rack_id, level, max_weight, max_volume) VALUES
(1, 1, '1', 909, 10),
(2, 2, '2', 1060, 7),
(3, 3, '3', 713, 15),
(4, 4, '4', 681, 10),
(5, 5, '1', 865, 6),
(6, 6, '2', 993, 12),
(7, 7, '3', 706, 9),
(8, 8, '4', 609, 6),
(9, 9, '1', 935, 15),
(10, 10, '2', 1148, 14),
(11, 1, '3', 1164, 13),
(12, 2, '4', 1026, 8),
(13, 3, '1', 1014, 7),
(14, 4, '2', 847, 9),
(15, 5, '3', 930, 15);

-- Storage Requests
INSERT INTO storage_request (request_id, warehouse_id, issuing_party_id, requested_entry_date, requested_exit_date, status, decisive_party_id, decision_date) VALUES
(1, 1, 114, '2026-06-19 22:51:47', '2026-06-27 22:51:47', 'REJECTED', 64, '2026-06-16 22:51:47'),
(2, 1, 23, '2026-07-09 04:32:11', '2026-07-17 04:32:11', 'PENDING', NULL, NULL),
(3, 1, 139, '2026-06-21 21:50:59', '2026-07-16 21:50:59', 'ACCEPTED', 65, '2026-06-19 21:50:59'),
(4, 1, 50, '2026-06-11 09:54:32', '2026-06-21 09:54:32', 'PENDING', NULL, NULL),
(5, 1, 98, '2026-06-16 00:35:01', '2026-07-11 00:35:01', 'ACCEPTED', 62, '2026-06-14 00:35:01'),
(6, 1, 117, '2026-07-17 04:20:17', '2026-08-11 04:20:17', 'PENDING', NULL, NULL),
(7, 1, 141, '2026-06-16 19:04:33', '2026-07-16 19:04:33', 'PENDING', NULL, NULL),
(8, 1, 34, '2026-06-14 21:27:34', '2026-07-10 21:27:34', 'PENDING', NULL, NULL),
(9, 1, 142, '2026-06-07 06:07:30', '2026-07-04 06:07:30', 'REJECTED', 59, '2026-06-04 06:07:30'),
(10, 1, 133, '2026-07-28 04:14:37', '2026-08-16 04:14:37', 'REJECTED', 61, '2026-07-27 04:14:37'),
(11, 1, 145, '2026-07-20 21:08:40', '2026-07-29 21:08:40', 'ACCEPTED', 51, '2026-07-16 21:08:40'),
(12, 1, 27, '2026-07-05 02:12:40', '2026-07-29 02:12:40', 'REJECTED', NULL, '2026-07-07 02:12:40'),
(13, 1, 102, '2026-07-27 12:52:39', '2026-08-02 12:52:39', 'REJECTED', NULL, '2026-07-28 12:52:39'),
(14, 1, 146, '2026-06-25 20:56:36', '2026-07-11 20:56:36', 'ACCEPTED', 53, '2026-06-22 20:56:36'),
(15, 1, 100, '2026-06-23 20:48:22', '2026-07-02 20:48:22', 'ACCEPTED', 55, '2026-06-22 20:48:22'),
(16, 1, 130, '2026-06-18 15:33:21', '2026-07-08 15:33:21', 'PENDING', NULL, NULL),
(17, 1, 114, '2026-06-16 15:41:41', '2026-07-06 15:41:41', 'REJECTED', NULL, '2026-06-18 15:41:41'),
(18, 1, 47, '2026-06-12 02:05:19', '2026-07-01 02:05:19', 'REJECTED', NULL, '2026-06-13 02:05:19'),
(19, 1, 36, '2026-08-01 16:23:30', '2026-08-18 16:23:30', 'REJECTED', 56, '2026-07-29 16:23:30'),
(20, 1, 12, '2026-06-07 21:02:06', '2026-06-20 21:02:06', 'ACCEPTED', 70, '2026-06-05 21:02:06'),
(21, 1, 2, '2026-06-24 18:57:40', '2026-06-29 18:57:40', 'ACCEPTED', 65, '2026-06-21 18:57:40'),
(22, 1, 32, '2026-06-10 00:37:52', '2026-07-02 00:37:52', 'ACCEPTED', 55, '2026-06-05 00:37:52'),
(23, 1, 95, '2026-06-18 10:02:35', '2026-07-02 10:02:35', 'ACCEPTED', 68, '2026-06-17 10:02:35'),
(24, 1, 137, '2026-07-25 07:28:24', '2026-08-04 07:28:24', 'REJECTED', NULL, '2026-07-26 07:28:24'),
(25, 1, 83, '2026-06-06 07:59:45', '2026-06-25 07:59:45', 'PENDING', NULL, NULL),
(26, 1, 19, '2026-06-18 02:02:41', '2026-07-02 02:02:41', 'REJECTED', 51, '2026-06-15 02:02:41'),
(27, 1, 135, '2026-07-22 15:30:56', '2026-08-21 15:30:56', 'REJECTED', 60, '2026-07-20 15:30:56'),
(28, 1, 28, '2026-07-14 18:36:29', '2026-07-22 18:36:29', 'PENDING', NULL, NULL),
(29, 1, 123, '2026-07-25 08:44:32', '2026-08-08 08:44:32', 'ACCEPTED', 53, '2026-07-22 08:44:32'),
(30, 1, 32, '2026-06-28 00:07:38', '2026-07-28 00:07:38', 'PENDING', NULL, NULL),
(31, 1, 1, '2026-07-21 22:43:18', '2026-08-04 22:43:18', 'ACCEPTED', 60, '2026-07-18 22:43:18'),
(32, 1, 44, '2026-07-08 23:09:23', '2026-08-04 23:09:23', 'REJECTED', 55, '2026-07-07 23:09:23'),
(33, 1, 112, '2026-06-30 20:29:42', '2026-07-17 20:29:42', 'PENDING', NULL, NULL),
(34, 1, 96, '2026-07-16 13:45:52', '2026-08-12 13:45:52', 'ACCEPTED', 70, '2026-07-15 13:45:52'),
(35, 1, 13, '2026-06-10 18:13:02', '2026-07-06 18:13:02', 'ACCEPTED', 52, '2026-06-05 18:13:02'),
(36, 1, 87, '2026-07-03 14:43:10', '2026-07-29 14:43:10', 'REJECTED', 57, '2026-07-01 14:43:10'),
(37, 1, 40, '2026-06-13 12:03:48', '2026-06-25 12:03:48', 'ACCEPTED', 53, '2026-06-11 12:03:48'),
(38, 1, 85, '2026-06-27 23:05:34', '2026-07-09 23:05:34', 'REJECTED', NULL, '2026-06-29 23:05:34'),
(39, 1, 38, '2026-08-01 04:07:08', '2026-08-22 04:07:08', 'PENDING', NULL, NULL),
(40, 1, 39, '2026-07-29 06:40:04', '2026-08-12 06:40:04', 'PENDING', NULL, NULL),
(41, 1, 110, '2026-06-26 00:45:24', '2026-07-20 00:45:24', 'PENDING', NULL, NULL),
(42, 1, 46, '2026-07-22 05:36:51', '2026-08-14 05:36:51', 'REJECTED', 68, '2026-07-21 05:36:51'),
(43, 1, 6, '2026-07-12 13:26:34', '2026-08-10 13:26:34', 'PENDING', NULL, NULL),
(44, 1, 45, '2026-06-05 03:40:20', '2026-06-16 03:40:20', 'PENDING', NULL, NULL),
(45, 1, 21, '2026-07-15 07:41:23', '2026-07-23 07:41:23', 'ACCEPTED', 63, '2026-07-14 07:41:23'),
(46, 1, 119, '2026-06-17 18:24:47', '2026-07-03 18:24:47', 'ACCEPTED', 63, '2026-06-15 18:24:47'),
(47, 1, 90, '2026-06-05 08:15:51', '2026-06-20 08:15:51', 'REJECTED', NULL, '2026-06-06 08:15:51'),
(48, 1, 113, '2026-06-13 09:07:40', '2026-07-02 09:07:40', 'PENDING', NULL, NULL),
(49, 1, 118, '2026-07-07 18:29:26', '2026-07-25 18:29:26', 'REJECTED', 65, '2026-07-05 18:29:26'),
(50, 1, 113, '2026-06-12 00:54:14', '2026-07-07 00:54:14', 'PENDING', NULL, NULL),
(51, 1, 93, '2026-06-17 05:11:41', '2026-07-05 05:11:41', 'ACCEPTED', 65, '2026-06-12 05:11:41'),
(52, 1, 129, '2026-07-02 20:45:51', '2026-07-23 20:45:51', 'REJECTED', 52, '2026-07-01 20:45:51'),
(53, 1, 14, '2026-06-23 04:25:19', '2026-07-08 04:25:19', 'PENDING', NULL, NULL),
(54, 1, 85, '2026-06-30 12:34:15', '2026-07-10 12:34:15', 'REJECTED', 61, '2026-06-28 12:34:15'),
(55, 1, 37, '2026-07-03 12:56:27', '2026-07-24 12:56:27', 'REJECTED', NULL, '2026-07-03 12:56:27'),
(56, 1, 40, '2026-07-20 19:42:03', '2026-08-09 19:42:03', 'PENDING', NULL, NULL),
(57, 1, 134, '2026-07-01 01:42:22', '2026-07-19 01:42:22', 'REJECTED', NULL, '2026-07-02 01:42:22'),
(58, 1, 113, '2026-07-07 11:18:09', '2026-08-05 11:18:09', 'PENDING', NULL, NULL),
(59, 1, 25, '2026-06-10 01:03:04', '2026-06-15 01:03:04', 'REJECTED', 66, '2026-06-07 01:03:04'),
(60, 1, 73, '2026-07-16 10:08:48', '2026-08-03 10:08:48', 'ACCEPTED', 51, '2026-07-13 10:08:48'),
(61, 1, 140, '2026-06-28 11:14:15', '2026-07-04 11:14:15', 'ACCEPTED', 58, '2026-06-25 11:14:15'),
(62, 1, 42, '2026-07-17 10:42:49', '2026-08-02 10:42:49', 'REJECTED', 56, '2026-07-14 10:42:49'),
(63, 1, 15, '2026-06-16 22:05:11', '2026-06-24 22:05:11', 'REJECTED', 55, '2026-06-13 22:05:11'),
(64, 1, 34, '2026-06-23 03:34:46', '2026-07-12 03:34:46', 'REJECTED', 64, '2026-06-22 03:34:46'),
(65, 1, 145, '2026-06-15 13:35:37', '2026-06-30 13:35:37', 'PENDING', NULL, NULL),
(66, 1, 104, '2026-06-30 10:43:24', '2026-07-09 10:43:24', 'REJECTED', 69, '2026-06-29 10:43:24'),
(67, 1, 40, '2026-06-06 14:51:46', '2026-06-25 14:51:46', 'ACCEPTED', 64, '2026-06-03 14:51:46'),
(68, 1, 74, '2026-07-28 22:09:43', '2026-08-27 22:09:43', 'ACCEPTED', 64, '2026-07-25 22:09:43'),
(69, 1, 119, '2026-06-05 10:26:25', '2026-06-22 10:26:25', 'ACCEPTED', 54, '2026-05-31 10:26:25'),
(70, 1, 6, '2026-07-04 21:42:23', '2026-07-16 21:42:23', 'ACCEPTED', 61, '2026-07-03 21:42:23'),
(71, 1, 23, '2026-06-09 05:33:41', '2026-06-21 05:33:41', 'PENDING', NULL, NULL),
(72, 1, 18, '2026-06-29 12:17:35', '2026-07-13 12:17:35', 'REJECTED', NULL, '2026-06-29 12:17:35'),
(73, 1, 39, '2026-06-12 23:14:07', '2026-06-22 23:14:07', 'ACCEPTED', 58, '2026-06-11 23:14:07'),
(74, 1, 72, '2026-06-19 23:52:51', '2026-07-16 23:52:51', 'ACCEPTED', 70, '2026-06-16 23:52:51'),
(75, 1, 45, '2026-07-20 18:15:28', '2026-08-08 18:15:28', 'ACCEPTED', 58, '2026-07-18 18:15:28'),
(76, 1, 74, '2026-06-15 22:48:14', '2026-07-10 22:48:14', 'PENDING', NULL, NULL),
(77, 1, 33, '2026-06-22 09:07:18', '2026-07-10 09:07:18', 'ACCEPTED', 61, '2026-06-18 09:07:18'),
(78, 1, 77, '2026-06-15 00:03:59', '2026-07-03 00:03:59', 'ACCEPTED', 62, '2026-06-12 00:03:59'),
(79, 1, 22, '2026-07-14 17:24:56', '2026-07-26 17:24:56', 'ACCEPTED', 61, '2026-07-10 17:24:56'),
(80, 1, 20, '2026-07-07 19:18:16', '2026-07-28 19:18:16', 'ACCEPTED', 68, '2026-07-02 19:18:16'),
(81, 1, 143, '2026-06-22 04:05:11', '2026-07-11 04:05:11', 'PENDING', NULL, NULL),
(82, 1, 104, '2026-07-16 22:29:53', '2026-08-06 22:29:53', 'REJECTED', 65, '2026-07-14 22:29:53'),
(83, 1, 15, '2026-06-24 18:07:10', '2026-07-11 18:07:10', 'PENDING', NULL, NULL),
(84, 1, 146, '2026-06-09 02:49:58', '2026-07-01 02:49:58', 'REJECTED', NULL, '2026-06-11 02:49:58'),
(85, 1, 2, '2026-06-21 08:28:54', '2026-07-15 08:28:54', 'PENDING', NULL, NULL),
(86, 1, 41, '2026-06-16 06:20:42', '2026-06-23 06:20:42', 'ACCEPTED', 61, '2026-06-13 06:20:42'),
(87, 1, 130, '2026-06-10 11:27:35', '2026-07-06 11:27:35', 'PENDING', NULL, NULL),
(88, 1, 16, '2026-07-26 03:45:16', '2026-08-20 03:45:16', 'ACCEPTED', 67, '2026-07-25 03:45:16'),
(89, 1, 141, '2026-06-27 04:38:09', '2026-07-14 04:38:09', 'PENDING', NULL, NULL),
(90, 1, 124, '2026-06-06 20:06:36', '2026-07-02 20:06:36', 'PENDING', NULL, NULL),
(91, 1, 83, '2026-07-26 21:46:16', '2026-08-09 21:46:16', 'PENDING', NULL, NULL),
(92, 1, 30, '2026-06-28 20:14:21', '2026-07-06 20:14:21', 'ACCEPTED', 60, '2026-06-23 20:14:21'),
(93, 1, 44, '2026-06-17 08:36:33', '2026-07-02 08:36:33', 'ACCEPTED', 67, '2026-06-12 08:36:33'),
(94, 1, 136, '2026-06-14 04:41:39', '2026-06-28 04:41:39', 'PENDING', NULL, NULL),
(95, 1, 148, '2026-06-11 06:23:43', '2026-07-10 06:23:43', 'REJECTED', 62, '2026-06-10 06:23:43'),
(96, 1, 9, '2026-07-19 15:48:14', '2026-08-14 15:48:14', 'ACCEPTED', 53, '2026-07-14 15:48:14'),
(97, 1, 128, '2026-06-19 14:51:30', '2026-07-07 14:51:30', 'REJECTED', 55, '2026-06-17 14:51:30'),
(98, 1, 111, '2026-06-17 10:50:58', '2026-07-06 10:50:58', 'PENDING', NULL, NULL),
(99, 1, 95, '2026-07-05 07:37:24', '2026-07-19 07:37:24', 'REJECTED', 70, '2026-07-03 07:37:24'),
(100, 1, 72, '2026-07-26 15:47:05', '2026-08-13 15:47:05', 'ACCEPTED', 62, '2026-07-25 15:47:05'),
(101, 1, 96, '2026-06-18 07:56:14', '2026-07-04 07:56:14', 'REJECTED', NULL, '2026-06-18 07:56:14'),
(102, 1, 23, '2026-07-13 14:37:42', '2026-07-20 14:37:42', 'ACCEPTED', 58, '2026-07-11 14:37:42'),
(103, 1, 106, '2026-06-26 00:34:52', '2026-07-23 00:34:52', 'PENDING', NULL, NULL),
(104, 1, 71, '2026-06-19 18:28:09', '2026-07-12 18:28:09', 'PENDING', NULL, NULL),
(105, 1, 91, '2026-07-31 19:29:58', '2026-08-23 19:29:58', 'PENDING', NULL, NULL),
(106, 1, 139, '2026-06-14 16:17:08', '2026-07-13 16:17:08', 'ACCEPTED', 51, '2026-06-12 16:17:08'),
(107, 1, 96, '2026-06-13 07:32:23', '2026-06-29 07:32:23', 'PENDING', NULL, NULL),
(108, 1, 138, '2026-07-16 16:53:55', '2026-07-26 16:53:55', 'PENDING', NULL, NULL),
(109, 1, 37, '2026-07-30 04:46:12', '2026-08-25 04:46:12', 'ACCEPTED', 52, '2026-07-29 04:46:12'),
(110, 1, 106, '2026-06-14 14:28:34', '2026-06-20 14:28:34', 'PENDING', NULL, NULL),
(111, 1, 74, '2026-07-17 07:51:15', '2026-08-09 07:51:15', 'PENDING', NULL, NULL),
(112, 1, 85, '2026-07-12 12:26:10', '2026-07-24 12:26:10', 'REJECTED', 60, '2026-07-10 12:26:10'),
(113, 1, 80, '2026-07-07 23:13:28', '2026-07-15 23:13:28', 'ACCEPTED', 57, '2026-07-05 23:13:28'),
(114, 1, 112, '2026-06-08 04:47:08', '2026-06-29 04:47:08', 'PENDING', NULL, NULL),
(115, 1, 75, '2026-06-15 06:11:20', '2026-07-06 06:11:20', 'ACCEPTED', 56, '2026-06-11 06:11:20'),
(116, 1, 29, '2026-07-07 18:17:26', '2026-08-01 18:17:26', 'PENDING', NULL, NULL),
(117, 1, 26, '2026-06-25 11:15:49', '2026-07-23 11:15:49', 'REJECTED', 70, '2026-06-24 11:15:49'),
(118, 1, 129, '2026-07-07 15:52:16', '2026-08-02 15:52:16', 'PENDING', NULL, NULL),
(119, 1, 135, '2026-06-23 11:11:53', '2026-07-06 11:11:53', 'REJECTED', 60, '2026-06-21 11:11:53'),
(120, 1, 124, '2026-06-19 18:33:47', '2026-07-08 18:33:47', 'REJECTED', NULL, '2026-06-19 18:33:47'),
(121, 1, 96, '2026-06-04 09:57:07', '2026-06-16 09:57:07', 'ACCEPTED', 62, '2026-06-01 09:57:07'),
(122, 1, 32, '2026-06-07 22:08:37', '2026-06-16 22:08:37', 'REJECTED', 54, '2026-06-05 22:08:37'),
(123, 1, 91, '2026-06-03 10:57:07', '2026-06-22 10:57:07', 'ACCEPTED', 62, '2026-05-31 10:57:07'),
(124, 1, 114, '2026-06-12 00:57:33', '2026-06-27 00:57:33', 'PENDING', NULL, NULL),
(125, 1, 49, '2026-06-14 11:11:54', '2026-07-12 11:11:54', 'REJECTED', NULL, '2026-06-15 11:11:54'),
(126, 1, 128, '2026-07-04 17:42:24', '2026-07-15 17:42:24', 'ACCEPTED', 52, '2026-06-30 17:42:24'),
(127, 1, 2, '2026-06-08 21:53:34', '2026-06-17 21:53:34', 'ACCEPTED', 68, '2026-06-06 21:53:34'),
(128, 1, 77, '2026-07-12 06:16:36', '2026-08-04 06:16:36', 'PENDING', NULL, NULL),
(129, 1, 79, '2026-07-13 07:48:05', '2026-08-12 07:48:05', 'PENDING', NULL, NULL),
(130, 1, 41, '2026-07-08 06:26:45', '2026-07-13 06:26:45', 'REJECTED', 68, '2026-07-05 06:26:45'),
(131, 1, 75, '2026-07-15 20:12:06', '2026-07-30 20:12:06', 'ACCEPTED', 57, '2026-07-12 20:12:06'),
(132, 1, 129, '2026-06-21 21:36:30', '2026-06-28 21:36:30', 'PENDING', NULL, NULL),
(133, 1, 35, '2026-07-16 20:49:52', '2026-08-03 20:49:52', 'REJECTED', NULL, '2026-07-18 20:49:52'),
(134, 1, 42, '2026-07-21 13:26:48', '2026-07-28 13:26:48', 'REJECTED', NULL, '2026-07-23 13:26:48'),
(135, 1, 34, '2026-07-30 20:05:55', '2026-08-24 20:05:55', 'PENDING', NULL, NULL),
(136, 1, 142, '2026-06-08 02:49:14', '2026-06-23 02:49:14', 'PENDING', NULL, NULL),
(137, 1, 7, '2026-07-26 19:12:24', '2026-08-23 19:12:24', 'REJECTED', NULL, '2026-07-26 19:12:24'),
(138, 1, 43, '2026-07-22 17:14:32', '2026-08-15 17:14:32', 'PENDING', NULL, NULL),
(139, 1, 105, '2026-07-26 23:24:04', '2026-08-05 23:24:04', 'PENDING', NULL, NULL),
(140, 1, 126, '2026-06-18 05:18:47', '2026-06-27 05:18:47', 'REJECTED', NULL, '2026-06-18 05:18:47'),
(141, 1, 126, '2026-06-25 16:42:54', '2026-07-24 16:42:54', 'REJECTED', 60, '2026-06-22 16:42:54'),
(142, 1, 88, '2026-07-16 19:05:59', '2026-07-23 19:05:59', 'REJECTED', 65, '2026-07-13 19:05:59'),
(143, 1, 17, '2026-06-10 01:56:03', '2026-07-09 01:56:03', 'ACCEPTED', 54, '2026-06-09 01:56:03'),
(144, 1, 21, '2026-06-17 08:51:11', '2026-07-09 08:51:11', 'PENDING', NULL, NULL),
(145, 1, 11, '2026-07-26 17:14:31', '2026-08-09 17:14:31', 'ACCEPTED', 58, '2026-07-22 17:14:31'),
(146, 1, 19, '2026-07-17 20:27:21', '2026-08-16 20:27:21', 'REJECTED', 61, '2026-07-15 20:27:21'),
(147, 1, 113, '2026-07-20 16:58:44', '2026-08-13 16:58:44', 'REJECTED', 61, '2026-07-18 16:58:44'),
(148, 1, 134, '2026-07-11 04:59:47', '2026-08-06 04:59:47', 'PENDING', NULL, NULL),
(149, 1, 106, '2026-07-01 05:44:17', '2026-07-19 05:44:17', 'ACCEPTED', 64, '2026-06-26 05:44:17'),
(150, 1, 29, '2026-07-29 10:21:28', '2026-08-25 10:21:28', 'ACCEPTED', 55, '2026-07-24 10:21:28'),
(151, 1, 89, '2026-07-22 03:37:23', '2026-08-10 03:37:23', 'PENDING', NULL, NULL),
(152, 1, 36, '2026-07-03 03:45:23', '2026-07-28 03:45:23', 'REJECTED', 57, '2026-07-01 03:45:23'),
(153, 1, 79, '2026-07-21 08:09:39', '2026-08-02 08:09:39', 'ACCEPTED', 51, '2026-07-20 08:09:39'),
(154, 1, 35, '2026-07-02 23:58:41', '2026-07-23 23:58:41', 'PENDING', NULL, NULL),
(155, 1, 34, '2026-06-24 16:15:11', '2026-07-20 16:15:11', 'ACCEPTED', 60, '2026-06-21 16:15:11'),
(156, 1, 115, '2026-07-24 09:01:36', '2026-08-06 09:01:36', 'ACCEPTED', 66, '2026-07-21 09:01:36'),
(157, 1, 33, '2026-07-28 20:44:53', '2026-08-23 20:44:53', 'ACCEPTED', 68, '2026-07-23 20:44:53'),
(158, 1, 138, '2026-07-12 06:17:10', '2026-08-01 06:17:10', 'ACCEPTED', 58, '2026-07-11 06:17:10'),
(159, 1, 29, '2026-07-20 06:35:58', '2026-08-08 06:35:58', 'ACCEPTED', 54, '2026-07-18 06:35:58'),
(160, 1, 146, '2026-07-15 00:41:33', '2026-07-29 00:41:33', 'PENDING', NULL, NULL),
(161, 1, 111, '2026-06-18 15:28:05', '2026-07-01 15:28:05', 'PENDING', NULL, NULL),
(162, 1, 47, '2026-06-09 15:02:36', '2026-07-09 15:02:36', 'PENDING', NULL, NULL),
(163, 1, 148, '2026-07-18 09:57:06', '2026-08-04 09:57:06', 'PENDING', NULL, NULL),
(164, 1, 49, '2026-07-24 18:00:54', '2026-08-13 18:00:54', 'REJECTED', NULL, '2026-07-25 18:00:54'),
(165, 1, 101, '2026-07-27 22:20:41', '2026-08-17 22:20:41', 'REJECTED', 61, '2026-07-24 22:20:41'),
(166, 1, 16, '2026-07-18 03:09:02', '2026-08-16 03:09:02', 'PENDING', NULL, NULL),
(167, 1, 117, '2026-06-14 20:50:12', '2026-07-03 20:50:12', 'ACCEPTED', 69, '2026-06-13 20:50:12'),
(168, 1, 106, '2026-07-09 11:05:44', '2026-07-24 11:05:44', 'ACCEPTED', 70, '2026-07-06 11:05:44'),
(169, 1, 1, '2026-07-20 12:20:25', '2026-08-03 12:20:25', 'PENDING', NULL, NULL),
(170, 1, 72, '2026-07-01 18:36:06', '2026-07-28 18:36:06', 'ACCEPTED', 53, '2026-06-27 18:36:06'),
(171, 1, 108, '2026-06-15 23:15:47', '2026-06-25 23:15:47', 'ACCEPTED', 58, '2026-06-12 23:15:47'),
(172, 1, 49, '2026-06-03 11:45:14', '2026-06-30 11:45:14', 'PENDING', NULL, NULL),
(173, 1, 83, '2026-07-02 03:31:25', '2026-07-08 03:31:25', 'REJECTED', NULL, '2026-07-02 03:31:25'),
(174, 1, 112, '2026-06-23 18:48:28', '2026-07-10 18:48:28', 'REJECTED', 63, '2026-06-21 18:48:28'),
(175, 1, 135, '2026-06-04 16:27:48', '2026-06-13 16:27:48', 'REJECTED', 56, '2026-06-03 16:27:48'),
(176, 1, 11, '2026-07-05 16:47:33', '2026-07-28 16:47:33', 'PENDING', NULL, NULL),
(177, 1, 47, '2026-06-30 09:45:11', '2026-07-11 09:45:11', 'REJECTED', 68, '2026-06-28 09:45:11'),
(178, 1, 28, '2026-06-21 00:00:49', '2026-07-07 00:00:49', 'ACCEPTED', 58, '2026-06-19 00:00:49'),
(179, 1, 50, '2026-06-03 01:00:13', '2026-06-16 01:00:13', 'ACCEPTED', 54, '2026-05-29 01:00:13'),
(180, 1, 146, '2026-07-14 23:21:28', '2026-07-23 23:21:28', 'ACCEPTED', 64, '2026-07-13 23:21:28'),
(181, 1, 128, '2026-07-03 17:31:42', '2026-08-02 17:31:42', 'REJECTED', 67, '2026-06-30 17:31:42'),
(182, 1, 80, '2026-07-25 03:13:09', '2026-08-13 03:13:09', 'REJECTED', NULL, '2026-07-26 03:13:09'),
(183, 1, 106, '2026-06-04 04:07:55', '2026-06-25 04:07:55', 'ACCEPTED', 59, '2026-05-31 04:07:55'),
(184, 1, 145, '2026-07-20 00:00:07', '2026-08-10 00:00:07', 'ACCEPTED', 70, '2026-07-17 00:00:07'),
(185, 1, 102, '2026-06-14 21:17:55', '2026-07-10 21:17:55', 'REJECTED', NULL, '2026-06-15 21:17:55'),
(186, 1, 138, '2026-06-03 22:40:29', '2026-06-20 22:40:29', 'PENDING', NULL, NULL),
(187, 1, 32, '2026-06-03 13:36:05', '2026-06-18 13:36:05', 'PENDING', NULL, NULL),
(188, 1, 115, '2026-07-01 04:26:46', '2026-07-26 04:26:46', 'REJECTED', 57, '2026-06-30 04:26:46'),
(189, 1, 6, '2026-06-20 08:00:15', '2026-07-14 08:00:15', 'REJECTED', 55, '2026-06-17 08:00:15'),
(190, 1, 110, '2026-06-24 03:45:28', '2026-06-30 03:45:28', 'REJECTED', 58, '2026-06-22 03:45:28'),
(191, 1, 96, '2026-06-23 08:11:51', '2026-07-01 08:11:51', 'ACCEPTED', 54, '2026-06-22 08:11:51'),
(192, 1, 131, '2026-06-20 06:22:31', '2026-07-19 06:22:31', 'PENDING', NULL, NULL),
(193, 1, 27, '2026-07-26 19:09:09', '2026-08-04 19:09:09', 'PENDING', NULL, NULL),
(194, 1, 31, '2026-06-30 00:56:13', '2026-07-29 00:56:13', 'ACCEPTED', 64, '2026-06-25 00:56:13'),
(195, 1, 9, '2026-06-10 13:28:59', '2026-07-03 13:28:59', 'ACCEPTED', 68, '2026-06-09 13:28:59'),
(196, 1, 19, '2026-06-30 20:24:42', '2026-07-20 20:24:42', 'REJECTED', 69, '2026-06-29 20:24:42'),
(197, 1, 86, '2026-06-23 17:18:03', '2026-07-13 17:18:03', 'ACCEPTED', 62, '2026-06-19 17:18:03'),
(198, 1, 89, '2026-07-06 05:36:10', '2026-07-25 05:36:10', 'ACCEPTED', 63, '2026-07-05 05:36:10'),
(199, 1, 12, '2026-06-23 08:53:36', '2026-06-30 08:53:36', 'REJECTED', 68, '2026-06-22 08:53:36'),
(200, 1, 127, '2026-07-11 17:31:02', '2026-08-08 17:31:02', 'REJECTED', 57, '2026-07-09 17:31:02');

-- Storage Reservations
INSERT INTO storage_reservation (reservation_id, request_id, party_id, shelf_id, reserved_weight, reserved_volume, reserved_from, reserved_until, status) VALUES
(4, 14, 146, 11, 100.73, 7.8, '2026-06-25 20:56:36', '2026-07-11 20:56:36', 'PENDING'),
(15, 45, 21, 13, 485.54, 6.77, '2026-07-15 07:41:23', '2026-07-23 07:41:23', 'EXPIRED'),
(17, 51, 93, 1, 951.14, 5.7, '2026-06-17 05:11:41', '2026-07-05 05:11:41', 'ACTIVE'),
(18, 60, 73, 9, 476.76, 9.04, '2026-07-16 10:08:48', '2026-08-03 10:08:48', 'ACTIVE'),
(33, 92, 30, 4, 624.28, 2.81, '2026-06-28 20:14:21', '2026-07-06 20:14:21', 'CANCELLED'),
(36, 100, 72, 14, 476.5, 9.19, '2026-07-26 15:47:05', '2026-08-13 15:47:05', 'ACTIVE'),
(37, 102, 23, 1, 946.76, 3.58, '2026-07-13 14:37:42', '2026-07-20 14:37:42', 'PENDING'),
(40, 113, 80, 5, 260.76, 9.02, '2026-07-07 23:13:28', '2026-07-15 23:13:28', 'ACTIVE'),
(41, 115, 75, 8, 978.05, 4.4, '2026-06-15 06:11:20', '2026-07-06 06:11:20', 'ACTIVE'),
(42, 121, 96, 11, 829.88, 9.46, '2026-06-04 09:57:07', '2026-06-16 09:57:07', 'PENDING'),
(43, 123, 91, 14, 794.49, 6.97, '2026-06-03 10:57:07', '2026-06-22 10:57:07', 'CANCELLED'),
(49, 149, 106, 14, 676.03, 5.3, '2026-07-01 05:44:17', '2026-07-19 05:44:17', 'PENDING'),
(52, 155, 34, 2, 465.12, 7.26, '2026-06-24 16:15:11', '2026-07-20 16:15:11', 'CANCELLED'),
(53, 156, 115, 4, 785.7, 6.06, '2026-07-24 09:01:36', '2026-08-06 09:01:36', 'EXPIRED'),
(60, 171, 108, 14, 454.37, 7.32, '2026-06-15 23:15:47', '2026-06-25 23:15:47', 'ACTIVE'),
(63, 180, 146, 12, 178.84, 6.73, '2026-07-14 23:21:28', '2026-07-23 23:21:28', 'PENDING'),
(66, 191, 96, 2, 610.41, 1.28, '2026-06-23 08:11:51', '2026-07-01 08:11:51', 'EXPIRED'),
(70, 198, 89, 4, 588.23, 4.51, '2026-07-06 05:36:10', '2026-07-25 05:36:10', 'PENDING');

-- Storage Records
INSERT INTO storage_record (storage_record_id, request_id, party_id, shelf_id, actual_entry_date, actual_exit_date, cargo_description, cargo_weight, cargo_volume) VALUES
(1, 14, 146, 11, '2026-06-25 20:56:36', NULL, 'Base fall establish.', 220.61, 5.67),
(2, 45, 21, 13, '2026-07-15 07:41:23', NULL, 'Bring smile gas manage key.', 207.74, 4.94),
(3, 51, 93, 1, '2026-06-17 05:11:41', NULL, 'Ahead ago effort.', 495.09, 3.97),
(4, 60, 73, 9, '2026-07-16 10:08:48', NULL, 'Popular right role onto.', 659.56, 7.03),
(5, 92, 30, 4, '2026-06-28 20:14:21', '2026-07-07 20:14:21', 'Case many.', 530.24, 1.92),
(6, 100, 72, 14, '2026-07-26 15:47:05', NULL, 'Possible who wall science.', 746.63, 4.53),
(7, 102, 23, 1, '2026-07-13 14:37:42', '2026-07-19 14:37:42', 'Inside whose fly might.', 569.21, 3.73),
(8, 113, 80, 5, '2026-07-07 23:13:28', '2026-07-10 23:13:28', 'Mean bar standard.', 203.15, 6.7),
(9, 115, 75, 8, '2026-06-15 06:11:20', '2026-06-18 06:11:20', 'Summer mind somebody special less.', 619.63, 6.07),
(10, 121, 96, 11, '2026-06-04 09:57:07', NULL, 'Sign single open see.', 540.61, 7.49),
(11, 123, 91, 14, '2026-06-03 10:57:07', '2026-06-07 10:57:07', 'Benefit even.', 293.63, 1.03),
(12, 149, 106, 14, '2026-07-01 05:44:17', '2026-07-05 05:44:17', 'Animal perhaps have.', 409.25, 1.3),
(13, 155, 34, 2, '2026-06-24 16:15:11', '2026-07-04 16:15:11', 'Something ball democratic join.', 258.51, 5.07),
(14, 156, 115, 4, '2026-07-24 09:01:36', NULL, 'Trade serious.', 239.75, 1.26),
(15, 171, 108, 14, '2026-06-15 23:15:47', NULL, 'Language of culture.', 620.6, 3.72),
(16, 180, 146, 12, '2026-07-14 23:21:28', NULL, 'Agent grow finally together.', 876.31, 1.74),
(17, 191, 96, 2, '2026-06-23 08:11:51', NULL, 'Build president role.', 845.57, 5.53),
(18, 198, 89, 4, '2026-07-06 05:36:10', NULL, 'Time address hit.', 656.58, 5.77);

-- Cargo Event History
INSERT INTO cargo_event_history (event_id, party_id, storage_record_id, event_type_id, event_time, details) VALUES
(1, 63, 1, 1, '2026-06-30 05:47:49', '{"note": "Effort which item another base economic evidence.", "performed_by": "Kristen Hernandez", "location": "foreign"}'::jsonb),
(2, 60, 2, 2, '2026-06-28 09:39:29', '{"note": "Son though gun particular hear yes.", "performed_by": "Robert Johnson", "location": "type"}'::jsonb),
(3, 51, 3, 3, '2026-06-12 21:24:36', '{"note": "Now guess step significant husband.", "performed_by": "Christina Roberts", "location": "seem"}'::jsonb),
(4, 61, 4, 4, '2026-06-18 22:59:09', '{"note": "Major how be.", "performed_by": "Chelsea Spencer", "location": "everything"}'::jsonb);

-- Payments
INSERT INTO payment (payment_id, storage_record_id, party_id, amount, currency, status, payment_date, external_reference) VALUES
(1, 1, 72, 1455.14, 'EUR', 'PAID', '2026-06-16 05:42:51', 'PAY-20260702-0001'),
(2, 2, 84, 1789.94, 'EUR', 'FAILED', '2026-06-30 18:02:00', 'PAY-20260702-0002'),
(3, 3, 40, 1607.97, 'USD', 'CANCELLED', '2026-06-06 10:29:14', 'PAY-20260702-0003'),
(4, 4, 39, 697.84, 'EUR', 'FAILED', '2026-06-15 07:14:18', 'PAY-20260702-0004'),
(5, 5, 125, 1069.54, 'PLN', 'FAILED', '2026-06-12 18:15:06', 'PAY-20260702-0005'),
(6, 6, 130, 1829.07, 'EUR', 'PAID', '2026-06-16 09:16:57', 'PAY-20260702-0006'),
(7, 7, 85, 1676.21, 'USD', 'FAILED', '2026-07-02 12:28:47', 'PAY-20260702-0007'),
(8, 8, 48, 1965.93, 'EUR', 'FAILED', '2026-06-28 17:29:53', 'PAY-20260702-0008'),
(9, 9, 82, 1636.06, 'USD', 'PAID', '2026-06-05 14:16:37', 'PAY-20260702-0009'),
(10, 10, 13, 1030.8, 'EUR', 'PAID', '2026-06-24 03:38:47', 'PAY-20260702-0010'),
(11, 11, 124, 1278.7, 'PLN', 'FAILED', '2026-06-10 14:33:21', 'PAY-20260702-0011'),
(12, 12, 138, 1994.1, 'EUR', 'PENDING', NULL, 'PAY-20260702-0012'),
(13, 13, 23, 1025.76, 'EUR', 'CANCELLED', '2026-06-25 06:35:53', 'PAY-20260702-0013'),
(14, 14, 118, 1318.46, 'USD', 'PAID', '2026-06-23 05:07:43', 'PAY-20260702-0014'),
(15, 15, 105, 1985.13, 'EUR', 'PAID', '2026-06-08 11:03:38', 'PAY-20260702-0015'),
(16, 16, 34, 1751.25, 'PLN', 'CANCELLED', '2026-06-19 00:51:07', 'PAY-20260702-0016'),
(17, 17, 29, 1982.77, 'PLN', 'CANCELLED', '2026-06-07 19:26:36', 'PAY-20260702-0017'),
(18, 18, 10, 1202.1, 'EUR', 'FAILED', '2026-06-22 07:57:36', 'PAY-20260702-0018'),
(19, 1, 93, 1074.82, 'USD', 'PENDING', NULL, 'PAY-20260702-0019'),
(20, 2, 133, 1521.04, 'PLN', 'CANCELLED', '2026-06-26 03:24:50', 'PAY-20260702-0020'),
(21, 3, 45, 1233.65, 'PLN', 'FAILED', '2026-06-17 17:44:21', 'PAY-20260702-0021'),
(22, 4, 113, 1779.36, 'USD', 'PAID', '2026-06-28 11:17:31', 'PAY-20260702-0022'),
(23, 5, 73, 535.7, 'EUR', 'PAID', '2026-06-24 13:59:39', 'PAY-20260702-0023'),
(24, 6, 49, 1245.25, 'PLN', 'PAID', '2026-06-07 18:42:15', 'PAY-20260702-0024'),
(25, 7, 124, 1611.53, 'USD', 'CANCELLED', '2026-07-01 00:12:38', 'PAY-20260702-0025'),
(26, 8, 99, 1576.06, 'PLN', 'FAILED', '2026-06-07 09:52:34', 'PAY-20260702-0026'),
(27, 9, 30, 1161.61, 'EUR', 'PENDING', NULL, 'PAY-20260702-0027'),
(28, 10, 40, 648.57, 'USD', 'PENDING', NULL, 'PAY-20260702-0028'),
(29, 11, 43, 1239.39, 'EUR', 'CANCELLED', '2026-06-07 23:22:28', 'PAY-20260702-0029'),
(30, 12, 29, 728.73, 'EUR', 'PENDING', NULL, 'PAY-20260702-0030'),
(31, 13, 128, 1894.24, 'PLN', 'PAID', '2026-06-14 15:10:54', 'PAY-20260702-0031'),
(32, 14, 15, 544.16, 'EUR', 'PENDING', NULL, 'PAY-20260702-0032'),
(33, 15, 115, 897.82, 'USD', 'FAILED', '2026-06-10 20:51:43', 'PAY-20260702-0033'),
(34, 16, 32, 815.59, 'EUR', 'FAILED', '2026-06-07 12:00:47', 'PAY-20260702-0034'),
(35, 17, 4, 1183.36, 'EUR', 'CANCELLED', '2026-06-16 03:10:12', 'PAY-20260702-0035'),
(36, 18, 12, 1675.26, 'EUR', 'PENDING', NULL, 'PAY-20260702-0036'),
(37, 1, 113, 1426.05, 'USD', 'PENDING', NULL, 'PAY-20260702-0037'),
(38, 2, 78, 1378.05, 'PLN', 'CANCELLED', '2026-06-27 10:17:41', 'PAY-20260702-0038'),
(39, 3, 44, 1540.84, 'EUR', 'PAID', '2026-06-14 00:10:24', 'PAY-20260702-0039'),
(40, 4, 12, 1649.88, 'USD', 'FAILED', '2026-06-24 08:17:29', 'PAY-20260702-0040');


-- Resync SERIAL sequences with seeded data (so API inserts don't collide)
SELECT setval(pg_get_serial_sequence('location', 'location_id'), (SELECT COALESCE(MAX(location_id), 1) FROM location));
SELECT setval(pg_get_serial_sequence('warehouse', 'warehouse_id'), (SELECT COALESCE(MAX(warehouse_id), 1) FROM warehouse));
SELECT setval(pg_get_serial_sequence('zone', 'zone_id'), (SELECT COALESCE(MAX(zone_id), 1) FROM zone));
SELECT setval(pg_get_serial_sequence('aisle', 'aisle_id'), (SELECT COALESCE(MAX(aisle_id), 1) FROM aisle));
SELECT setval(pg_get_serial_sequence('rack', 'rack_id'), (SELECT COALESCE(MAX(rack_id), 1) FROM rack));
SELECT setval(pg_get_serial_sequence('shelf', 'shelf_id'), (SELECT COALESCE(MAX(shelf_id), 1) FROM shelf));
SELECT setval(pg_get_serial_sequence('capacity', 'capacity_id'), (SELECT COALESCE(MAX(capacity_id), 1) FROM capacity));
SELECT setval(pg_get_serial_sequence('party', 'party_id'), (SELECT COALESCE(MAX(party_id), 1) FROM party));
SELECT setval(pg_get_serial_sequence('party_contact', 'contact_id'), (SELECT COALESCE(MAX(contact_id), 1) FROM party_contact));
SELECT setval(pg_get_serial_sequence('party_relationship', 'relationship_id'), (SELECT COALESCE(MAX(relationship_id), 1) FROM party_relationship));
SELECT setval(pg_get_serial_sequence('role', 'role_id'), (SELECT COALESCE(MAX(role_id), 1) FROM role));
SELECT setval(pg_get_serial_sequence('storage_request', 'request_id'), (SELECT COALESCE(MAX(request_id), 1) FROM storage_request));
SELECT setval(pg_get_serial_sequence('storage_reservation', 'reservation_id'), (SELECT COALESCE(MAX(reservation_id), 1) FROM storage_reservation));
SELECT setval(pg_get_serial_sequence('storage_record', 'storage_record_id'), (SELECT COALESCE(MAX(storage_record_id), 1) FROM storage_record));
SELECT setval(pg_get_serial_sequence('payment', 'payment_id'), (SELECT COALESCE(MAX(payment_id), 1) FROM payment));
SELECT setval(pg_get_serial_sequence('cargo_event_type', 'event_type_id'), (SELECT COALESCE(MAX(event_type_id), 1) FROM cargo_event_type));
SELECT setval(pg_get_serial_sequence('cargo_event_history', 'event_id'), (SELECT COALESCE(MAX(event_id), 1) FROM cargo_event_history));
