
-- SQL generated by wms-data-generator
-- DO NOT EDIT THIS FILE MANUALLY
-- Edit the create-wms-schema.sql file instead
--
-- 🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚
-- 🚚 DELIVEROO (C) 2025 🚚
-- 🚚   SHIP THAT SHIT   🚚
-- 🚚   Spółka Akcyjna   🚚
-- 🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚
--
-- Zatrudniamy! https://shorturl.at/G98Ej


-- Clean up previous tables
DROP TABLE IF EXISTS cargo_event_history CASCADE;
DROP TABLE IF EXISTS cargo_event_type CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS storage_record CASCADE;
DROP TABLE IF EXISTS storage_reservation CASCADE;
DROP TABLE IF EXISTS storage_request CASCADE;
DROP TABLE IF EXISTS employee_warehouse CASCADE;
DROP TABLE IF EXISTS party_role CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS party_relationship CASCADE;
DROP TABLE IF EXISTS party_contact CASCADE;
DROP TABLE IF EXISTS party CASCADE;
DROP TABLE IF EXISTS capacity CASCADE;
DROP TABLE IF EXISTS shelf CASCADE;
DROP TABLE IF EXISTS rack CASCADE;
DROP TABLE IF EXISTS aisle CASCADE;
DROP TABLE IF EXISTS zone CASCADE;
DROP TABLE IF EXISTS warehouse CASCADE;
DROP TABLE IF EXISTS location CASCADE;

-- 1. LOCATIONS
CREATE TABLE location (
    location_id SERIAL PRIMARY KEY,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    country TEXT NOT NULL
);

-- 2. WAREHOUSES
CREATE TABLE warehouse (
    warehouse_id SERIAL PRIMARY KEY,
    location_id INTEGER NOT NULL REFERENCES location(location_id),
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED','MAINTENANCE','INACTIVE'))
);
-- Basic FK index only
CREATE INDEX idx_warehouse_location_id ON warehouse(location_id);

-- 3. ZONES
CREATE TABLE zone (
    zone_id SERIAL PRIMARY KEY,
    warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id),
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED','MAINTENANCE','INACTIVE'))
);
CREATE INDEX idx_zone_warehouse_id ON zone(warehouse_id);

-- 4. AISLES
CREATE TABLE aisle (
    aisle_id SERIAL PRIMARY KEY,
    zone_id INTEGER NOT NULL REFERENCES zone(zone_id),
    label TEXT NOT NULL,
    width INTEGER NOT NULL,
    width_unit TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED','MAINTENANCE','INACTIVE'))
);
CREATE INDEX idx_aisle_zone_id ON aisle(zone_id);

-- 5. RACKS
CREATE TABLE rack (
    rack_id SERIAL PRIMARY KEY,
    aisle_id INTEGER NOT NULL REFERENCES aisle(aisle_id),
    label TEXT NOT NULL,
    max_height INTEGER NOT NULL,
    height_unit TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED','MAINTENANCE','INACTIVE'))
);
CREATE INDEX idx_rack_aisle_id ON rack(aisle_id);

-- 6. SHELVES
CREATE TABLE shelf (
    shelf_id SERIAL PRIMARY KEY,
    rack_id INTEGER NOT NULL REFERENCES rack(rack_id),
    level TEXT NOT NULL,
    max_weight NUMERIC NOT NULL,
    max_volume NUMERIC NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED','MAINTENANCE','INACTIVE'))
);
CREATE INDEX idx_shelf_rack_id ON shelf(rack_id);

-- 7. CAPACITY
CREATE TABLE capacity (
    capacity_id SERIAL PRIMARY KEY,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('WAREHOUSE','ZONE','RACK','SHELF')),
    entity_id INTEGER NOT NULL,
    value NUMERIC NOT NULL,
    unit TEXT NOT NULL,
    description TEXT
);
-- Composite index exists, but likely insufficient for complex aggregations without covering columns
CREATE INDEX idx_capacity_entity ON capacity(entity_type, entity_id);

-- 8. PARTY
CREATE TABLE party (
    party_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    contact_email TEXT, -- Important: No index here implies full scan on search
    contact_phone TEXT,
    data JSONB, -- Important: No GIN index here
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 9. PARTY CONTACTS
CREATE TABLE party_contact (
    contact_id SERIAL PRIMARY KEY,
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    details TEXT NOT NULL
);
CREATE INDEX idx_party_contact_party_id ON party_contact(party_id);

-- 10. PARTY RELATIONSHIP
CREATE TABLE party_relationship (
    relationship_id SERIAL PRIMARY KEY,
    party_id_primary INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    party_id_secondary INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    relationship_type TEXT NOT NULL,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    notes TEXT
);
CREATE INDEX idx_party_relationship_primary ON party_relationship(party_id_primary);
CREATE INDEX idx_party_relationship_secondary ON party_relationship(party_id_secondary);

-- 11. ADDRESS
CREATE TABLE address (
    address_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    street_address TEXT NOT NULL,
    city TEXT NOT NULL,
    country TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    address_type TEXT NOT NULL CHECK (address_type IN ('BILLING','SHIPPING','CORPORATE','PERSONAL','OTHER'))
);
CREATE INDEX idx_address_party_id ON address(party_id);

-- 12. ROLES
CREATE TABLE role (
    role_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL CHECK (name IN ('DIRECTOR','WAREHOUSE_MANAGER','LOGISTICS_COORDINATOR','STORAGE_APPROVER','OPERATOR')),
    description TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_role_name ON role(name);

-- 13. PARTY ROLES
CREATE TABLE party_role (
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES role(role_id) ON DELETE CASCADE,
    assigned_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (party_id, role_id)
);
CREATE INDEX idx_party_role_party_id ON party_role(party_id);
CREATE INDEX idx_party_role_role_id ON party_role(role_id);

-- 14. EMPLOYEE-WAREHOUSE
CREATE TABLE employee_warehouse (
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id) ON DELETE CASCADE,
    assigned_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_until TIMESTAMP,
    PRIMARY KEY (party_id, warehouse_id, assigned_from)
);
CREATE INDEX idx_employee_warehouse_party_id ON employee_warehouse(party_id);
CREATE INDEX idx_employee_warehouse_warehouse ON employee_warehouse(warehouse_id);

-- 15. STORAGE REQUESTS
CREATE TABLE storage_request (
    request_id SERIAL PRIMARY KEY,
    issuing_party_id INTEGER NOT NULL REFERENCES party(party_id),
    warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id),
    requested_entry_date TIMESTAMP NOT NULL,
    requested_exit_date TIMESTAMP NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING','ACCEPTED','REJECTED')) DEFAULT 'PENDING',
    decisive_party_id INTEGER REFERENCES party(party_id),
    decision_date TIMESTAMP
);
CREATE INDEX idx_storage_request_issuing_party_id ON storage_request(issuing_party_id);
CREATE INDEX idx_storage_request_warehouse_id ON storage_request(warehouse_id);
CREATE INDEX idx_storage_request_decisive_party_id ON storage_request(decisive_party_id);

-- 16. STORAGE RESERVATIONS
CREATE TABLE storage_reservation (
    reservation_id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES storage_request(request_id) ON DELETE CASCADE,
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    shelf_id INTEGER NOT NULL REFERENCES shelf(shelf_id),
    reserved_weight NUMERIC NOT NULL,
    reserved_volume NUMERIC NOT NULL,
    reserved_from TIMESTAMP NOT NULL,
    reserved_until TIMESTAMP NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING','ACTIVE','EXPIRED','CANCELLED')) DEFAULT 'PENDING'
);
CREATE INDEX idx_storage_reservation_request_id ON storage_reservation(request_id);
CREATE INDEX idx_storage_reservation_party_id ON storage_reservation(party_id);
CREATE INDEX idx_storage_reservation_shelf_id ON storage_reservation(shelf_id);

-- 17. STORAGE RECORDS
CREATE TABLE storage_record (
    storage_record_id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES storage_request(request_id),
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    shelf_id INTEGER NOT NULL REFERENCES shelf(shelf_id),
    actual_entry_date TIMESTAMP NOT NULL,
    actual_exit_date TIMESTAMP,
    cargo_description TEXT NOT NULL,
    cargo_weight NUMERIC NOT NULL,
    cargo_volume NUMERIC NOT NULL
);
CREATE INDEX idx_storage_record_request_id ON storage_record(request_id);
CREATE INDEX idx_storage_record_party_id ON storage_record(party_id);
CREATE INDEX idx_storage_record_shelf_id ON storage_record(shelf_id);

-- 18. PAYMENTS
CREATE TABLE payment (
    payment_id SERIAL PRIMARY KEY,
    storage_record_id INTEGER NOT NULL REFERENCES storage_record(storage_record_id) ON DELETE CASCADE,
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    amount NUMERIC NOT NULL,
    currency TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING','PAID','FAILED','CANCELLED')) DEFAULT 'PENDING',
    payment_date TIMESTAMP,
    external_reference TEXT
);
CREATE INDEX idx_payment_party_id ON payment(party_id);
CREATE INDEX idx_payment_storage_record_id ON payment(storage_record_id);

-- 19. CARGO EVENT TYPES
CREATE TABLE cargo_event_type (
    event_type_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT
);
CREATE UNIQUE INDEX idx_cargo_event_type_name ON cargo_event_type(name);

-- 20. CARGO EVENT HISTORY
CREATE TABLE cargo_event_history (
    event_id SERIAL PRIMARY KEY,
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    storage_record_id INTEGER NOT NULL REFERENCES storage_record(storage_record_id) ON DELETE CASCADE,
    event_type_id INTEGER NOT NULL REFERENCES cargo_event_type(event_type_id),
    event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details JSONB
);
CREATE INDEX idx_cargo_event_history_party_id ON cargo_event_history(party_id);
CREATE INDEX idx_cargo_event_history_storage_record_id ON cargo_event_history(storage_record_id);
CREATE INDEX idx_cargo_event_history_event_type_id ON cargo_event_history(event_type_id);

-- Locations
INSERT INTO location (location_id, address, city, postal_code, country) VALUES
(1, 'ul. Wichrowa 89', 'Janki', '05-090', 'Poland');

-- Warehouses
INSERT INTO warehouse (warehouse_id, location_id, name, description) VALUES
(1, 1, 'Main Deliveroo Warehouse', 'Main warehouse for Deliveroo in Poland');

-- Roles
INSERT INTO role (role_id, name, description) VALUES
(1, 'DIRECTOR', 'Executive director overseeing all warehouse operations and strategic planning.'),
(2, 'WAREHOUSE_MANAGER', 'Oversees all warehouse operations, staff management, and safety protocols.'),
(3, 'LOGISTICS_COORDINATOR', 'Manages logistics, distribution processes, and supply chain coordination.'),
(4, 'STORAGE_APPROVER', 'Reviews and approves storage requests and reservation decisions.'),
(5, 'OPERATOR', 'Handles day-to-day warehouse operations including receiving, shipping, and inventory management.');

-- Contractor and Employee Parties
INSERT INTO party (party_id, name, data, created_at, updated_at) VALUES
(1, 'Mccarthy-Murphy', '{"type": "contractor_company", "tax_id_number": "5411182462", "status": "ACTIVE"}'::jsonb, '2024-11-03 14:28:58.144436', '2025-07-27 19:02:42.929470'),
(2, 'Hubbard Ltd', '{"type": "contractor_company", "tax_id_number": "8495968170", "status": "ACTIVE"}'::jsonb, '2025-05-22 08:02:34.367602', '2025-09-19 12:57:20.186959'),
(3, 'Herrera Ltd', '{"type": "contractor_company", "tax_id_number": "5382267353", "status": "ACTIVE"}'::jsonb, '2025-02-07 03:00:42.064192', '2025-11-29 03:50:49.298246'),
(4, 'Garcia, Smith and Thompson', '{"type": "contractor_company", "tax_id_number": "6905573020", "status": "ACTIVE"}'::jsonb, '2024-07-01 20:52:11.586617', '2025-10-19 19:59:50.238122'),
(5, 'Owens PLC', '{"type": "contractor_company", "tax_id_number": "3408065360", "status": "ACTIVE"}'::jsonb, '2025-05-23 09:54:48.893806', '2026-01-29 06:23:28.669052'),
(6, 'Mitchell, Patterson and Riley', '{"type": "contractor_company", "tax_id_number": "1334205442", "status": "INACTIVE"}'::jsonb, '2026-05-21 12:11:14.108406', '2025-10-30 06:22:59.663963'),
(7, 'Serrano Ltd', '{"type": "contractor_company", "tax_id_number": "6011538084", "status": "ACTIVE"}'::jsonb, '2025-03-10 13:41:12.717820', '2026-03-28 20:02:28.955799'),
(8, 'Garza-Wilson', '{"type": "contractor_company", "tax_id_number": "6652230791", "status": "ACTIVE"}'::jsonb, '2025-09-22 18:26:20.832803', '2026-01-30 01:04:38.194690'),
(9, 'Smith Group', '{"type": "contractor_company", "tax_id_number": "5192836096", "status": "ACTIVE"}'::jsonb, '2024-08-21 22:05:09.799244', '2025-07-13 21:21:41.415709'),
(10, 'Dennis PLC', '{"type": "contractor_company", "tax_id_number": "1029968968", "status": "ACTIVE"}'::jsonb, '2025-04-26 07:49:21.235588', '2025-11-25 22:44:31.118275'),
(11, 'Garza, Hernandez and James', '{"type": "contractor_company", "tax_id_number": null, "status": "ACTIVE"}'::jsonb, '2025-07-30 01:25:33.657650', '2025-08-29 22:24:47.070265'),
(12, 'Wood, Henry and Huber', '{"type": "contractor_company", "tax_id_number": "0700446901", "status": "ACTIVE"}'::jsonb, '2026-06-21 05:52:03.511044', '2026-05-20 21:01:44.864364'),
(13, 'Tran Group', '{"type": "contractor_company", "tax_id_number": "6620807580", "status": "ACTIVE"}'::jsonb, '2025-04-14 16:07:04.625690', '2025-08-29 22:59:05.123012'),
(14, 'Stone PLC', '{"type": "contractor_company", "tax_id_number": "3342506052", "status": "ACTIVE"}'::jsonb, '2024-10-19 02:41:03.418938', '2026-06-30 01:08:54.202727'),
(15, 'Johnson-Lynn', '{"type": "contractor_company", "tax_id_number": null, "status": "ACTIVE"}'::jsonb, '2025-01-17 07:12:55.397235', '2025-07-27 06:36:32.087698'),
(16, 'Alexander, Rodgers and Smith', '{"type": "contractor_company", "tax_id_number": "0815510229", "status": "ACTIVE"}'::jsonb, '2024-10-18 17:19:18.074256', '2025-12-01 16:27:38.324225'),
(17, 'Holt-Solis', '{"type": "contractor_company", "tax_id_number": "8906561953", "status": "INACTIVE"}'::jsonb, '2024-11-09 07:10:09.069967', '2025-12-23 12:03:12.650342'),
(18, 'Young-Love', '{"type": "contractor_company", "tax_id_number": "9540433386", "status": "ACTIVE"}'::jsonb, '2026-05-06 06:17:02.846612', '2026-04-07 00:24:59.587133'),
(19, 'Hernandez, Snow and Santos', '{"type": "contractor_company", "tax_id_number": "0522215362", "status": "ACTIVE"}'::jsonb, '2025-09-30 00:21:43.903171', '2025-07-30 13:07:07.331030'),
(20, 'Bell-Graham', '{"type": "contractor_company", "tax_id_number": "2958297502", "status": "ACTIVE"}'::jsonb, '2024-10-15 10:27:07.216930', '2026-03-27 14:17:10.253853'),
(21, 'Carter Ltd', '{"type": "contractor_company", "tax_id_number": "6074475306", "status": "ACTIVE"}'::jsonb, '2024-11-01 17:48:42.155597', '2026-04-05 15:02:37.661042'),
(22, 'Pitts, Wilson and Rowe', '{"type": "contractor_company", "tax_id_number": "3177806331", "status": "ACTIVE"}'::jsonb, '2025-05-26 17:55:58.777014', '2026-04-07 15:30:18.169221'),
(23, 'Spence-Norris', '{"type": "contractor_company", "tax_id_number": "6118159952", "status": "ACTIVE"}'::jsonb, '2024-09-21 23:07:57.502723', '2026-02-27 02:57:26.303502'),
(24, 'Mayer, Ward and English', '{"type": "contractor_company", "tax_id_number": "9549584810", "status": "ACTIVE"}'::jsonb, '2025-06-30 21:24:53.681253', '2026-06-10 17:42:58.378446'),
(25, 'Young-Taylor', '{"type": "contractor_company", "tax_id_number": "6859310788", "status": "ACTIVE"}'::jsonb, '2024-11-22 01:55:26.639063', '2025-11-24 12:27:31.781552'),
(26, 'Miller, Foster and Martin', '{"type": "contractor_company", "tax_id_number": "8123855030", "status": "ACTIVE"}'::jsonb, '2026-03-23 14:57:54.484714', '2025-10-20 18:58:26.053159'),
(27, 'Foster, Butler and Johnson', '{"type": "contractor_company", "tax_id_number": "4433133560", "status": "ACTIVE"}'::jsonb, '2025-05-02 20:16:21.960742', '2026-06-16 01:35:39.008777'),
(28, 'Baker-Thomas', '{"type": "contractor_company", "tax_id_number": "7083964037", "status": "ACTIVE"}'::jsonb, '2025-02-23 04:44:00.452126', '2025-07-02 04:39:22.683542'),
(29, 'Brown, Espinoza and Petersen', '{"type": "contractor_company", "tax_id_number": "5618572997", "status": "ACTIVE"}'::jsonb, '2025-11-16 15:55:47.892914', '2026-03-23 20:06:52.262306'),
(30, 'Miller, Brown and Garcia', '{"type": "contractor_company", "tax_id_number": "9582854523", "status": "ACTIVE"}'::jsonb, '2024-07-06 00:56:28.597878', '2025-12-04 13:01:40.269122'),
(31, 'Salazar, Blair and Gibson', '{"type": "contractor_company", "tax_id_number": "6835633041", "status": "ACTIVE"}'::jsonb, '2026-01-25 02:18:56.625950', '2026-04-04 04:11:26.491836'),
(32, 'Carr PLC', '{"type": "contractor_company", "tax_id_number": "7217222890", "status": "ACTIVE"}'::jsonb, '2024-09-13 22:12:19.480702', '2025-08-30 12:11:27.547619'),
(33, 'Mora, Hale and Braun', '{"type": "contractor_company", "tax_id_number": "1775353217", "status": "ACTIVE"}'::jsonb, '2024-08-21 00:01:24.211535', '2026-01-12 01:38:40.249408'),
(34, 'Hughes PLC', '{"type": "contractor_company", "tax_id_number": "6174972776", "status": "ACTIVE"}'::jsonb, '2026-04-12 07:35:28.262417', '2025-10-16 17:32:33.169513'),
(35, 'Dalton, Brock and Thompson', '{"type": "contractor_company", "tax_id_number": "2535227958", "status": "ACTIVE"}'::jsonb, '2025-03-12 00:54:25.672860', '2025-08-07 18:55:50.425530'),
(36, 'Paul-Ryan', '{"type": "contractor_company", "tax_id_number": null, "status": "ACTIVE"}'::jsonb, '2025-06-25 18:30:28.391623', '2026-02-01 15:04:11.787311'),
(37, 'Miller-Wells', '{"type": "contractor_company", "tax_id_number": null, "status": "ACTIVE"}'::jsonb, '2024-12-07 03:48:51.811160', '2025-12-05 13:13:02.402990'),
(38, 'Murray-King', '{"type": "contractor_company", "tax_id_number": "2895295201", "status": "ACTIVE"}'::jsonb, '2025-10-16 22:29:09.266777', '2025-07-06 22:26:58.321111'),
(39, 'Ramos-Hardy', '{"type": "contractor_company", "tax_id_number": "8217508395", "status": "INACTIVE"}'::jsonb, '2025-04-21 01:19:23.670604', '2026-04-11 21:59:01.020932'),
(40, 'Bishop, Petersen and Ortiz', '{"type": "contractor_company", "tax_id_number": "7394237320", "status": "ACTIVE"}'::jsonb, '2024-10-30 05:43:45.804633', '2025-11-03 17:43:09.626769'),
(41, 'Allen, French and Graham', '{"type": "contractor_company", "tax_id_number": "1224443498", "status": "ACTIVE"}'::jsonb, '2024-10-01 06:53:22.822225', '2025-12-20 12:24:16.494789'),
(42, 'Conley, Edwards and Mayo', '{"type": "contractor_company", "tax_id_number": "0300993935", "status": "ACTIVE"}'::jsonb, '2025-01-29 06:58:13.149418', '2026-03-27 17:00:08.432698'),
(43, 'Blackwell-Gutierrez', '{"type": "contractor_company", "tax_id_number": "6458446353", "status": "ACTIVE"}'::jsonb, '2024-08-09 03:58:11.708821', '2025-09-24 03:05:11.478075'),
(44, 'Wolf Inc', '{"type": "contractor_company", "tax_id_number": "9299034498", "status": "ACTIVE"}'::jsonb, '2025-03-26 18:49:06.070899', '2025-10-06 21:40:18.603528'),
(45, 'Curry, Walker and Brown', '{"type": "contractor_company", "tax_id_number": "1857521365", "status": "ACTIVE"}'::jsonb, '2026-05-15 20:36:01.035262', '2026-04-17 08:14:18.361910'),
(46, 'Gregory, Moses and White', '{"type": "contractor_company", "tax_id_number": "1388389007", "status": "ACTIVE"}'::jsonb, '2025-04-05 08:05:22.563672', '2026-05-31 15:27:20.749193'),
(47, 'Johnson, Ross and White', '{"type": "contractor_company", "tax_id_number": "0024228413", "status": "ACTIVE"}'::jsonb, '2026-01-18 05:02:26.334776', '2025-12-29 02:27:14.342557'),
(48, 'Watkins-Gray', '{"type": "contractor_company", "tax_id_number": "9727111543", "status": "INACTIVE"}'::jsonb, '2025-04-29 19:47:21.428720', '2025-09-18 19:02:06.619644'),
(49, 'Obrien, Anderson and Wilson', '{"type": "contractor_company", "tax_id_number": "0461040030", "status": "ACTIVE"}'::jsonb, '2025-09-09 04:24:11.206036', '2025-12-04 14:41:53.117849'),
(50, 'Jones, Miller and Solis', '{"type": "contractor_company", "tax_id_number": "1030147960", "status": "ACTIVE"}'::jsonb, '2025-12-14 19:30:56.603788', '2025-11-12 23:10:20.642559'),
(71, 'Shane Cox', '{"type": "contractor_employee", "job_title": "Cytogeneticist"}'::jsonb, '2026-06-19 16:52:21.244419', '2026-07-01 01:14:16.913403'),
(72, 'John Bowers', '{"type": "contractor_employee", "job_title": "Secretary/administrator"}'::jsonb, '2025-08-11 06:05:22.848981', '2026-07-01 01:17:34.249320'),
(73, 'Joseph Powell', '{"type": "contractor_employee", "job_title": "Surveyor, quantity"}'::jsonb, '2025-11-10 05:38:17.369426', '2026-07-01 01:12:58.308819'),
(74, 'Nicole Bowers', '{"type": "contractor_employee", "job_title": "Textile designer"}'::jsonb, '2025-09-23 13:18:26.340583', '2026-07-01 01:17:26.443078'),
(75, 'David Smith', '{"type": "contractor_employee", "job_title": "Police officer"}'::jsonb, '2026-01-01 14:42:09.042856', '2026-07-01 01:12:46.681726'),
(76, 'Michael Castillo', '{"type": "contractor_employee", "job_title": "Recruitment consultant"}'::jsonb, '2025-10-23 01:10:44.866512', '2026-07-01 01:17:32.172557'),
(77, 'Lee Mitchell', '{"type": "contractor_employee", "job_title": "Automotive engineer"}'::jsonb, '2025-10-23 17:11:05.988170', '2026-07-01 01:12:44.864243'),
(78, 'Joshua Mosley', '{"type": "contractor_employee", "job_title": "Film/video editor"}'::jsonb, '2025-07-27 06:27:03.647973', '2026-07-01 01:14:20.363408'),
(79, 'Edward Berg', '{"type": "contractor_employee", "job_title": "Pharmacist, hospital"}'::jsonb, '2025-11-30 04:17:43.473576', '2026-07-01 01:17:34.711338'),
(80, 'Michelle Richardson', '{"type": "contractor_employee", "job_title": "Doctor, hospital"}'::jsonb, '2026-02-09 11:58:52.848791', '2026-07-01 01:17:56.233016'),
(81, 'Anthony Jones', '{"type": "contractor_employee", "job_title": "Engineer, agricultural"}'::jsonb, '2025-09-26 21:00:11.643980', '2026-07-01 01:14:24.573120'),
(82, 'Sonya Marquez', '{"type": "contractor_employee", "job_title": "Pharmacist, hospital"}'::jsonb, '2026-02-28 11:34:01.695417', '2026-07-01 01:15:14.960448'),
(83, 'Kelly Bradford', '{"type": "contractor_employee", "job_title": "Tour manager"}'::jsonb, '2026-04-16 23:55:49.491155', '2026-07-01 01:12:19.334602'),
(84, 'Dwayne Evans', '{"type": "contractor_employee", "job_title": "Geologist, wellsite"}'::jsonb, '2025-08-02 15:33:57.809518', '2026-07-01 01:15:27.101689'),
(85, 'Janice Bautista', '{"type": "contractor_employee", "job_title": "Politician''s assistant"}'::jsonb, '2026-01-14 21:35:37.687521', '2026-07-01 01:14:58.232769'),
(86, 'Melanie Carr', '{"type": "contractor_employee", "job_title": "Transport planner"}'::jsonb, '2026-03-02 12:26:15.113849', '2026-07-01 01:14:11.357830'),
(87, 'Jesse Sanchez', '{"type": "contractor_employee", "job_title": "Pharmacologist"}'::jsonb, '2025-09-22 03:05:10.784705', '2026-07-01 01:13:36.949982'),
(88, 'Shawn Sullivan', '{"type": "contractor_employee", "job_title": "Sports coach"}'::jsonb, '2026-06-16 05:52:45.464635', '2026-07-01 01:15:28.149868'),
(89, 'Ryan Harrison', '{"type": "contractor_employee", "job_title": "Accountant, chartered certified"}'::jsonb, '2025-09-15 10:03:13.372457', '2026-07-01 01:13:27.732346'),
(90, 'Christine Fields', '{"type": "contractor_employee", "job_title": "Holiday representative"}'::jsonb, '2025-10-27 13:23:37.126125', '2026-07-01 01:12:16.868558'),
(91, 'Janet Miller', '{"type": "contractor_employee", "job_title": "Translator"}'::jsonb, '2026-03-20 22:18:00.785119', '2026-07-01 01:15:20.511617'),
(92, 'Jacqueline Kramer', '{"type": "contractor_employee", "job_title": "Public librarian"}'::jsonb, '2026-05-21 13:01:10.479143', '2026-07-01 01:12:07.409710'),
(93, 'Robin Padilla', '{"type": "contractor_employee", "job_title": "Firefighter"}'::jsonb, '2026-02-13 09:43:20.348785', '2026-07-01 01:14:38.453358'),
(94, 'Laura Peterson', '{"type": "contractor_employee", "job_title": "Medical physicist"}'::jsonb, '2026-06-26 21:51:02.302165', '2026-07-01 01:12:25.696634'),
(95, 'Erik Gomez', '{"type": "contractor_employee", "job_title": "Best boy"}'::jsonb, '2025-08-20 10:10:53.121180', '2026-07-01 01:13:08.165872'),
(96, 'Alexandra Peck', '{"type": "contractor_employee", "job_title": "Agricultural consultant"}'::jsonb, '2025-11-17 21:16:43.511490', '2026-07-01 01:12:30.255176'),
(97, 'Kyle Herrera', '{"type": "contractor_employee", "job_title": "Editor, film/video"}'::jsonb, '2025-11-12 21:00:10.779269', '2026-07-01 01:15:31.856375'),
(98, 'Sharon Rivers', '{"type": "contractor_employee", "job_title": "Politician''s assistant"}'::jsonb, '2026-02-23 00:27:38.559264', '2026-07-01 01:12:27.201439'),
(99, 'Mr. Anthony Zimmerman', '{"type": "contractor_employee", "job_title": "Psychotherapist, dance movement"}'::jsonb, '2025-10-16 01:52:36.833426', '2026-07-01 01:14:00.966090'),
(100, 'Jessica Moss', '{"type": "contractor_employee", "job_title": "Warehouse manager"}'::jsonb, '2026-04-29 17:35:01.054395', '2026-07-01 01:13:02.292900'),
(101, 'David Gonzalez', '{"type": "contractor_employee", "job_title": "Programmer, applications"}'::jsonb, '2025-07-25 08:13:56.028682', '2026-07-01 01:15:52.053028'),
(102, 'Mrs. Kathryn Perry', '{"type": "contractor_employee", "job_title": "Editor, film/video"}'::jsonb, '2025-11-17 22:47:33.620146', '2026-07-01 01:13:07.875993'),
(103, 'Rachel Marshall', '{"type": "contractor_employee", "job_title": "Social research officer, government"}'::jsonb, '2025-08-25 08:24:55.821061', '2026-07-01 01:13:09.653846'),
(104, 'Jacqueline Smith', '{"type": "contractor_employee", "job_title": "Ship broker"}'::jsonb, '2026-03-26 22:45:21.300678', '2026-07-01 01:18:00.933677'),
(105, 'Nancy Ward', '{"type": "contractor_employee", "job_title": "Scientist, research (life sciences)"}'::jsonb, '2026-03-17 21:22:35.030517', '2026-07-01 01:17:30.847984'),
(106, 'Aaron Bailey', '{"type": "contractor_employee", "job_title": "Teacher, adult education"}'::jsonb, '2025-09-13 04:38:01.994896', '2026-07-01 01:14:20.914728'),
(107, 'Jimmy Bennett', '{"type": "contractor_employee", "job_title": "Armed forces operational officer"}'::jsonb, '2025-11-26 23:21:01.971497', '2026-07-01 01:15:44.657938'),
(108, 'Jennifer Turner MD', '{"type": "contractor_employee", "job_title": "Transport planner"}'::jsonb, '2026-03-14 03:26:41.813017', '2026-07-01 01:16:47.886357'),
(109, 'Tonya Yang', '{"type": "contractor_employee", "job_title": "Administrator, local government"}'::jsonb, '2026-05-01 20:05:00.875169', '2026-07-01 01:13:26.716902'),
(110, 'Shannon Sullivan', '{"type": "contractor_employee", "job_title": "Music therapist"}'::jsonb, '2026-04-03 14:26:17.726248', '2026-07-01 01:17:05.081900'),
(111, 'Jasmine Mccormick', '{"type": "contractor_employee", "job_title": "Therapist, nutritional"}'::jsonb, '2026-03-03 16:12:31.014825', '2026-07-01 01:13:58.362683'),
(112, 'Meghan Walker', '{"type": "contractor_employee", "job_title": "Brewing technologist"}'::jsonb, '2026-01-18 01:51:21.665195', '2026-07-01 01:15:51.470536'),
(113, 'Brianna Walker', '{"type": "contractor_employee", "job_title": "Geoscientist"}'::jsonb, '2026-03-04 03:58:51.371547', '2026-07-01 01:16:05.819850'),
(114, 'Ronald Norton', '{"type": "contractor_employee", "job_title": "Museum/gallery conservator"}'::jsonb, '2025-10-09 11:07:18.621107', '2026-07-01 01:14:36.603430'),
(115, 'Ronald Henderson', '{"type": "contractor_employee", "job_title": "Magazine features editor"}'::jsonb, '2025-11-26 08:52:40.658983', '2026-07-01 01:17:16.527144'),
(116, 'Betty Hernandez', '{"type": "contractor_employee", "job_title": "Waste management officer"}'::jsonb, '2025-11-24 05:36:20.253414', '2026-07-01 01:13:52.061219'),
(117, 'Christopher Davis', '{"type": "contractor_employee", "job_title": "Petroleum engineer"}'::jsonb, '2026-03-13 22:52:53.837692', '2026-07-01 01:13:44.490300'),
(118, 'Sean Wade', '{"type": "contractor_employee", "job_title": "Engineer, energy"}'::jsonb, '2025-08-13 06:07:29.733958', '2026-07-01 01:15:27.407956'),
(119, 'Kimberly Morris', '{"type": "contractor_employee", "job_title": "Engineer, materials"}'::jsonb, '2025-07-20 09:52:12.791767', '2026-07-01 01:13:33.139458'),
(120, 'Brianna Robertson', '{"type": "contractor_employee", "job_title": "Designer, industrial/product"}'::jsonb, '2026-06-11 08:22:25.598990', '2026-07-01 01:16:34.734054'),
(121, 'Julia Simmons', '{"type": "contractor_employee", "job_title": "Commercial/residential surveyor"}'::jsonb, '2026-01-03 02:08:19.848892', '2026-07-01 01:15:26.450968'),
(122, 'Michael Henry', '{"type": "contractor_employee", "job_title": "Exhibitions officer, museum/gallery"}'::jsonb, '2026-06-11 04:29:09.131835', '2026-07-01 01:13:46.581650'),
(123, 'Melissa Blackwell', '{"type": "contractor_employee", "job_title": "Engineer, mining"}'::jsonb, '2026-02-18 15:44:26.971457', '2026-07-01 01:12:50.059426'),
(124, 'Valerie Bennett', '{"type": "contractor_employee", "job_title": "Farm manager"}'::jsonb, '2026-06-06 15:01:07.259381', '2026-07-01 01:16:23.533093'),
(125, 'Michelle Wright', '{"type": "contractor_employee", "job_title": "Engineer, electrical"}'::jsonb, '2026-02-25 17:53:48.650718', '2026-07-01 01:13:51.101321'),
(126, 'Jamie Roberson', '{"type": "contractor_employee", "job_title": "Operational researcher"}'::jsonb, '2026-04-21 01:31:17.965978', '2026-07-01 01:13:42.674826'),
(127, 'Edward Cabrera', '{"type": "contractor_employee", "job_title": "Mining engineer"}'::jsonb, '2026-02-08 21:46:41.620059', '2026-07-01 01:17:17.032409'),
(128, 'Michael Harris', '{"type": "contractor_employee", "job_title": "Horticulturist, commercial"}'::jsonb, '2025-09-06 23:57:08.508576', '2026-07-01 01:14:50.620906'),
(129, 'Amanda Miles', '{"type": "contractor_employee", "job_title": "Teacher, secondary school"}'::jsonb, '2026-06-26 18:02:00.149774', '2026-07-01 01:17:11.199546'),
(130, 'Phillip Collins', '{"type": "contractor_employee", "job_title": "Research officer, trade union"}'::jsonb, '2026-02-21 18:47:01.762515', '2026-07-01 01:17:06.178004'),
(131, 'Thomas Frazier', '{"type": "contractor_employee", "job_title": "Archaeologist"}'::jsonb, '2026-05-26 16:54:32.919277', '2026-07-01 01:15:26.498081'),
(132, 'Dennis Webb', '{"type": "contractor_employee", "job_title": "Translator"}'::jsonb, '2026-06-22 01:59:53.065506', '2026-07-01 01:16:44.614471'),
(133, 'Julia Roberts MD', '{"type": "contractor_employee", "job_title": "Community education officer"}'::jsonb, '2026-01-14 16:10:35.904959', '2026-07-01 01:12:14.231025');

-- Party Relationships
INSERT INTO party_relationship (party_id_primary, party_id_secondary, relationship_type, valid_from) VALUES
(1, 71, 'REPRESENTATIVE', '2026-06-05 13:24:15.639263'),
(2, 72, 'REPRESENTATIVE', '2026-02-11 06:02:59.274749'),
(2, 73, 'REPRESENTATIVE', '2026-03-27 00:39:37.182705'),
(5, 74, 'REPRESENTATIVE', '2025-10-28 14:21:22.574198'),
(7, 75, 'REPRESENTATIVE', '2025-07-13 07:41:55.602304'),
(7, 76, 'REPRESENTATIVE', '2026-01-05 12:06:23.784340'),
(7, 77, 'REPRESENTATIVE', '2026-02-22 08:18:18.547570'),
(8, 78, 'REPRESENTATIVE', '2026-01-08 20:59:58.078102'),
(10, 79, 'REPRESENTATIVE', '2025-10-11 08:44:19.213875'),
(10, 80, 'REPRESENTATIVE', '2025-10-23 01:40:29.997513'),
(11, 81, 'REPRESENTATIVE', '2025-11-19 09:03:14.753857'),
(11, 82, 'REPRESENTATIVE', '2025-08-29 00:24:17.795111'),
(12, 83, 'REPRESENTATIVE', '2025-10-30 01:17:51.596234'),
(12, 84, 'REPRESENTATIVE', '2025-09-25 08:28:03.932090'),
(13, 85, 'REPRESENTATIVE', '2026-06-18 09:53:04.763111'),
(14, 86, 'REPRESENTATIVE', '2025-09-08 09:16:08.374599'),
(15, 87, 'REPRESENTATIVE', '2025-11-14 02:16:59.390646'),
(15, 88, 'REPRESENTATIVE', '2025-07-30 20:38:12.879917'),
(16, 89, 'REPRESENTATIVE', '2026-06-08 02:05:55.957464'),
(16, 90, 'REPRESENTATIVE', '2025-09-13 07:24:36.073320'),
(17, 91, 'REPRESENTATIVE', '2026-01-15 15:25:48.999638'),
(17, 92, 'REPRESENTATIVE', '2025-09-21 21:57:30.932651'),
(17, 93, 'REPRESENTATIVE', '2025-07-09 10:14:35.222669'),
(22, 94, 'REPRESENTATIVE', '2025-09-09 14:05:46.349490'),
(23, 95, 'REPRESENTATIVE', '2025-10-15 00:47:27.675560'),
(23, 96, 'REPRESENTATIVE', '2026-04-14 14:25:37.502906'),
(23, 97, 'REPRESENTATIVE', '2026-04-13 19:36:02.402078'),
(24, 98, 'REPRESENTATIVE', '2025-09-03 10:33:32.107167'),
(24, 99, 'REPRESENTATIVE', '2025-11-21 09:37:22.837541'),
(25, 100, 'REPRESENTATIVE', '2025-09-08 02:41:05.342118'),
(25, 101, 'REPRESENTATIVE', '2026-04-02 01:36:56.812092'),
(25, 102, 'REPRESENTATIVE', '2025-11-19 19:43:58.921665'),
(26, 103, 'REPRESENTATIVE', '2026-04-22 10:02:40.265856'),
(26, 104, 'REPRESENTATIVE', '2026-04-20 07:58:37.361917'),
(26, 105, 'REPRESENTATIVE', '2025-12-11 18:54:26.478863'),
(28, 106, 'REPRESENTATIVE', '2026-05-01 07:54:40.382122'),
(28, 107, 'REPRESENTATIVE', '2026-05-17 01:25:18.114964'),
(29, 108, 'REPRESENTATIVE', '2026-06-27 08:59:35.493238'),
(32, 109, 'REPRESENTATIVE', '2026-02-01 17:43:40.475452'),
(33, 110, 'REPRESENTATIVE', '2026-06-20 23:46:59.946755'),
(33, 111, 'REPRESENTATIVE', '2026-02-27 02:34:22.800945'),
(34, 112, 'REPRESENTATIVE', '2026-03-18 04:46:15.738878'),
(34, 113, 'REPRESENTATIVE', '2026-02-06 22:55:56.239566'),
(34, 114, 'REPRESENTATIVE', '2025-10-26 04:01:02.064530'),
(36, 115, 'REPRESENTATIVE', '2025-12-21 23:22:12.036157'),
(38, 116, 'REPRESENTATIVE', '2025-11-09 15:41:30.322235'),
(38, 117, 'REPRESENTATIVE', '2026-04-22 13:52:14.661386'),
(39, 118, 'REPRESENTATIVE', '2025-09-11 12:46:32.624672'),
(39, 119, 'REPRESENTATIVE', '2026-03-25 19:57:44.476872'),
(39, 120, 'REPRESENTATIVE', '2025-10-02 22:29:25.106375'),
(40, 121, 'REPRESENTATIVE', '2025-08-14 09:21:41.943234'),
(40, 122, 'REPRESENTATIVE', '2025-08-09 10:55:22.493410'),
(40, 123, 'REPRESENTATIVE', '2026-01-29 16:43:19.878881'),
(41, 124, 'REPRESENTATIVE', '2025-07-10 18:33:06.890535'),
(42, 125, 'REPRESENTATIVE', '2026-05-12 04:36:34.369490'),
(44, 126, 'REPRESENTATIVE', '2026-06-17 02:13:24.566036'),
(45, 127, 'REPRESENTATIVE', '2026-02-15 09:23:06.720715'),
(46, 128, 'REPRESENTATIVE', '2026-06-08 12:18:23.395186'),
(46, 129, 'REPRESENTATIVE', '2025-12-07 14:19:33.467989'),
(47, 130, 'REPRESENTATIVE', '2025-07-08 20:28:54.742463'),
(48, 131, 'REPRESENTATIVE', '2026-04-29 02:37:09.601887'),
(50, 132, 'REPRESENTATIVE', '2025-08-02 20:38:28.365752'),
(50, 133, 'REPRESENTATIVE', '2026-01-06 10:09:58.657554');

-- Party Contacts
INSERT INTO party_contact (party_id, type, details) VALUES
(1, 'EMAIL', 'info@mccarthy-murphy.com'),
(1, 'PHONE', '+1-827-283-1906x423'),
(2, 'EMAIL', 'info@hubbardltd.com'),
(2, 'PHONE', '(293)218-3109x46240'),
(3, 'EMAIL', 'info@herreraltd.com'),
(4, 'EMAIL', 'info@garciasmithandthompson.com'),
(4, 'PHONE', '364.851.4008'),
(5, 'EMAIL', 'info@owensplc.com'),
(5, 'PHONE', '+1-994-322-0544x1160'),
(6, 'EMAIL', 'info@mitchellpattersonandriley.com'),
(6, 'PHONE', '818.677.0715x96785'),
(7, 'EMAIL', 'info@serranoltd.com'),
(8, 'EMAIL', 'info@garza-wilson.com'),
(8, 'PHONE', '9279007353'),
(9, 'EMAIL', 'info@smithgroup.com'),
(9, 'PHONE', '833-421-0685'),
(10, 'EMAIL', 'info@dennisplc.com'),
(10, 'PHONE', '6183619739'),
(11, 'EMAIL', 'info@garzahernandezandjames.com'),
(11, 'PHONE', '799-657-9253x814'),
(12, 'EMAIL', 'info@woodhenryandhuber.com'),
(12, 'PHONE', '(363)401-9812x643'),
(13, 'EMAIL', 'info@trangroup.com'),
(13, 'PHONE', '(469)279-7217x78563'),
(14, 'EMAIL', 'info@stoneplc.com'),
(14, 'PHONE', '(556)850-4995'),
(15, 'EMAIL', 'info@johnson-lynn.com'),
(15, 'PHONE', '4044174608'),
(16, 'EMAIL', 'info@alexanderrodgersandsmith.com'),
(16, 'PHONE', '(314)598-1385'),
(17, 'EMAIL', 'info@holt-solis.com'),
(17, 'PHONE', '292-252-4456x39769'),
(18, 'EMAIL', 'info@young-love.com'),
(18, 'PHONE', '389-925-6030'),
(19, 'EMAIL', 'info@hernandezsnowandsantos.com'),
(20, 'EMAIL', 'info@bell-graham.com'),
(20, 'PHONE', '706-269-1706x2619'),
(21, 'EMAIL', 'info@carterltd.com'),
(21, 'PHONE', '369.909.9581x225'),
(22, 'EMAIL', 'info@pittswilsonandrowe.com'),
(22, 'PHONE', '371-717-1426x81348'),
(23, 'EMAIL', 'info@spence-norris.com'),
(23, 'PHONE', '619-682-1900'),
(24, 'EMAIL', 'info@mayerwardandenglish.com'),
(24, 'PHONE', '453-410-0858'),
(25, 'EMAIL', 'info@young-taylor.com'),
(25, 'PHONE', '8398443412'),
(26, 'EMAIL', 'info@millerfosterandmartin.com'),
(26, 'PHONE', '(947)391-8728x879'),
(27, 'EMAIL', 'info@fosterbutlerandjohnson.com'),
(28, 'EMAIL', 'info@baker-thomas.com'),
(29, 'EMAIL', 'info@brownespinozaandpetersen.com'),
(30, 'EMAIL', 'info@millerbrownandgarcia.com'),
(30, 'PHONE', '8912013964'),
(31, 'EMAIL', 'info@salazarblairandgibson.com'),
(31, 'PHONE', '(956)591-5811x92616'),
(32, 'EMAIL', 'info@carrplc.com'),
(32, 'PHONE', '+1-745-859-3031x8052'),
(33, 'EMAIL', 'info@morahaleandbraun.com'),
(33, 'PHONE', '(563)423-6881'),
(34, 'EMAIL', 'info@hughesplc.com'),
(35, 'EMAIL', 'info@daltonbrockandthompson.com'),
(35, 'PHONE', '001-286-761-1315x0719'),
(36, 'EMAIL', 'info@paul-ryan.com'),
(36, 'PHONE', '+1-873-297-6262'),
(37, 'EMAIL', 'info@miller-wells.com'),
(37, 'PHONE', '+1-407-690-1801x522'),
(38, 'EMAIL', 'info@murray-king.com'),
(38, 'PHONE', '564-464-0277'),
(39, 'EMAIL', 'info@ramos-hardy.com'),
(39, 'PHONE', '(609)737-5344'),
(40, 'EMAIL', 'info@bishoppetersenandortiz.com'),
(40, 'PHONE', '+1-544-959-6230'),
(41, 'EMAIL', 'info@allenfrenchandgraham.com'),
(41, 'PHONE', '+1-543-747-7062x26582'),
(42, 'EMAIL', 'info@conleyedwardsandmayo.com'),
(42, 'PHONE', '001-702-999-3926'),
(43, 'EMAIL', 'info@blackwell-gutierrez.com'),
(44, 'EMAIL', 'info@wolfinc.com'),
(44, 'PHONE', '719.487.4524x526'),
(45, 'EMAIL', 'info@currywalkerandbrown.com'),
(45, 'PHONE', '(313)639-7900x3557'),
(46, 'EMAIL', 'info@gregorymosesandwhite.com'),
(47, 'EMAIL', 'info@johnsonrossandwhite.com'),
(47, 'PHONE', '001-460-841-6957'),
(48, 'EMAIL', 'info@watkins-gray.com'),
(48, 'PHONE', '870.995.4292x484'),
(49, 'EMAIL', 'info@obrienandersonandwilson.com'),
(49, 'PHONE', '001-453-905-1431x0214'),
(50, 'EMAIL', 'info@jonesmillerandsolis.com'),
(50, 'PHONE', '845-209-6438x415'),
(71, 'EMAIL', 'shane.cox@mccarthy-murphy.com'),
(71, 'PHONE', '(240)943-3517x702'),
(72, 'EMAIL', 'john.bowers@hubbardltd.com'),
(72, 'PHONE', '(594)442-2365'),
(73, 'EMAIL', 'joseph.powell@hubbardltd.com'),
(73, 'PHONE', '(446)656-8294x8121'),
(74, 'EMAIL', 'nicole.bowers@owensplc.com'),
(74, 'PHONE', '867.979.8577x7283'),
(75, 'EMAIL', 'david.smith@serranoltd.com'),
(75, 'PHONE', '425.322.6446x2969'),
(76, 'EMAIL', 'michael.castillo@serranoltd.com'),
(76, 'PHONE', '442.876.0418'),
(77, 'EMAIL', 'lee.mitchell@serranoltd.com'),
(78, 'EMAIL', 'joshua.mosley@garza-wilson.com'),
(78, 'PHONE', '503.714.4087'),
(79, 'EMAIL', 'edward.berg@dennisplc.com'),
(79, 'PHONE', '001-911-813-6647x3330'),
(80, 'EMAIL', 'michelle.richardson@dennisplc.com'),
(80, 'PHONE', '674.356.6842x708'),
(81, 'EMAIL', 'anthony.jones@garzahernandezandjames.com'),
(82, 'EMAIL', 'sonya.marquez@garzahernandezandjames.com'),
(82, 'PHONE', '247-330-0194'),
(83, 'EMAIL', 'kelly.bradford@woodhenryandhuber.com'),
(83, 'PHONE', '793.403.8991x2125'),
(84, 'EMAIL', 'dwayne.evans@woodhenryandhuber.com'),
(84, 'PHONE', '(670)244-9912x916'),
(85, 'EMAIL', 'janice.bautista@trangroup.com'),
(86, 'EMAIL', 'melanie.carr@stoneplc.com'),
(86, 'PHONE', '+1-397-249-9715x274'),
(87, 'EMAIL', 'jesse.sanchez@johnson-lynn.com'),
(87, 'PHONE', '(752)691-8936x423'),
(88, 'EMAIL', 'shawn.sullivan@johnson-lynn.com'),
(88, 'PHONE', '+1-291-974-9891x396'),
(89, 'EMAIL', 'ryan.harrison@alexanderrodgersandsmith.com'),
(89, 'PHONE', '303-655-1695x48626'),
(90, 'EMAIL', 'christine.fields@alexanderrodgersandsmith.com'),
(91, 'EMAIL', 'janet.miller@holt-solis.com'),
(91, 'PHONE', '2567394370'),
(92, 'EMAIL', 'jacqueline.kramer@holt-solis.com'),
(93, 'EMAIL', 'robin.padilla@holt-solis.com'),
(94, 'EMAIL', 'laura.peterson@pittswilsonandrowe.com'),
(94, 'PHONE', '001-557-897-5962x49333'),
(95, 'EMAIL', 'erik.gomez@spence-norris.com'),
(95, 'PHONE', '(303)481-8535'),
(96, 'EMAIL', 'alexandra.peck@spence-norris.com'),
(96, 'PHONE', '7099164612'),
(97, 'EMAIL', 'kyle.herrera@spence-norris.com'),
(97, 'PHONE', '001-346-312-3536x613'),
(98, 'EMAIL', 'sharon.rivers@mayerwardandenglish.com'),
(98, 'PHONE', '(718)971-9516x5313'),
(99, 'EMAIL', 'mr..zimmerman@mayerwardandenglish.com'),
(99, 'PHONE', '(538)745-8498'),
(100, 'EMAIL', 'jessica.moss@young-taylor.com'),
(101, 'EMAIL', 'david.gonzalez@young-taylor.com'),
(101, 'PHONE', '001-914-841-5054'),
(102, 'EMAIL', 'mrs..perry@young-taylor.com'),
(102, 'PHONE', '3554183688'),
(103, 'EMAIL', 'rachel.marshall@millerfosterandmartin.com'),
(103, 'PHONE', '001-505-488-6491'),
(104, 'EMAIL', 'jacqueline.smith@millerfosterandmartin.com'),
(104, 'PHONE', '(398)705-7890x3840'),
(105, 'EMAIL', 'nancy.ward@millerfosterandmartin.com'),
(105, 'PHONE', '(926)570-4579x780'),
(106, 'EMAIL', 'aaron.bailey@baker-thomas.com'),
(106, 'PHONE', '776-628-1563x6195'),
(107, 'EMAIL', 'jimmy.bennett@baker-thomas.com'),
(108, 'EMAIL', 'jennifer.md@brownespinozaandpetersen.com'),
(108, 'PHONE', '875.444.2251x1535'),
(109, 'EMAIL', 'tonya.yang@carrplc.com'),
(109, 'PHONE', '248-942-1479x18045'),
(110, 'EMAIL', 'shannon.sullivan@morahaleandbraun.com'),
(110, 'PHONE', '922.705.7174x45503'),
(111, 'EMAIL', 'jasmine.mccormick@morahaleandbraun.com'),
(111, 'PHONE', '(689)388-3955'),
(112, 'EMAIL', 'meghan.walker@hughesplc.com'),
(112, 'PHONE', '(335)783-5789x39224'),
(113, 'EMAIL', 'brianna.walker@hughesplc.com'),
(113, 'PHONE', '001-308-919-9808x723'),
(114, 'EMAIL', 'ronald.norton@hughesplc.com'),
(114, 'PHONE', '810-780-2444x96935'),
(115, 'EMAIL', 'ronald.henderson@paul-ryan.com'),
(115, 'PHONE', '(763)858-0763x0926'),
(116, 'EMAIL', 'betty.hernandez@murray-king.com'),
(116, 'PHONE', '524-261-7191'),
(117, 'EMAIL', 'christopher.davis@murray-king.com'),
(118, 'EMAIL', 'sean.wade@ramos-hardy.com'),
(118, 'PHONE', '726.762.1920'),
(119, 'EMAIL', 'kimberly.morris@ramos-hardy.com'),
(119, 'PHONE', '(515)477-0433x9617'),
(120, 'EMAIL', 'brianna.robertson@ramos-hardy.com'),
(120, 'PHONE', '(592)723-2511'),
(121, 'EMAIL', 'julia.simmons@bishoppetersenandortiz.com'),
(121, 'PHONE', '5722651554'),
(122, 'EMAIL', 'michael.henry@bishoppetersenandortiz.com'),
(122, 'PHONE', '+1-457-378-9742x335'),
(123, 'EMAIL', 'melissa.blackwell@bishoppetersenandortiz.com'),
(123, 'PHONE', '698-215-1553x9837'),
(124, 'EMAIL', 'valerie.bennett@allenfrenchandgraham.com'),
(124, 'PHONE', '326.757.9880x1283'),
(125, 'EMAIL', 'michelle.wright@conleyedwardsandmayo.com'),
(125, 'PHONE', '+1-577-798-0374x8984'),
(126, 'EMAIL', 'jamie.roberson@wolfinc.com'),
(126, 'PHONE', '001-963-713-4883x33243'),
(127, 'EMAIL', 'edward.cabrera@currywalkerandbrown.com'),
(127, 'PHONE', '(468)504-6928'),
(128, 'EMAIL', 'michael.harris@gregorymosesandwhite.com'),
(128, 'PHONE', '+1-895-478-8208'),
(129, 'EMAIL', 'amanda.miles@gregorymosesandwhite.com'),
(129, 'PHONE', '493-761-5518x2717'),
(130, 'EMAIL', 'phillip.collins@johnsonrossandwhite.com'),
(130, 'PHONE', '422.900.3258'),
(131, 'EMAIL', 'thomas.frazier@watkins-gray.com'),
(131, 'PHONE', '+1-404-587-2170'),
(132, 'EMAIL', 'dennis.webb@jonesmillerandsolis.com'),
(132, 'PHONE', '001-804-418-3385x51623'),
(133, 'EMAIL', 'julia.md@jonesmillerandsolis.com'),
(133, 'PHONE', '281.829.3768x5945');

-- Contractor Addresses
INSERT INTO address (address_id, party_id, street_address, city, country, postal_code, address_type) VALUES
('7a43eff3-0361-4e8d-849e-00df7a66158d', 1, '1131 Bishop Ridge', 'West Jeff', 'Guinea-Bissau', '19756', 'OTHER'),
('7286d57c-6d8a-4dc1-8d44-5656d841b07d', 1, '748 Jessica Place', 'Larryton', 'Ethiopia', '56080', 'CORPORATE'),
('cb785b56-3a04-456a-9a9c-744a4b1d4b3e', 2, '568 Tanner Fall Suite 035', 'Dianetown', 'Uruguay', '44332', 'CORPORATE'),
('ed62995e-12b5-44d9-acde-d501a074a562', 3, '1606 Yvonne Key', 'Port Brianbury', 'Reunion', '99421', 'BILLING'),
('9fd79de0-b3bb-410e-ba99-03f3a786b779', 4, '53049 Jason Crossing Apt. 339', 'Danielfort', 'Poland', '88011', 'SHIPPING'),
('dfe073e3-db8b-43ab-b3f1-6958a0f16e0d', 5, '3207 Bradley Hill Apt. 064', 'East Emilyfurt', 'North Macedonia', '85076', 'CORPORATE'),
('a21ee832-1a38-4cd4-b621-a3bdab0977e2', 6, '47956 Smith Views Suite 538', 'New Janet', 'Grenada', '47687', 'BILLING'),
('0551e604-fc6b-49ad-842d-393f2ded1b9e', 6, '9979 Carrie Turnpike', 'South William', 'Korea', '80485', 'CORPORATE'),
('4dbdfcec-2b7c-4a32-a94b-e3a6c802a263', 7, '4179 Luis Court', 'Port Monicaview', 'Kiribati', '87228', 'SHIPPING'),
('198e6239-8180-4f7f-8d9a-5c9f2704585d', 8, '3514 Allen Mountain', 'Jonside', 'Palestinian Territory', '35090', 'OTHER'),
('3a5d2075-70c4-4f15-8f20-795ab08fdc2f', 9, '403 Wolfe Radial Suite 618', 'Veronicastad', 'Chad', '68301', 'SHIPPING'),
('20dfb824-63df-440a-a12e-e9841f95751b', 9, '49941 Jenkins Islands Suite 359', 'North Sean', 'Mayotte', '74423', 'OTHER'),
('16a16d59-7268-4c45-a3d9-b55349ba8eee', 10, '30685 Dunn Expressway', 'Mackchester', 'Bahamas', '86219', 'OTHER'),
('f12ad97a-6e67-4896-a332-8e5406b292a6', 10, '63573 Hill Corner Apt. 698', 'North Adrianport', 'United States Virgin Islands', '07909', 'BILLING'),
('c3569c87-29f4-42c5-84a7-6e13ae808284', 11, '8660 Holland Brooks', 'East Bernard', 'Niger', '15120', 'SHIPPING'),
('86dd1999-da21-4d8e-9abf-49f803e2006b', 12, '42094 Jacob Summit Apt. 558', 'New Davidmouth', 'Ecuador', '30898', 'OTHER'),
('22828a71-6323-46db-9222-02e4c8ab48cf', 13, '98188 Monroe Heights', 'Laurenstad', 'Mauritius', '84346', 'BILLING'),
('45f7bd7a-a259-42e8-a57b-9c43511842b4', 14, '61160 Jamie Port', 'Donaldburgh', 'Ukraine', '71045', 'OTHER'),
('d8818719-190d-41f7-88df-fc25e6e9d3e3', 14, '81577 Collins Mission', 'East Emilymouth', 'Iceland', '68024', 'SHIPPING'),
('4ec7a53d-3dd1-43ae-bcfd-989bcba73e56', 15, '972 Daniel Place', 'Carlosfort', 'South Georgia and the South Sandwich Islands', '05618', 'SHIPPING'),
('dc2bd9d9-e7e9-46e0-a244-5d358d0da60e', 16, '57678 David Trail Suite 847', 'West Karen', 'Sudan', '24144', 'BILLING'),
('02f35863-a31c-47ed-b6ac-d9961d8e097d', 16, '469 Cox Ports', 'South Amandamouth', 'Saint Pierre and Miquelon', '67713', 'CORPORATE'),
('9ebe9b01-7113-4d05-9bb1-a4fd3b49c75c', 17, '437 Potts Highway', 'West Cynthia', 'Christmas Island', '06450', 'CORPORATE'),
('7ec7e6e0-889b-427c-b601-f521c3c4571d', 17, '621 Brett Lock Apt. 303', 'Johnsonton', 'Wallis and Futuna', '13565', 'BILLING'),
('5cddfedc-99b5-4ac9-b60d-11361b7082dd', 18, '988 Craig Orchard', 'West Michael', 'Switzerland', '36114', 'OTHER'),
('106e6192-fb43-4873-9917-5c1ab83a8969', 19, '3447 Jared Fields', 'Johnburgh', 'Swaziland', '04287', 'SHIPPING'),
('776b5eca-37c3-42a5-9354-bc2d2c5a07b4', 19, '63255 Danielle Forks', 'New Robert', 'Montenegro', '07089', 'BILLING'),
('c037e51c-7ef2-4f0d-96b3-5f8acdb4ebbf', 20, '01356 Sabrina Parkways', 'Sarahbury', 'Italy', '01376', 'BILLING'),
('44fdbb29-979d-4447-a899-7958e15eabb6', 21, '1621 Jessica Crescent Apt. 986', 'Beverlymouth', 'Dominica', '48024', 'BILLING'),
('64adedf9-6d83-42cd-9527-82cdd67b5050', 22, '85169 Debra Rest', 'North Jacobshire', 'Canada', '34836', 'SHIPPING'),
('4490c706-3839-4f07-bd65-4c67238fb95f', 23, '156 Martin Islands Suite 455', 'Davidstad', 'Botswana', '16362', 'BILLING'),
('bfcdf8a6-61f1-4fc9-b6c8-047b7d348c95', 23, '7467 Hunter Wells', 'West Dannyfurt', 'Mozambique', '91261', 'SHIPPING'),
('5bd40060-06cc-4e16-9491-3634be5c5bcc', 23, '980 Heidi Meadows', 'Gonzalezmouth', 'Vietnam', '41110', 'CORPORATE'),
('356944dc-ebc9-42c4-bc9a-ca2604bd90b2', 24, '628 Emily Shore Apt. 618', 'Colleenchester', 'Gambia', '39886', 'SHIPPING'),
('5286b1e4-b9ba-43a9-8d60-caf4410a74ef', 24, '90865 Nguyen Islands', 'East Ricardomouth', 'Ethiopia', '76290', 'OTHER'),
('ac502deb-1fed-4fda-95ff-fb00bef44263', 24, '569 Jamie Harbors Apt. 168', 'Claudiastad', 'Nepal', '62804', 'CORPORATE'),
('61d71492-0d7f-42ae-8814-2c9c6dffe796', 25, '737 Anderson Mountain', 'Jordanton', 'Indonesia', '57038', 'BILLING'),
('4a384761-84d4-4d87-8b1a-7d1f01b9ba44', 25, '93782 Stark Locks Suite 463', 'Rebekahville', 'Senegal', '45850', 'OTHER'),
('8828f9e3-b9a6-4eb8-8498-767fd1de796e', 25, '007 Mccormick Course', 'West Brianna', 'Afghanistan', '30063', 'CORPORATE'),
('a87aedd1-87a1-40a2-bf05-aa9415db6a5b', 26, '97554 Luis Crest Apt. 569', 'Olivershire', 'Spain', '35942', 'OTHER'),
('5004151e-c1bb-411e-82bb-7dba32131b75', 27, '87616 Andrea Roads', 'Alexanderburgh', 'French Southern Territories', '56872', 'CORPORATE'),
('8d37d052-e5ab-4fb5-94f0-b537755a7648', 28, '5396 Beck Plaza', 'Patrickbury', 'Oman', '50732', 'BILLING'),
('ea3d8118-f0bb-4e07-8213-c5a6439bd68b', 29, '1131 Ford Port', 'Kristinastad', 'Niger', '64897', 'BILLING'),
('a2dfc31c-00d5-45ea-9bef-53bfabe221c4', 29, '107 Leonard Tunnel Suite 969', 'Gloverport', 'Chad', '71473', 'OTHER'),
('333ef352-2374-430f-9935-b109da5135b7', 30, '9668 Ruiz Fall', 'South Tracyburgh', 'Tajikistan', '71043', 'BILLING'),
('d3d71400-abc6-4bca-8398-dadf32a08f44', 31, '5868 Sue Burgs', 'Lake Dana', 'Northern Mariana Islands', '93936', 'OTHER'),
('7500e537-7033-4eb3-9b02-b4da6edc5ec1', 32, '88876 Ryan Lane', 'Harperstad', 'Congo', '55488', 'CORPORATE'),
('b34ead6e-4cce-44a9-ab6e-937cc413d079', 33, '99750 Reeves Divide Suite 023', 'Joshuatown', 'Somalia', '16924', 'SHIPPING'),
('9cc5aec4-9ffc-4270-8ae6-ddde881d5339', 33, '1892 Hooper Locks Suite 347', 'South Tamara', 'Guinea-Bissau', '62923', 'BILLING'),
('58ac1296-04c6-4a3b-a487-9d10c044b4cb', 34, '20309 Daniel Wells Suite 505', 'West Margaret', 'Norway', '10881', 'OTHER'),
('3a3c694a-c74a-420d-ba9a-bb1d928c5f08', 35, '2452 Blair Mall Apt. 288', 'North Shawn', 'Sao Tome and Principe', '69160', 'OTHER'),
('b383010e-cf7c-4ae7-9b06-e7a1c3300d82', 36, '771 Devon Junctions', 'Goodwinborough', 'Kenya', '51817', 'SHIPPING'),
('a2b8f111-7b04-4576-b616-40f9657949ac', 37, '981 Jason Manor Apt. 021', 'Thomasmouth', 'Oman', '67566', 'SHIPPING'),
('077c1e1e-e5eb-48c0-8ed2-6571de0a900f', 37, '41650 Jared Fords', 'North Kelly', 'Paraguay', '26208', 'OTHER'),
('d7ab20b7-b671-470f-8d97-d2b27bad046f', 37, '32039 Clay Rapids', 'Stephaniechester', 'Turks and Caicos Islands', '38472', 'BILLING'),
('f39b26fd-1639-4b7f-aa27-1f3bed938259', 38, '7823 Donald Ridge', 'Stevenfurt', 'Ghana', '69571', 'BILLING'),
('1164275c-019e-49f8-a090-f48db4f03468', 38, '224 Jamie Islands', 'East Jenny', 'Iran', '45887', 'CORPORATE'),
('bec0ed35-b0d6-4657-8372-5a4d3176bcff', 38, '66322 Bryan Skyway Apt. 198', 'Philliphaven', 'China', '49625', 'SHIPPING'),
('0af85aaf-b5d0-4d01-9265-ddb9ac029afd', 39, '86657 Reyes Passage Apt. 305', 'Parkerstad', 'Togo', '28435', 'SHIPPING'),
('599ee3af-32a4-46f2-bfb3-12521ada83e6', 40, '7442 Campos Grove Suite 659', 'Juliemouth', 'Jamaica', '95338', 'CORPORATE'),
('ce975d40-cb7a-40a4-973d-27bf02c5e32f', 41, '73201 Dickson Manors', 'Port Joe', 'Cocos (Keeling) Islands', '09689', 'SHIPPING'),
('ed930d27-be3a-4f5e-86a9-aa5969538f23', 42, '47807 John Road Suite 724', 'West Deborahton', 'Saint Lucia', '31331', 'CORPORATE'),
('d7e2d4b6-0f01-4496-8bab-ea102929c784', 43, '238 Todd Corners Suite 323', 'Ashleychester', 'Israel', '56914', 'SHIPPING'),
('989028c6-f5d8-4654-b21c-defc96c9c5dc', 44, '0349 Kathryn Fort Suite 506', 'Stephaniefurt', 'Syrian Arab Republic', '20151', 'OTHER'),
('643376f9-5115-4488-b5e8-45e9b081982e', 45, '2191 Colton Estate Suite 328', 'Jessicaland', 'Western Sahara', '99113', 'OTHER'),
('ac8b5f46-2258-4785-8f52-89d10bc1cf7d', 46, '551 Robinson Course Suite 395', 'Denniston', 'Azerbaijan', '67117', 'SHIPPING'),
('7cdcff57-b647-4dd3-a5ef-1739ac35fc18', 47, '820 Ryan Union', 'Moralesfurt', 'Thailand', '27401', 'CORPORATE'),
('a83685b5-abb3-4f16-bf7b-b38f715629df', 47, '9965 Shaffer Mill Apt. 775', 'Brandonton', 'Northern Mariana Islands', '06255', 'SHIPPING'),
('0fdfb218-7b06-414c-9288-a4a7c3c608bc', 48, '7817 Tyler Forges Apt. 604', 'East Michaelhaven', 'Sweden', '30037', 'BILLING'),
('c87bc39f-4081-414f-828e-52739db17d6c', 49, '2442 Barnett Meadows Apt. 703', 'West Ambershire', 'Syrian Arab Republic', '42407', 'SHIPPING'),
('f3582c62-e2e4-4457-a67d-6609a1d21c3f', 50, '316 Stephanie Passage', 'West Carol', 'Dominican Republic', '32738', 'SHIPPING'),
('c6fdfa29-8961-42e5-9a66-5cf53aac468c', 50, '21321 Melissa Camp', 'South Kylemouth', 'Saint Pierre and Miquelon', '16529', 'OTHER'),
('5133ae3c-96ca-4d48-8386-210d261bb359', 50, '6435 Julian Knolls Apt. 535', 'New David', 'Thailand', '79029', 'BILLING');

-- Employee Parties
INSERT INTO party (party_id, name, data, created_at, updated_at) VALUES
(51, 'Marissa Sloan', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-10-31 12:02:09', '2026-02-09 17:06:37'),
(52, 'Jacob Kim', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2025-02-06 13:06:47', '2025-07-23 04:49:23'),
(53, 'Vanessa Scott', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-05-20 03:46:36', '2026-05-25 23:11:07'),
(54, 'Christina Sanchez', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-10-31 02:31:41', '2025-11-21 11:11:27'),
(55, 'Scott Brandt', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2025-03-27 00:59:54', '2025-08-11 04:39:13'),
(56, 'Ashley Hernandez', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2021-07-28 13:27:44', '2026-01-20 18:26:44'),
(57, 'Lindsay Stewart', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2021-08-11 02:15:40', '2025-12-23 02:15:58'),
(58, 'Vanessa Anderson', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2021-07-21 21:36:28', '2026-04-22 11:19:30'),
(59, 'Eric Jenkins', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2025-06-11 18:17:31', '2026-03-27 09:13:34'),
(60, 'Brenda Harris', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-12-08 23:31:12', '2025-10-12 19:37:21'),
(61, 'Sherri Brown', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-07-27 04:51:12', '2025-10-09 08:54:21'),
(62, 'James Lowe', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2025-05-03 04:58:47', '2026-04-13 05:50:15'),
(63, 'Emily Williams', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-05-05 01:42:54', '2025-12-31 19:00:47'),
(64, 'Jacob Perez', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2023-04-22 01:38:27', '2026-04-07 16:27:55'),
(65, 'Carlos Odonnell', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-06-03 03:07:02', '2026-02-23 11:17:38'),
(66, 'Richard Thomas', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2025-06-04 05:31:00', '2026-06-29 00:27:27'),
(67, 'Christopher Garcia', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-06-17 06:52:58', '2025-12-19 12:02:39'),
(68, 'Nancy George', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2021-09-06 00:05:46', '2026-04-24 10:28:01'),
(69, 'Mary Bowman', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-05-28 12:09:56', '2026-01-19 19:39:01'),
(70, 'Stacy Espinoza', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-08-11 19:45:33', '2025-08-11 22:27:34');

-- Employee Addresses
INSERT INTO address (address_id, party_id, street_address, city, country, postal_code, address_type) VALUES
('e715ca19-6fc1-4af2-84bb-5a9adbb4a08e', 51, '1267 Frey Parkway Suite 370', 'Robinsonchester', 'Mauritius', '27327', 'PERSONAL'),
('e405d97c-cf9a-48b2-b9aa-f5388715602c', 52, '770 Carol Coves Suite 167', 'Welchfort', 'Kazakhstan', '46644', 'OTHER'),
('7a3c11d9-07a6-4461-9ce1-2c2d7aa30a50', 53, '0080 Christopher Ramp Suite 009', 'East Todd', 'Guatemala', '88794', 'OTHER'),
('87dd6fa9-60a6-4b63-8422-01ea9269d1e2', 54, '512 Samantha Road', 'North Trevorland', 'Ecuador', '64684', 'PERSONAL'),
('5a415d13-e14c-43b1-8e9b-bd8ae19f3bee', 55, '3145 Vasquez Mountains Suite 748', 'South Hannahville', 'Niger', '69419', 'PERSONAL'),
('ca1a098b-4a56-4cda-90c2-61ee0a6dfa03', 56, '2477 Steven Underpass Suite 291', 'East Deborah', 'Brazil', '34704', 'OTHER'),
('00dc76a1-2692-45c0-b6ee-328c04d32512', 57, '91447 Ray Walk Suite 458', 'Tylermouth', 'Guam', '24962', 'OTHER'),
('671c3b81-5a0c-4382-81e8-9ed966789d7e', 58, '9357 Johnson Via', 'Lake Jacob', 'American Samoa', '90713', 'PERSONAL'),
('6c83700d-b387-4318-9ba2-42befeb67257', 59, '375 Wang Plaza', 'Henrychester', 'Swaziland', '44618', 'OTHER'),
('2b0ea5eb-e264-4ff6-8429-53da141c28c8', 59, '2583 Wyatt Plaza', 'South Victoriachester', 'Guyana', '14064', 'PERSONAL'),
('a79daceb-1d14-4b50-836a-4599e8d03009', 60, '297 Fernandez Creek', 'Austinmouth', 'Mali', '07480', 'OTHER'),
('0e3c300c-a8bb-4877-8739-7f2c838b805c', 61, '9854 Ashley Garden', 'West Katherine', 'Sweden', '18467', 'PERSONAL'),
('5c8c51a2-14e9-4b19-a63c-80814aa73f5f', 62, '997 Pham Turnpike Apt. 940', 'Port Howard', 'Cambodia', '58184', 'OTHER'),
('aac02aac-7bc6-43d3-acc7-881656f76b36', 62, '7489 Michael Pines', 'Franklinport', 'Bahamas', '71840', 'PERSONAL'),
('aae60c9c-d934-419d-812c-2c61d25ec5ac', 63, '20293 John Throughway', 'Port Yolanda', 'Hong Kong', '83145', 'PERSONAL'),
('074dc928-73f1-4b93-85b5-0262b934da2e', 64, '19849 Ruiz Passage Suite 991', 'Holtton', 'Puerto Rico', '71035', 'OTHER'),
('870be87b-dd60-4553-9603-06ff0e425321', 64, '3136 Powell Fort Suite 627', 'Gonzalezborough', 'Burkina Faso', '94254', 'PERSONAL'),
('41ca96ed-efb2-4231-9c32-22b8800bab94', 65, '390 Michelle Stream Suite 857', 'Port Kathryn', 'Tuvalu', '90184', 'PERSONAL'),
('1b9c9e40-a8f9-4c23-a3bc-a2d3474f6ea7', 66, '790 Ray Way', 'Port Williamside', 'Micronesia', '47823', 'OTHER'),
('f3ecb93d-b94b-4e83-8fac-428a136caf73', 66, '2764 Patterson Tunnel Apt. 174', 'North Carlos', 'Saint Kitts and Nevis', '91524', 'PERSONAL'),
('19c53bb1-cd6d-4bcc-9aff-d3d251939a1d', 67, '412 Lauren Lake Apt. 799', 'West Jon', 'French Guiana', '21849', 'PERSONAL'),
('0638d3a0-51e6-45db-9c4e-f4eba4a45d6d', 68, '5425 Monroe Avenue Apt. 243', 'Josephtown', 'Ghana', '85161', 'OTHER'),
('dd46d9f9-82ce-4cd3-b38c-963bb47af90c', 68, '76943 Jesus Coves', 'Bennetthaven', 'North Macedonia', '66403', 'PERSONAL'),
('10899f83-e37f-4edb-9927-475008111a64', 69, '563 Gutierrez Points Suite 268', 'South Davidfurt', 'Mozambique', '10452', 'OTHER'),
('562f2d44-97db-4487-a186-57ea8d2e5d99', 70, '670 Smith Fall Apt. 017', 'Port Denniston', 'United States Minor Outlying Islands', '21548', 'PERSONAL'),
('b23e10a5-97b0-42e1-a6cc-a6bbfcf45420', 70, '1954 Hawkins Road', 'Longbury', 'Libyan Arab Jamahiriya', '91786', 'OTHER');

-- Employee Contacts
INSERT INTO party_contact (party_id, type, details) VALUES
(51, 'EMAIL', 'peter58@example.com'),
(51, 'PHONE', '(409)466-3727'),
(52, 'EMAIL', 'deanisabel@example.org'),
(52, 'PHONE', '(908)458-4212'),
(53, 'EMAIL', 'hilltabitha@example.net'),
(53, 'PHONE', '389.940.7315x7260'),
(54, 'EMAIL', 'lbanks@example.com'),
(54, 'PHONE', '216.688.8250x4687'),
(55, 'EMAIL', 'nicolegarcia@example.com'),
(55, 'PHONE', '(535)328-1982'),
(56, 'EMAIL', 'timothy41@example.net'),
(56, 'PHONE', '500.895.2066x816'),
(57, 'EMAIL', 'rroberts@example.com'),
(57, 'PHONE', '(776)716-8594x029'),
(58, 'EMAIL', 'ubeck@example.com'),
(58, 'PHONE', '+1-460-578-1275x686'),
(59, 'EMAIL', 'adriandeleon@example.net'),
(59, 'PHONE', '928.318.6597x06655'),
(60, 'EMAIL', 'delgadonicole@example.com'),
(60, 'PHONE', '4432720671'),
(61, 'EMAIL', 'stacey65@example.net'),
(61, 'PHONE', '592.682.1710'),
(62, 'EMAIL', 'nicholas13@example.org'),
(62, 'PHONE', '697-592-7732x16530'),
(63, 'EMAIL', 'lanedaniel@example.org'),
(63, 'PHONE', '416.222.9766'),
(64, 'EMAIL', 'shannondillon@example.com'),
(64, 'PHONE', '231.482.6123'),
(65, 'EMAIL', 'brandi17@example.net'),
(65, 'PHONE', '+1-275-426-0896x2280'),
(66, 'EMAIL', 'johnsonvictoria@example.net'),
(66, 'PHONE', '545.341.9098x180'),
(67, 'EMAIL', 'mosleylauren@example.net'),
(67, 'PHONE', '+1-664-955-5141'),
(68, 'EMAIL', 'larsonchelsea@example.com'),
(68, 'PHONE', '001-710-664-0064x74224'),
(69, 'EMAIL', 'alexisscott@example.net'),
(69, 'PHONE', '(772)334-7214'),
(70, 'EMAIL', 'woodkerry@example.com'),
(70, 'PHONE', '001-807-853-2892x496');

-- Party Roles
INSERT INTO party_role (party_id, role_id, assigned_date) VALUES
(51, 5, '2023-11-08 23:26:38'),
(52, 4, '2026-04-10 16:01:17'),
(53, 5, '2025-07-29 03:28:56'),
(54, 3, '2025-11-18 09:50:17'),
(55, 5, '2026-03-04 10:56:30'),
(56, 5, '2025-05-15 16:19:52'),
(57, 5, '2025-05-22 10:08:27'),
(58, 4, '2024-12-10 19:26:05'),
(58, 5, '2025-02-28 19:39:07'),
(59, 3, '2026-01-22 08:22:08'),
(59, 5, '2026-04-03 06:40:33'),
(60, 4, '2024-01-07 02:22:23'),
(61, 3, '2024-02-23 08:41:12'),
(62, 5, '2026-04-02 04:51:30'),
(63, 5, '2022-09-30 06:59:07'),
(64, 5, '2023-07-28 15:39:50'),
(65, 5, '2023-03-30 13:01:55'),
(66, 5, '2026-04-26 06:20:02'),
(67, 5, '2024-03-12 22:21:50'),
(68, 5, '2023-04-16 19:44:16'),
(68, 1, '2023-03-20 16:35:41'),
(69, 4, '2025-01-16 15:53:53'),
(70, 3, '2025-02-16 16:45:00'),
(70, 5, '2025-10-31 22:10:06');

-- Employee Warehouses
INSERT INTO employee_warehouse (party_id, warehouse_id, assigned_from, assigned_until) VALUES
(51, 1, '2022-10-31 12:02:09', NULL),
(52, 1, '2025-02-06 13:06:47', NULL),
(53, 1, '2024-05-20 03:46:36', NULL),
(54, 1, '2024-10-31 02:31:41', NULL),
(55, 1, '2025-03-27 00:59:54', NULL),
(56, 1, '2021-07-28 13:27:44', NULL),
(57, 1, '2021-08-11 02:15:40', NULL),
(58, 1, '2021-07-21 21:36:28', NULL),
(59, 1, '2025-06-11 18:17:31', NULL),
(60, 1, '2022-12-08 23:31:12', NULL),
(61, 1, '2022-07-27 04:51:12', NULL),
(62, 1, '2025-05-03 04:58:47', NULL),
(63, 1, '2022-05-05 01:42:54', NULL),
(64, 1, '2023-04-22 01:38:27', NULL),
(65, 1, '2022-06-03 03:07:02', NULL),
(66, 1, '2025-06-04 05:31:00', NULL),
(67, 1, '2022-06-17 06:52:58', NULL),
(68, 1, '2021-09-06 00:05:46', NULL),
(69, 1, '2022-05-28 12:09:56', NULL),
(70, 1, '2024-08-11 19:45:33', NULL);

-- Cargo Event Types
INSERT INTO cargo_event_type (event_type_id, name, description) VALUES
(1, 'RECEIVED', 'Cargo received at warehouse'),
(2, 'MOVED', 'Cargo moved to another shelf'),
(3, 'DISPATCHED', 'Cargo dispatched from warehouse'),
(4, 'DAMAGED', 'Cargo found damaged'),
(5, 'LOST', 'Cargo missing or lost'),
(6, 'CONTRACTOR_CONTACT', 'Contact with contractor regarding storage'),
(7, 'QUALITY_ISSUE', 'Quality-related issue reported'),
(8, 'SAFETY_INCIDENT', 'Safety or accident incident reported');

-- Zones
INSERT INTO zone (zone_id, warehouse_id, name, description) VALUES
(1, 1, 'Bulk Storage Area', 'Area for storing large quantities of goods, usually on pallets.'),
(2, 1, 'Receiving Area', 'Zone designated for unloading and inspecting incoming goods.'),
(3, 1, 'Picking Area', 'Zone where items are picked to fulfill orders.'),
(4, 1, 'Packing Area', 'Area for packing picked items and preparing them for shipment.'),
(5, 1, 'Shipping Area', 'Zone for staging and loading outbound shipments.'),
(6, 1, 'Returns Area', 'Designated space for processing returned goods.'),
(7, 1, 'Quarantine/Inspection Area', 'Area for holding goods pending inspection or quality checks.');

-- Aisles
INSERT INTO aisle (aisle_id, zone_id, label, width, width_unit) VALUES
(1, 1, 'Aisle-1', 300, 'cm'),
(2, 1, 'Aisle-2', 350, 'cm'),
(3, 1, 'Aisle-3', 250, 'cm'),
(4, 1, 'Aisle-4', 200, 'cm'),
(5, 1, 'Aisle-5', 300, 'cm'),
(6, 1, 'Aisle-6', 300, 'cm'),
(7, 1, 'Aisle-7', 300, 'cm');

-- Racks
INSERT INTO rack (rack_id, aisle_id, label, max_height, height_unit) VALUES
(1, 1, 'R-001', 450, 'cm'),
(2, 2, 'R-002', 400, 'cm'),
(3, 3, 'R-003', 450, 'cm'),
(4, 4, 'R-004', 350, 'cm'),
(5, 5, 'R-005', 350, 'cm'),
(6, 6, 'R-006', 500, 'cm'),
(7, 7, 'R-007', 450, 'cm'),
(8, 1, 'R-008', 500, 'cm'),
(9, 2, 'R-009', 350, 'cm'),
(10, 3, 'R-010', 350, 'cm');

-- Shelves
INSERT INTO shelf (shelf_id, rack_id, level, max_weight, max_volume) VALUES
(1, 1, '1', 1080, 9),
(2, 2, '2', 726, 13),
(3, 3, '3', 698, 10),
(4, 4, '4', 1178, 15),
(5, 5, '1', 1105, 7),
(6, 6, '2', 704, 8),
(7, 7, '3', 733, 10),
(8, 8, '4', 1002, 5),
(9, 9, '1', 618, 9),
(10, 10, '2', 647, 11),
(11, 1, '3', 1177, 9),
(12, 2, '4', 1177, 9),
(13, 3, '1', 985, 8),
(14, 4, '2', 1113, 9),
(15, 5, '3', 677, 10);

-- Storage Requests
INSERT INTO storage_request (request_id, warehouse_id, issuing_party_id, requested_entry_date, requested_exit_date, status, decisive_party_id, decision_date) VALUES
(1, 1, 40, '2026-07-21 16:32:44', '2026-08-18 16:32:44', 'ACCEPTED', 66, '2026-07-20 16:32:44'),
(2, 1, 42, '2026-07-11 03:42:28', '2026-08-01 03:42:28', 'REJECTED', 65, '2026-07-09 03:42:28'),
(3, 1, 17, '2026-07-26 07:37:52', '2026-08-22 07:37:52', 'ACCEPTED', 52, '2026-07-21 07:37:52'),
(4, 1, 81, '2026-06-25 18:53:43', '2026-07-22 18:53:43', 'ACCEPTED', 69, '2026-06-24 18:53:43'),
(5, 1, 2, '2026-07-30 07:33:06', '2026-08-05 07:33:06', 'REJECTED', 52, '2026-07-28 07:33:06'),
(6, 1, 31, '2026-07-28 08:15:24', '2026-08-15 08:15:24', 'PENDING', NULL, NULL),
(7, 1, 19, '2026-06-18 00:50:32', '2026-07-13 00:50:32', 'REJECTED', 60, '2026-06-17 00:50:32'),
(8, 1, 128, '2026-06-18 00:34:39', '2026-07-07 00:34:39', 'REJECTED', 62, '2026-06-15 00:34:39'),
(9, 1, 1, '2026-07-25 05:09:33', '2026-08-23 05:09:33', 'REJECTED', 60, '2026-07-24 05:09:33'),
(10, 1, 25, '2026-07-22 04:26:16', '2026-08-01 04:26:16', 'REJECTED', NULL, '2026-07-22 04:26:16'),
(11, 1, 30, '2026-06-28 08:34:07', '2026-07-21 08:34:07', 'ACCEPTED', 60, '2026-06-26 08:34:07'),
(12, 1, 13, '2026-06-03 20:43:54', '2026-07-02 20:43:54', 'ACCEPTED', 69, '2026-05-30 20:43:54'),
(13, 1, 84, '2026-06-16 18:09:49', '2026-06-28 18:09:49', 'PENDING', NULL, NULL),
(14, 1, 22, '2026-06-21 04:11:28', '2026-07-18 04:11:28', 'REJECTED', NULL, '2026-06-21 04:11:28'),
(15, 1, 115, '2026-06-03 18:40:35', '2026-06-26 18:40:35', 'PENDING', NULL, NULL),
(16, 1, 100, '2026-07-20 04:14:39', '2026-08-03 04:14:39', 'ACCEPTED', 62, '2026-07-17 04:14:39'),
(17, 1, 10, '2026-06-29 10:26:36', '2026-07-04 10:26:36', 'PENDING', NULL, NULL),
(18, 1, 84, '2026-07-16 03:25:39', '2026-07-27 03:25:39', 'PENDING', NULL, NULL),
(19, 1, 109, '2026-06-08 06:37:27', '2026-06-22 06:37:27', 'REJECTED', 60, '2026-06-06 06:37:27'),
(20, 1, 118, '2026-07-07 13:45:08', '2026-07-23 13:45:08', 'PENDING', NULL, NULL),
(21, 1, 88, '2026-06-21 19:10:09', '2026-07-11 19:10:09', 'ACCEPTED', 62, '2026-06-19 19:10:09'),
(22, 1, 89, '2026-06-27 04:05:03', '2026-07-13 04:05:03', 'REJECTED', 69, '2026-06-25 04:05:03'),
(23, 1, 101, '2026-06-24 11:03:40', '2026-07-11 11:03:40', 'REJECTED', 63, '2026-06-23 11:03:40'),
(24, 1, 30, '2026-07-11 13:33:26', '2026-07-21 13:33:26', 'REJECTED', 70, '2026-07-09 13:33:26'),
(25, 1, 15, '2026-06-24 12:25:06', '2026-07-21 12:25:06', 'REJECTED', NULL, '2026-06-26 12:25:06'),
(26, 1, 84, '2026-07-22 00:51:32', '2026-08-01 00:51:32', 'ACCEPTED', 62, '2026-07-18 00:51:32'),
(27, 1, 3, '2026-06-13 03:57:52', '2026-06-18 03:57:52', 'REJECTED', NULL, '2026-06-15 03:57:52'),
(28, 1, 104, '2026-06-19 09:03:44', '2026-07-06 09:03:44', 'ACCEPTED', 67, '2026-06-14 09:03:44'),
(29, 1, 19, '2026-07-30 11:49:04', '2026-08-11 11:49:04', 'REJECTED', 58, '2026-07-27 11:49:04'),
(30, 1, 108, '2026-07-22 15:56:06', '2026-08-03 15:56:06', 'REJECTED', NULL, '2026-07-24 15:56:06'),
(31, 1, 92, '2026-07-13 01:11:30', '2026-08-05 01:11:30', 'ACCEPTED', 54, '2026-07-09 01:11:30'),
(32, 1, 73, '2026-07-09 22:20:24', '2026-07-30 22:20:24', 'REJECTED', 60, '2026-07-07 22:20:24'),
(33, 1, 115, '2026-07-14 05:40:12', '2026-08-05 05:40:12', 'PENDING', NULL, NULL),
(34, 1, 89, '2026-06-23 02:26:58', '2026-07-10 02:26:58', 'ACCEPTED', 57, '2026-06-19 02:26:58'),
(35, 1, 123, '2026-07-25 14:16:00', '2026-08-03 14:16:00', 'REJECTED', 59, '2026-07-22 14:16:00'),
(36, 1, 98, '2026-06-03 21:14:10', '2026-06-17 21:14:10', 'REJECTED', NULL, '2026-06-04 21:14:10'),
(37, 1, 48, '2026-06-26 21:55:37', '2026-07-22 21:55:37', 'REJECTED', 67, '2026-06-25 21:55:37'),
(38, 1, 126, '2026-07-13 04:47:21', '2026-08-06 04:47:21', 'PENDING', NULL, NULL),
(39, 1, 39, '2026-06-01 11:17:47', '2026-06-23 11:17:47', 'PENDING', NULL, NULL),
(40, 1, 18, '2026-07-30 02:46:38', '2026-08-10 02:46:38', 'PENDING', NULL, NULL),
(41, 1, 2, '2026-06-01 22:48:12', '2026-06-22 22:48:12', 'ACCEPTED', 62, '2026-05-31 22:48:12'),
(42, 1, 113, '2026-06-04 11:08:58', '2026-06-12 11:08:58', 'PENDING', NULL, NULL),
(43, 1, 116, '2026-07-09 12:24:04', '2026-07-23 12:24:04', 'REJECTED', NULL, '2026-07-10 12:24:04'),
(44, 1, 90, '2026-06-29 16:31:54', '2026-07-18 16:31:54', 'ACCEPTED', 52, '2026-06-24 16:31:54'),
(45, 1, 128, '2026-06-18 06:21:56', '2026-06-26 06:21:56', 'PENDING', NULL, NULL),
(46, 1, 24, '2026-07-25 21:03:33', '2026-08-20 21:03:33', 'PENDING', NULL, NULL),
(47, 1, 23, '2026-07-04 14:49:53', '2026-07-18 14:49:53', 'REJECTED', 69, '2026-07-02 14:49:53'),
(48, 1, 42, '2026-06-01 14:11:53', '2026-06-16 14:11:53', 'REJECTED', 63, '2026-05-29 14:11:53'),
(49, 1, 88, '2026-06-14 06:03:29', '2026-06-19 06:03:29', 'PENDING', NULL, NULL),
(50, 1, 24, '2026-06-27 00:32:30', '2026-07-24 00:32:30', 'PENDING', NULL, NULL),
(51, 1, 92, '2026-07-13 07:54:27', '2026-08-09 07:54:27', 'REJECTED', NULL, '2026-07-15 07:54:27'),
(52, 1, 9, '2026-07-27 19:11:21', '2026-08-01 19:11:21', 'ACCEPTED', 51, '2026-07-26 19:11:21'),
(53, 1, 132, '2026-06-04 17:17:35', '2026-06-10 17:17:35', 'PENDING', NULL, NULL),
(54, 1, 8, '2026-06-21 15:03:28', '2026-07-15 15:03:28', 'ACCEPTED', 66, '2026-06-20 15:03:28'),
(55, 1, 79, '2026-06-11 11:29:28', '2026-06-22 11:29:28', 'ACCEPTED', 69, '2026-06-07 11:29:28'),
(56, 1, 87, '2026-07-15 07:59:08', '2026-07-30 07:59:08', 'PENDING', NULL, NULL),
(57, 1, 124, '2026-07-18 05:41:11', '2026-08-08 05:41:11', 'PENDING', NULL, NULL),
(58, 1, 25, '2026-07-23 16:30:10', '2026-08-17 16:30:10', 'REJECTED', 67, '2026-07-22 16:30:10'),
(59, 1, 78, '2026-06-06 23:55:33', '2026-07-04 23:55:33', 'PENDING', NULL, NULL),
(60, 1, 10, '2026-07-05 02:04:47', '2026-07-29 02:04:47', 'REJECTED', 58, '2026-07-03 02:04:47'),
(61, 1, 122, '2026-06-03 21:18:20', '2026-06-22 21:18:20', 'ACCEPTED', 63, '2026-06-01 21:18:20'),
(62, 1, 23, '2026-07-06 03:27:01', '2026-07-25 03:27:01', 'ACCEPTED', 53, '2026-07-02 03:27:01'),
(63, 1, 99, '2026-07-22 21:41:17', '2026-08-15 21:41:17', 'ACCEPTED', 53, '2026-07-21 21:41:17'),
(64, 1, 125, '2026-06-25 00:29:12', '2026-07-19 00:29:12', 'ACCEPTED', 61, '2026-06-22 00:29:12'),
(65, 1, 25, '2026-06-15 08:07:03', '2026-07-10 08:07:03', 'REJECTED', 69, '2026-06-14 08:07:03'),
(66, 1, 10, '2026-06-25 17:04:19', '2026-07-22 17:04:19', 'REJECTED', 62, '2026-06-23 17:04:19'),
(67, 1, 78, '2026-07-01 04:59:46', '2026-07-18 04:59:46', 'REJECTED', 56, '2026-06-28 04:59:46'),
(68, 1, 87, '2026-06-10 15:55:07', '2026-06-20 15:55:07', 'ACCEPTED', 67, '2026-06-09 15:55:07'),
(69, 1, 115, '2026-06-15 15:15:21', '2026-06-20 15:15:21', 'PENDING', NULL, NULL),
(70, 1, 127, '2026-07-06 08:02:21', '2026-07-19 08:02:21', 'PENDING', NULL, NULL),
(71, 1, 130, '2026-07-21 10:08:10', '2026-08-02 10:08:10', 'ACCEPTED', 57, '2026-07-19 10:08:10'),
(72, 1, 21, '2026-07-15 17:13:26', '2026-08-08 17:13:26', 'REJECTED', 51, '2026-07-13 17:13:26'),
(73, 1, 77, '2026-06-07 06:09:40', '2026-06-14 06:09:40', 'ACCEPTED', 57, '2026-06-03 06:09:40'),
(74, 1, 126, '2026-07-06 13:11:11', '2026-07-29 13:11:11', 'ACCEPTED', 53, '2026-07-05 13:11:11'),
(75, 1, 99, '2026-06-19 09:37:26', '2026-07-15 09:37:26', 'PENDING', NULL, NULL),
(76, 1, 122, '2026-06-07 15:31:48', '2026-06-18 15:31:48', 'REJECTED', NULL, '2026-06-07 15:31:48'),
(77, 1, 10, '2026-07-25 09:56:54', '2026-08-22 09:56:54', 'ACCEPTED', 57, '2026-07-23 09:56:54'),
(78, 1, 114, '2026-07-30 00:30:19', '2026-08-13 00:30:19', 'ACCEPTED', 68, '2026-07-26 00:30:19'),
(79, 1, 3, '2026-06-12 02:48:25', '2026-07-03 02:48:25', 'PENDING', NULL, NULL),
(80, 1, 28, '2026-06-16 00:45:24', '2026-07-14 00:45:24', 'ACCEPTED', 69, '2026-06-11 00:45:24'),
(81, 1, 79, '2026-06-03 19:28:05', '2026-06-12 19:28:05', 'PENDING', NULL, NULL),
(82, 1, 13, '2026-07-10 12:10:54', '2026-08-09 12:10:54', 'ACCEPTED', 60, '2026-07-06 12:10:54'),
(83, 1, 17, '2026-07-04 03:05:47', '2026-07-11 03:05:47', 'PENDING', NULL, NULL),
(84, 1, 38, '2026-07-18 22:44:39', '2026-07-24 22:44:39', 'ACCEPTED', 58, '2026-07-13 22:44:39'),
(85, 1, 17, '2026-06-01 10:33:30', '2026-07-01 10:33:30', 'ACCEPTED', 52, '2026-05-28 10:33:30'),
(86, 1, 85, '2026-07-28 06:26:44', '2026-08-25 06:26:44', 'PENDING', NULL, NULL),
(87, 1, 26, '2026-07-05 18:30:19', '2026-07-19 18:30:19', 'ACCEPTED', 61, '2026-07-02 18:30:19'),
(88, 1, 114, '2026-06-24 13:00:29', '2026-07-02 13:00:29', 'ACCEPTED', 56, '2026-06-21 13:00:29'),
(89, 1, 83, '2026-07-30 01:36:41', '2026-08-17 01:36:41', 'PENDING', NULL, NULL),
(90, 1, 125, '2026-07-25 22:30:48', '2026-08-17 22:30:48', 'REJECTED', 66, '2026-07-22 22:30:48'),
(91, 1, 16, '2026-07-23 03:12:53', '2026-08-11 03:12:53', 'PENDING', NULL, NULL),
(92, 1, 44, '2026-06-24 06:08:01', '2026-07-22 06:08:01', 'ACCEPTED', 66, '2026-06-19 06:08:01'),
(93, 1, 96, '2026-06-29 04:21:50', '2026-07-12 04:21:50', 'PENDING', NULL, NULL),
(94, 1, 93, '2026-06-28 00:42:45', '2026-07-06 00:42:45', 'REJECTED', NULL, '2026-06-28 00:42:45'),
(95, 1, 75, '2026-06-11 01:18:11', '2026-06-27 01:18:11', 'ACCEPTED', 53, '2026-06-06 01:18:11'),
(96, 1, 33, '2026-07-02 00:32:51', '2026-07-19 00:32:51', 'PENDING', NULL, NULL),
(97, 1, 110, '2026-07-13 19:47:54', '2026-08-04 19:47:54', 'REJECTED', 63, '2026-07-10 19:47:54'),
(98, 1, 91, '2026-07-18 06:36:14', '2026-08-09 06:36:14', 'ACCEPTED', 61, '2026-07-17 06:36:14'),
(99, 1, 21, '2026-06-27 16:59:03', '2026-07-03 16:59:03', 'PENDING', NULL, NULL),
(100, 1, 11, '2026-07-05 11:12:22', '2026-08-03 11:12:22', 'ACCEPTED', 58, '2026-06-30 11:12:22'),
(101, 1, 115, '2026-06-03 00:39:41', '2026-06-12 00:39:41', 'PENDING', NULL, NULL),
(102, 1, 82, '2026-07-15 08:08:48', '2026-08-13 08:08:48', 'ACCEPTED', 52, '2026-07-10 08:08:48'),
(103, 1, 75, '2026-07-21 18:11:45', '2026-08-15 18:11:45', 'REJECTED', 54, '2026-07-18 18:11:45'),
(104, 1, 24, '2026-06-15 06:19:35', '2026-07-09 06:19:35', 'REJECTED', NULL, '2026-06-17 06:19:35'),
(105, 1, 97, '2026-06-29 12:59:01', '2026-07-05 12:59:01', 'PENDING', NULL, NULL),
(106, 1, 24, '2026-06-02 17:10:17', '2026-06-07 17:10:17', 'REJECTED', NULL, '2026-06-04 17:10:17'),
(107, 1, 35, '2026-06-21 16:42:22', '2026-07-15 16:42:22', 'PENDING', NULL, NULL),
(108, 1, 130, '2026-06-21 23:40:06', '2026-07-09 23:40:06', 'PENDING', NULL, NULL),
(109, 1, 111, '2026-07-09 12:20:41', '2026-07-21 12:20:41', 'REJECTED', NULL, '2026-07-09 12:20:41'),
(110, 1, 90, '2026-07-23 08:27:09', '2026-08-09 08:27:09', 'PENDING', NULL, NULL),
(111, 1, 116, '2026-06-08 21:36:28', '2026-06-15 21:36:28', 'PENDING', NULL, NULL),
(112, 1, 74, '2026-07-13 03:44:33', '2026-07-20 03:44:33', 'PENDING', NULL, NULL),
(113, 1, 82, '2026-06-18 23:01:18', '2026-07-16 23:01:18', 'PENDING', NULL, NULL),
(114, 1, 103, '2026-06-26 23:36:31', '2026-07-09 23:36:31', 'REJECTED', 53, '2026-06-23 23:36:31'),
(115, 1, 4, '2026-06-08 22:28:31', '2026-06-14 22:28:31', 'PENDING', NULL, NULL),
(116, 1, 89, '2026-06-07 02:21:28', '2026-06-26 02:21:28', 'REJECTED', 70, '2026-06-04 02:21:28'),
(117, 1, 24, '2026-07-21 17:39:25', '2026-08-04 17:39:25', 'REJECTED', 69, '2026-07-20 17:39:25'),
(118, 1, 72, '2026-06-22 08:09:06', '2026-07-17 08:09:06', 'REJECTED', 66, '2026-06-20 08:09:06'),
(119, 1, 5, '2026-06-29 07:29:46', '2026-07-29 07:29:46', 'PENDING', NULL, NULL),
(120, 1, 130, '2026-06-09 17:37:42', '2026-06-22 17:37:42', 'REJECTED', 57, '2026-06-08 17:37:42'),
(121, 1, 81, '2026-06-26 22:27:49', '2026-07-14 22:27:49', 'REJECTED', NULL, '2026-06-28 22:27:49'),
(122, 1, 100, '2026-06-14 20:34:19', '2026-07-12 20:34:19', 'PENDING', NULL, NULL),
(123, 1, 117, '2026-07-17 07:56:16', '2026-08-14 07:56:16', 'ACCEPTED', 63, '2026-07-13 07:56:16'),
(124, 1, 4, '2026-06-25 13:41:17', '2026-07-25 13:41:17', 'REJECTED', 53, '2026-06-23 13:41:17'),
(125, 1, 12, '2026-06-17 23:36:17', '2026-07-06 23:36:17', 'ACCEPTED', 62, '2026-06-13 23:36:17'),
(126, 1, 1, '2026-06-17 04:37:48', '2026-07-08 04:37:48', 'REJECTED', NULL, '2026-06-17 04:37:48'),
(127, 1, 41, '2026-07-04 11:02:40', '2026-07-11 11:02:40', 'REJECTED', 53, '2026-07-01 11:02:40'),
(128, 1, 14, '2026-07-19 14:13:43', '2026-08-01 14:13:43', 'REJECTED', 64, '2026-07-16 14:13:43'),
(129, 1, 91, '2026-06-15 08:29:21', '2026-06-20 08:29:21', 'ACCEPTED', 64, '2026-06-10 08:29:21'),
(130, 1, 100, '2026-07-04 01:34:57', '2026-07-18 01:34:57', 'ACCEPTED', 58, '2026-06-29 01:34:57'),
(131, 1, 3, '2026-06-30 06:40:05', '2026-07-26 06:40:05', 'PENDING', NULL, NULL),
(132, 1, 97, '2026-07-02 01:21:52', '2026-07-31 01:21:52', 'REJECTED', 57, '2026-07-01 01:21:52'),
(133, 1, 123, '2026-07-30 12:41:51', '2026-08-04 12:41:51', 'PENDING', NULL, NULL),
(134, 1, 130, '2026-07-28 09:08:32', '2026-08-08 09:08:32', 'REJECTED', 62, '2026-07-25 09:08:32'),
(135, 1, 92, '2026-07-24 18:12:37', '2026-08-04 18:12:37', 'PENDING', NULL, NULL),
(136, 1, 104, '2026-07-30 05:51:58', '2026-08-25 05:51:58', 'PENDING', NULL, NULL),
(137, 1, 84, '2026-07-25 12:57:54', '2026-08-07 12:57:54', 'PENDING', NULL, NULL),
(138, 1, 103, '2026-06-29 07:39:05', '2026-07-24 07:39:05', 'ACCEPTED', 59, '2026-06-25 07:39:05'),
(139, 1, 18, '2026-06-15 15:03:34', '2026-06-23 15:03:34', 'PENDING', NULL, NULL),
(140, 1, 31, '2026-07-06 17:12:36', '2026-07-12 17:12:36', 'REJECTED', NULL, '2026-07-08 17:12:36'),
(141, 1, 106, '2026-06-18 07:04:36', '2026-07-14 07:04:36', 'REJECTED', 65, '2026-06-15 07:04:36'),
(142, 1, 82, '2026-06-02 11:52:46', '2026-06-18 11:52:46', 'REJECTED', 58, '2026-05-31 11:52:46'),
(143, 1, 45, '2026-06-29 22:35:38', '2026-07-07 22:35:38', 'PENDING', NULL, NULL),
(144, 1, 82, '2026-07-04 07:53:50', '2026-07-27 07:53:50', 'REJECTED', 70, '2026-07-03 07:53:50'),
(145, 1, 100, '2026-06-16 13:18:07', '2026-07-10 13:18:07', 'PENDING', NULL, NULL),
(146, 1, 16, '2026-06-23 13:38:46', '2026-07-15 13:38:46', 'PENDING', NULL, NULL),
(147, 1, 97, '2026-06-08 22:53:51', '2026-06-23 22:53:51', 'PENDING', NULL, NULL),
(148, 1, 111, '2026-06-30 07:00:42', '2026-07-10 07:00:42', 'ACCEPTED', 60, '2026-06-25 07:00:42'),
(149, 1, 106, '2026-07-26 22:07:27', '2026-08-09 22:07:27', 'ACCEPTED', 67, '2026-07-23 22:07:27'),
(150, 1, 77, '2026-07-30 01:49:26', '2026-08-08 01:49:26', 'REJECTED', 60, '2026-07-27 01:49:26'),
(151, 1, 114, '2026-06-05 02:36:29', '2026-06-26 02:36:29', 'ACCEPTED', 55, '2026-06-03 02:36:29'),
(152, 1, 82, '2026-06-24 15:16:54', '2026-07-24 15:16:54', 'REJECTED', 51, '2026-06-22 15:16:54'),
(153, 1, 26, '2026-06-22 07:09:44', '2026-07-10 07:09:44', 'PENDING', NULL, NULL),
(154, 1, 121, '2026-06-10 01:17:36', '2026-06-23 01:17:36', 'REJECTED', 69, '2026-06-08 01:17:36'),
(155, 1, 130, '2026-06-06 03:00:28', '2026-06-15 03:00:28', 'ACCEPTED', 67, '2026-06-05 03:00:28'),
(156, 1, 49, '2026-06-17 07:08:18', '2026-07-10 07:08:18', 'PENDING', NULL, NULL),
(157, 1, 96, '2026-06-15 16:38:31', '2026-06-28 16:38:31', 'PENDING', NULL, NULL),
(158, 1, 3, '2026-06-04 06:38:16', '2026-06-19 06:38:16', 'PENDING', NULL, NULL),
(159, 1, 38, '2026-06-03 20:04:02', '2026-06-30 20:04:02', 'ACCEPTED', 60, '2026-05-31 20:04:02'),
(160, 1, 82, '2026-07-27 08:49:20', '2026-08-17 08:49:20', 'ACCEPTED', 61, '2026-07-26 08:49:20'),
(161, 1, 50, '2026-06-26 18:28:02', '2026-07-19 18:28:02', 'ACCEPTED', 55, '2026-06-23 18:28:02'),
(162, 1, 133, '2026-06-21 09:21:57', '2026-07-08 09:21:57', 'REJECTED', 55, '2026-06-19 09:21:57'),
(163, 1, 122, '2026-06-03 00:54:33', '2026-06-17 00:54:33', 'PENDING', NULL, NULL),
(164, 1, 22, '2026-06-16 13:26:09', '2026-06-21 13:26:09', 'PENDING', NULL, NULL),
(165, 1, 74, '2026-07-22 01:06:09', '2026-08-20 01:06:09', 'PENDING', NULL, NULL),
(166, 1, 39, '2026-07-15 17:52:14', '2026-08-02 17:52:14', 'PENDING', NULL, NULL),
(167, 1, 5, '2026-07-09 17:40:55', '2026-07-30 17:40:55', 'PENDING', NULL, NULL),
(168, 1, 77, '2026-07-10 08:35:22', '2026-07-22 08:35:22', 'PENDING', NULL, NULL),
(169, 1, 22, '2026-07-02 19:09:58', '2026-07-10 19:09:58', 'ACCEPTED', 55, '2026-07-01 19:09:58'),
(170, 1, 121, '2026-07-06 03:07:38', '2026-07-28 03:07:38', 'ACCEPTED', 51, '2026-07-05 03:07:38'),
(171, 1, 82, '2026-07-11 23:37:59', '2026-08-10 23:37:59', 'REJECTED', 57, '2026-07-09 23:37:59'),
(172, 1, 109, '2026-06-13 05:42:13', '2026-07-08 05:42:13', 'PENDING', NULL, NULL),
(173, 1, 90, '2026-07-28 00:05:25', '2026-08-03 00:05:25', 'PENDING', NULL, NULL),
(174, 1, 2, '2026-07-08 21:55:40', '2026-08-01 21:55:40', 'PENDING', NULL, NULL),
(175, 1, 10, '2026-06-14 09:44:27', '2026-06-21 09:44:27', 'REJECTED', 66, '2026-06-11 09:44:27'),
(176, 1, 21, '2026-06-12 01:08:28', '2026-07-02 01:08:28', 'PENDING', NULL, NULL),
(177, 1, 50, '2026-06-30 09:15:18', '2026-07-30 09:15:18', 'PENDING', NULL, NULL),
(178, 1, 19, '2026-07-02 13:25:03', '2026-07-15 13:25:03', 'PENDING', NULL, NULL),
(179, 1, 43, '2026-06-17 20:28:27', '2026-06-24 20:28:27', 'PENDING', NULL, NULL),
(180, 1, 102, '2026-06-13 05:49:29', '2026-07-05 05:49:29', 'ACCEPTED', 68, '2026-06-12 05:49:29'),
(181, 1, 114, '2026-06-18 05:28:37', '2026-07-16 05:28:37', 'REJECTED', 65, '2026-06-16 05:28:37'),
(182, 1, 7, '2026-07-13 14:56:54', '2026-07-19 14:56:54', 'ACCEPTED', 60, '2026-07-12 14:56:54'),
(183, 1, 31, '2026-07-10 09:53:18', '2026-08-04 09:53:18', 'REJECTED', 61, '2026-07-07 09:53:18'),
(184, 1, 88, '2026-06-15 18:38:59', '2026-06-28 18:38:59', 'REJECTED', 70, '2026-06-13 18:38:59'),
(185, 1, 27, '2026-07-15 01:04:07', '2026-07-31 01:04:07', 'ACCEPTED', 57, '2026-07-13 01:04:07'),
(186, 1, 119, '2026-07-06 17:17:26', '2026-07-28 17:17:26', 'PENDING', NULL, NULL),
(187, 1, 16, '2026-06-19 00:38:24', '2026-07-14 00:38:24', 'PENDING', NULL, NULL),
(188, 1, 13, '2026-06-08 20:49:03', '2026-06-14 20:49:03', 'ACCEPTED', 70, '2026-06-07 20:49:03'),
(189, 1, 91, '2026-06-24 00:22:42', '2026-07-15 00:22:42', 'REJECTED', NULL, '2026-06-24 00:22:42'),
(190, 1, 35, '2026-07-18 15:23:17', '2026-07-29 15:23:17', 'PENDING', NULL, NULL),
(191, 1, 19, '2026-06-28 02:36:54', '2026-07-26 02:36:54', 'REJECTED', 64, '2026-06-27 02:36:54'),
(192, 1, 120, '2026-06-19 07:33:27', '2026-07-04 07:33:27', 'REJECTED', 55, '2026-06-16 07:33:27'),
(193, 1, 117, '2026-06-28 09:12:51', '2026-07-17 09:12:51', 'ACCEPTED', 60, '2026-06-25 09:12:51'),
(194, 1, 96, '2026-07-20 15:41:05', '2026-07-29 15:41:05', 'PENDING', NULL, NULL),
(195, 1, 11, '2026-07-05 23:45:05', '2026-07-10 23:45:05', 'PENDING', NULL, NULL),
(196, 1, 72, '2026-06-15 00:09:10', '2026-07-14 00:09:10', 'ACCEPTED', 56, '2026-06-13 00:09:10'),
(197, 1, 87, '2026-06-10 21:07:27', '2026-07-03 21:07:27', 'REJECTED', 61, '2026-06-08 21:07:27'),
(198, 1, 40, '2026-06-26 18:03:09', '2026-07-25 18:03:09', 'ACCEPTED', 69, '2026-06-24 18:03:09'),
(199, 1, 77, '2026-07-02 03:44:53', '2026-07-23 03:44:53', 'REJECTED', NULL, '2026-07-04 03:44:53'),
(200, 1, 30, '2026-07-10 00:35:46', '2026-07-21 00:35:46', 'REJECTED', 60, '2026-07-08 00:35:46');

-- Storage Reservations
INSERT INTO storage_reservation (reservation_id, request_id, party_id, shelf_id, reserved_weight, reserved_volume, reserved_from, reserved_until, status) VALUES
(3, 4, 81, 13, 907.15, 8.73, '2026-06-25 18:53:43', '2026-07-22 18:53:43', 'PENDING'),
(11, 34, 89, 15, 416.31, 3.7, '2026-06-23 02:26:58', '2026-07-10 02:26:58', 'PENDING'),
(13, 44, 90, 1, 415.39, 8.76, '2026-06-29 16:31:54', '2026-07-18 16:31:54', 'EXPIRED'),
(22, 71, 130, 5, 528.6, 6.75, '2026-07-21 10:08:10', '2026-08-02 10:08:10', 'EXPIRED'),
(24, 74, 126, 10, 890.79, 6.22, '2026-07-06 13:11:11', '2026-07-29 13:11:11', 'ACTIVE'),
(26, 78, 114, 14, 734.53, 7.43, '2026-07-30 00:30:19', '2026-08-13 00:30:19', 'ACTIVE'),
(29, 84, 38, 15, 415.95, 1.26, '2026-07-18 22:44:39', '2026-07-24 22:44:39', 'ACTIVE'),
(34, 95, 75, 3, 112.74, 7.18, '2026-06-11 01:18:11', '2026-06-27 01:18:11', 'ACTIVE'),
(38, 123, 117, 4, 875.98, 6.68, '2026-07-17 07:56:16', '2026-08-14 07:56:16', 'EXPIRED'),
(39, 125, 12, 12, 355.82, 2.91, '2026-06-17 23:36:17', '2026-07-06 23:36:17', 'CANCELLED'),
(44, 149, 106, 6, 912.94, 2.04, '2026-07-26 22:07:27', '2026-08-09 22:07:27', 'EXPIRED'),
(53, 182, 7, 6, 783.19, 7.71, '2026-07-13 14:56:54', '2026-07-19 14:56:54', 'PENDING'),
(56, 193, 117, 11, 802.6, 1.61, '2026-06-28 09:12:51', '2026-07-17 09:12:51', 'EXPIRED'),
(57, 196, 72, 3, 605.58, 2.27, '2026-06-15 00:09:10', '2026-07-14 00:09:10', 'PENDING');

-- Storage Records
INSERT INTO storage_record (storage_record_id, request_id, party_id, shelf_id, actual_entry_date, actual_exit_date, cargo_description, cargo_weight, cargo_volume) VALUES
(1, 4, 81, 13, '2026-06-25 18:53:43', NULL, 'Parent radio grow.', 864.36, 6.47),
(2, 34, 89, 15, '2026-06-23 02:26:58', NULL, 'Fast speak.', 807.91, 1.85),
(3, 44, 90, 1, '2026-06-29 16:31:54', NULL, 'Show international myself assume.', 693.97, 5.24),
(4, 71, 130, 5, '2026-07-21 10:08:10', '2026-07-28 10:08:10', 'Type throughout stuff.', 826.6, 1.21),
(5, 74, 126, 10, '2026-07-06 13:11:11', '2026-07-15 13:11:11', 'Father act cell.', 419.25, 8.79),
(6, 78, 114, 14, '2026-07-30 00:30:19', '2026-08-09 00:30:19', 'Hotel audience difficult free have.', 816.06, 9.72),
(7, 84, 38, 15, '2026-07-18 22:44:39', NULL, 'Option personal force agency remember.', 126.7, 1.4),
(8, 95, 75, 3, '2026-06-11 01:18:11', '2026-06-20 01:18:11', 'Loss yourself store easy.', 124.54, 1.99),
(9, 123, 117, 4, '2026-07-17 07:56:16', NULL, 'Card surface environment security.', 877.26, 1.58),
(10, 125, 12, 12, '2026-06-17 23:36:17', '2026-06-22 23:36:17', 'Reduce different on.', 391.94, 7.82),
(11, 149, 106, 6, '2026-07-26 22:07:27', '2026-08-03 22:07:27', 'Rise travel total.', 467.12, 1.95),
(12, 182, 7, 6, '2026-07-13 14:56:54', '2026-07-14 14:56:54', 'Cut allow.', 364.97, 1.72),
(13, 193, 117, 11, '2026-06-28 09:12:51', '2026-07-01 09:12:51', 'Ready instead whole.', 167.94, 4.17),
(14, 196, 72, 3, '2026-06-15 00:09:10', NULL, 'Writer begin institution us.', 456.06, 6.53);

-- Cargo Event History
INSERT INTO cargo_event_history (event_id, party_id, storage_record_id, event_type_id, event_time, details) VALUES
(1, 70, 1, 1, '2026-06-23 01:13:55', '{"note": "Particular institution head culture travel guess decide.", "performed_by": "Holly Ford", "location": "protect"}'::jsonb),
(2, 70, 2, 2, '2026-06-06 18:10:07', '{"note": "Condition to key per in sure of certainly.", "performed_by": "Sabrina Orr", "location": "foreign"}'::jsonb),
(3, 60, 3, 3, '2026-06-05 09:17:27', '{"note": "Beautiful participant quality kitchen water law hope.", "performed_by": "Charles Coffey", "location": "mouth"}'::jsonb),
(4, 54, 4, 4, '2026-06-05 16:54:17', '{"note": "Once probably whatever glass.", "performed_by": "Chelsea Davis", "location": "role"}'::jsonb);

-- Payments
INSERT INTO payment (payment_id, storage_record_id, party_id, amount, currency, status, payment_date, external_reference) VALUES
(1, 1, 14, 1309.34, 'USD', 'FAILED', '2026-06-27 19:12:19', 'PAY-20260701-0001'),
(2, 2, 5, 1223.4, 'PLN', 'FAILED', '2026-06-19 20:51:05', 'PAY-20260701-0002'),
(3, 3, 42, 720.45, 'USD', 'CANCELLED', '2026-06-01 09:15:50', 'PAY-20260701-0003'),
(4, 4, 114, 662.54, 'USD', 'PAID', '2026-06-20 21:02:16', 'PAY-20260701-0004'),
(5, 5, 26, 579.54, 'USD', 'PENDING', NULL, 'PAY-20260701-0005'),
(6, 6, 72, 1191.35, 'PLN', 'CANCELLED', '2026-06-23 04:20:28', 'PAY-20260701-0006'),
(7, 7, 87, 926.97, 'USD', 'FAILED', '2026-06-14 15:56:47', 'PAY-20260701-0007'),
(8, 8, 119, 795.13, 'PLN', 'PENDING', NULL, 'PAY-20260701-0008'),
(9, 9, 27, 1959.78, 'USD', 'PAID', '2026-06-11 00:38:03', 'PAY-20260701-0009'),
(10, 10, 11, 955.65, 'USD', 'PENDING', NULL, 'PAY-20260701-0010'),
(11, 11, 123, 955.95, 'USD', 'PAID', '2026-06-19 12:02:41', 'PAY-20260701-0011'),
(12, 12, 116, 757.64, 'PLN', 'PAID', '2026-06-16 13:37:18', 'PAY-20260701-0012'),
(13, 13, 126, 1281.28, 'EUR', 'FAILED', '2026-06-30 17:25:59', 'PAY-20260701-0013'),
(14, 14, 120, 703.41, 'USD', 'PENDING', NULL, 'PAY-20260701-0014'),
(15, 1, 45, 514.65, 'PLN', 'FAILED', '2026-06-27 09:12:53', 'PAY-20260701-0015'),
(16, 2, 120, 955.97, 'USD', 'FAILED', '2026-06-04 00:39:03', 'PAY-20260701-0016'),
(17, 3, 128, 628.7, 'USD', 'PENDING', NULL, 'PAY-20260701-0017'),
(18, 4, 7, 1994.79, 'USD', 'CANCELLED', '2026-06-21 23:20:05', 'PAY-20260701-0018'),
(19, 5, 92, 1885.71, 'EUR', 'CANCELLED', '2026-06-05 22:42:23', 'PAY-20260701-0019'),
(20, 6, 37, 594.82, 'PLN', 'PAID', '2026-06-10 04:58:06', 'PAY-20260701-0020'),
(21, 7, 10, 587.96, 'PLN', 'PAID', '2026-06-10 23:48:54', 'PAY-20260701-0021'),
(22, 8, 29, 1814.11, 'PLN', 'PAID', '2026-06-07 04:12:48', 'PAY-20260701-0022'),
(23, 9, 50, 1005.6, 'USD', 'PENDING', NULL, 'PAY-20260701-0023'),
(24, 10, 79, 1355.97, 'USD', 'PENDING', NULL, 'PAY-20260701-0024'),
(25, 11, 110, 1202.17, 'USD', 'PENDING', NULL, 'PAY-20260701-0025'),
(26, 12, 25, 1081.16, 'EUR', 'PAID', '2026-06-21 14:19:42', 'PAY-20260701-0026'),
(27, 13, 5, 1521.51, 'PLN', 'PENDING', NULL, 'PAY-20260701-0027'),
(28, 14, 85, 805.54, 'EUR', 'CANCELLED', '2026-06-22 04:28:04', 'PAY-20260701-0028'),
(29, 1, 86, 1467.91, 'PLN', 'PAID', '2026-06-20 11:13:56', 'PAY-20260701-0029'),
(30, 2, 110, 1063.95, 'EUR', 'PENDING', NULL, 'PAY-20260701-0030'),
(31, 3, 14, 1294.99, 'USD', 'FAILED', '2026-06-01 05:10:24', 'PAY-20260701-0031'),
(32, 4, 88, 1868.77, 'PLN', 'FAILED', '2026-06-29 03:24:26', 'PAY-20260701-0032'),
(33, 5, 3, 1229.55, 'EUR', 'CANCELLED', '2026-06-03 13:46:12', 'PAY-20260701-0033'),
(34, 6, 87, 777.03, 'PLN', 'FAILED', '2026-06-07 07:51:38', 'PAY-20260701-0034'),
(35, 7, 87, 1033.64, 'USD', 'PAID', '2026-06-08 10:05:56', 'PAY-20260701-0035'),
(36, 8, 21, 952.86, 'USD', 'CANCELLED', '2026-06-29 18:07:17', 'PAY-20260701-0036'),
(37, 9, 26, 1881.13, 'USD', 'CANCELLED', '2026-06-20 13:11:08', 'PAY-20260701-0037'),
(38, 10, 44, 570.38, 'USD', 'CANCELLED', '2026-06-20 12:02:10', 'PAY-20260701-0038'),
(39, 11, 13, 1415.87, 'USD', 'FAILED', '2026-06-26 09:46:44', 'PAY-20260701-0039'),
(40, 12, 71, 1532.76, 'EUR', 'PAID', '2026-06-25 03:13:08', 'PAY-20260701-0040');


-- Resync SERIAL sequences with seeded data (so API inserts don't collide)
SELECT setval(pg_get_serial_sequence('location', 'location_id'), (SELECT COALESCE(MAX(location_id), 1) FROM location));
SELECT setval(pg_get_serial_sequence('warehouse', 'warehouse_id'), (SELECT COALESCE(MAX(warehouse_id), 1) FROM warehouse));
SELECT setval(pg_get_serial_sequence('zone', 'zone_id'), (SELECT COALESCE(MAX(zone_id), 1) FROM zone));
SELECT setval(pg_get_serial_sequence('aisle', 'aisle_id'), (SELECT COALESCE(MAX(aisle_id), 1) FROM aisle));
SELECT setval(pg_get_serial_sequence('rack', 'rack_id'), (SELECT COALESCE(MAX(rack_id), 1) FROM rack));
SELECT setval(pg_get_serial_sequence('shelf', 'shelf_id'), (SELECT COALESCE(MAX(shelf_id), 1) FROM shelf));
SELECT setval(pg_get_serial_sequence('capacity', 'capacity_id'), (SELECT COALESCE(MAX(capacity_id), 1) FROM capacity));
SELECT setval(pg_get_serial_sequence('party', 'party_id'), (SELECT COALESCE(MAX(party_id), 1) FROM party));
SELECT setval(pg_get_serial_sequence('party_contact', 'contact_id'), (SELECT COALESCE(MAX(contact_id), 1) FROM party_contact));
SELECT setval(pg_get_serial_sequence('party_relationship', 'relationship_id'), (SELECT COALESCE(MAX(relationship_id), 1) FROM party_relationship));
SELECT setval(pg_get_serial_sequence('role', 'role_id'), (SELECT COALESCE(MAX(role_id), 1) FROM role));
SELECT setval(pg_get_serial_sequence('storage_request', 'request_id'), (SELECT COALESCE(MAX(request_id), 1) FROM storage_request));
SELECT setval(pg_get_serial_sequence('storage_reservation', 'reservation_id'), (SELECT COALESCE(MAX(reservation_id), 1) FROM storage_reservation));
SELECT setval(pg_get_serial_sequence('storage_record', 'storage_record_id'), (SELECT COALESCE(MAX(storage_record_id), 1) FROM storage_record));
SELECT setval(pg_get_serial_sequence('payment', 'payment_id'), (SELECT COALESCE(MAX(payment_id), 1) FROM payment));
SELECT setval(pg_get_serial_sequence('cargo_event_type', 'event_type_id'), (SELECT COALESCE(MAX(event_type_id), 1) FROM cargo_event_type));
SELECT setval(pg_get_serial_sequence('cargo_event_history', 'event_id'), (SELECT COALESCE(MAX(event_id), 1) FROM cargo_event_history));
